(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',key='',serial=0;
var parts=['左臂','头顶','右臂'],directions=['左侧','上方','右侧'];
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function make(){return {id:Date.now().toString(36)+'-'+(++serial),round:0,phase:'ready',left:3,ready:{A:false,B:false},armor:[2,2,2],hp:5,weak:0,dir:0,chain:0,event:0,effect:'',hit:-1,done:false,win:false,msg:'B 找弱点，A 攻击；A 看来袭，B 举盾。双方准备后开始。'};}
function attack(s){s.round++;s.phase='attack';s.left=8;s.weak=pick([0,1,2].filter(function(i){return s.armor[i]>0;}));s.msg='侦察窗口打开！B 报弱点，A 选择部位攻击。';}
function defense(s){s.round++;s.phase='defense';s.left=5;s.dir=pick([0,1,2]);s.msg=s.chain>0?'还有一发！重新报方向，再举盾。':'它鼓起腮帮要发射了！A 报来袭方向，B 举盾。';}
function finishBattle(s,win){s.done=true;s.win=win;s.phase='result';s.msg=win?'拆机成功！气鼓鼓号服气啦。':'护盾电量耗尽。下次先报清位置，再动手！';}
function impact(s,ok,slot){s.event++;s.hit=slot;s.effect=ok?(s.phase==='attack'?'hit':'block'):'miss';var was=s.phase;s.phase='impact';s.left=1.15;if(!ok){s.hp--;s.msg=was==='attack'?'打偏了，反弹消耗 1 格护盾。':'没挡住，消耗 1 格护盾。';}else if(was==='attack'){s.armor[slot]--;s.msg=s.armor[slot]===0?parts[slot]+'装甲拆掉了！':'命中'+parts[slot]+'！再来一下就能拆掉。';}else s.msg='挡住了！泡泡弹弹回去了。';if(s.hp<=0)finishBattle(s,false);else if(s.armor.every(function(n){return n===0;}))finishBattle(s,true);else if(was==='attack'){s.next='defense';s.chain=s.armor.filter(function(n){return n===0;}).length>=1?2:1;}else{s.chain--;s.next=s.chain>0?'defense':'attack';}}
function step(s,dt){if(s.done)return;if(s.phase==='ready'){if(!s.ready.A||!s.ready.B)return;s.left=Math.max(0,s.left-dt);if(s.left===0)attack(s);return;}s.left=Math.max(0,s.left-dt);if(s.left>0)return;if(s.phase==='impact'){if(s.next==='attack')attack(s);else defense(s);}else impact(s,false,-1);}
function input(s,d,who){if(!s||d.id!==s.id)return;if(d.t==='mbAgain'&&s.done){s['again'+who]=true;return;}if(s.done)return;if(d.t==='mbReady'&&s.phase==='ready'){s.ready[who]=true;return;}if(d.round!==s.round||!Number.isInteger(d.slot)||d.slot<0||d.slot>2)return;if(d.t==='mbAct'&&((s.phase==='attack'&&who==='A')||(s.phase==='defense'&&who==='B')))impact(s,d.slot===(s.phase==='attack'?s.weak:s.dir),d.slot);}
function snap(s,who){var v={id:s.id,round:s.round,phase:s.phase,left:s.left,ready:s.ready,armor:s.armor.slice(),hp:s.hp,chain:s.chain,event:s.event,effect:s.effect,hit:s.hit,done:s.done,win:s.win,msg:s.msg};if(who==='B'&&s.phase==='attack')v.weak=s.weak;if(who==='A'&&s.phase==='defense')v.dir=s.dir;return v;}
function act(t,slot){var s=role==='A'?active:view;if(!s)return;var d={t:t,id:s.id,round:s.round,slot:slot};if(role==='A')input(s,d,'A');else netSend(d);}
function clean(){if(dispose)dispose();dispose=null;active=null;view=null;key='';}
function shell(who){role=who;clearNetZones();window._keys={};$('app').innerHTML='<section class="mb-shell"><header><button id="back" aria-label="返回">‹</button><div><small>双人拆机战</small><h1>气鼓鼓号</h1></div><b class="mb-role">'+who+' · '+(who==='A'?'攻击手':'护盾手')+'</b></header><div class="mb-status"><b id="mb-hp"></b><span id="mb-armor"></span></div><div class="mb-arena"><svg id="mb-boss" viewBox="0 0 360 320" role="img" aria-label="气鼓鼓号机械怪"><ellipse cx="180" cy="284" rx="115" ry="15" fill="#a0cec0"/><g class="mb-machine"><path d="M129 258v17m102-17v17" stroke="#304f59" stroke-width="20" stroke-linecap="round"/><rect x="91" y="91" width="178" height="163" rx="68" fill="#f4ae72" stroke="#304f59" stroke-width="5"/><path d="M134 185q46 32 92 0" fill="none" stroke="#304f59" stroke-width="5" stroke-linecap="round"/><ellipse class="mb-cheek" cx="115" cy="169" rx="18" ry="13" fill="#ec826d"/><ellipse class="mb-cheek" cx="245" cy="169" rx="18" ry="13" fill="#ec826d"/><g fill="#fff9e8" stroke="#304f59" stroke-width="4"><ellipse cx="150" cy="141" rx="18" ry="24"/><ellipse cx="210" cy="141" rx="18" ry="24"/></g><g fill="#304f59"><circle cx="155" cy="147" r="7"/><circle cx="205" cy="147" r="7"/></g><g id="mb-part-0"><rect x="40" y="139" width="66" height="88" rx="28" fill="#88cce2" stroke="#304f59" stroke-width="5"/><path d="M54 182h36" stroke="#eafcff" stroke-width="6"/></g><g id="mb-part-1"><path d="M116 106q-5-65 64-67 69 2 64 67Z" fill="#88cce2" stroke="#304f59" stroke-width="5"/><path d="M180 40V21" stroke="#304f59" stroke-width="5"/><circle cx="180" cy="18" r="9" fill="#f07e69" stroke="#304f59" stroke-width="4"/></g><g id="mb-part-2"><rect x="254" y="139" width="66" height="88" rx="28" fill="#88cce2" stroke="#304f59" stroke-width="5"/><path d="M271 182h36" stroke="#eafcff" stroke-width="6"/></g><g fill="#304f59" font-size="13" font-weight="bold" text-anchor="middle"><text x="73" y="247">左臂</text><text x="180" y="80">头顶</text><text x="287" y="247">右臂</text></g></g><g id="mb-fx"></g></svg><div id="mb-cue" aria-live="polite"></div></div><div class="mb-meter"><i id="mb-meter"></i></div><section class="mb-instruction"><h2 id="mb-title"></h2><p id="mb-duty"></p></section><p id="msg" role="status"></p><footer id="mb-controls"></footer></section>';
 $('back').onclick=function(){if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 var conn=PEER.conn;function disconnected(){clean();window._dead=true;if($('msg'))$('msg').textContent='连接断开，战斗停止。请返回重新建房。';document.querySelectorAll('#mb-controls button').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnected);function kb(e){if(e.repeat||!['1','2','3'].includes(e.key))return;var btn=document.querySelector('[data-mb="'+(+e.key-1)+'"]');if(btn&&!btn.disabled){e.preventDefault();btn.click();}}window.addEventListener('keydown',kb);dispose=function(){window.removeEventListener('keydown',kb);if(conn&&conn.off)conn.off('close',disconnected);};
}
function draw(s,who){if(!$('mb-boss'))return;view=s;$('mb-hp').textContent='护盾 '+s.hp+' / 5';$('mb-armor').textContent='已拆 '+(6-s.armor.reduce(function(a,b){return a+b;},0))+' / 6';$('msg').textContent=s.msg;
 var waiting=s.phase==='ready',att=s.phase==='attack',def=s.phase==='defense',turn=att&&who==='A'||def&&who==='B';$('mb-title').textContent=s.done?(s.win?'拆机成功！':'再配合一次'):waiting?'先确认分工':att?'B 报弱点 · A 攻击':def?'A 报方向 · B 举盾':'漂亮，再接下一招';$('mb-duty').textContent=waiting?(who==='A'?'听 B 报弱点，点对应部位；怪物发射时，你看箭头报方向。':'观察闪亮装甲，向 A 报部位；听 A 报来袭方向，点对应护盾。'):att?(who==='B'?'弱点是「'+parts[s.weak]+'」，告诉 A！':'听 B 报部位，点击下面的攻击按钮。'):def?(who==='A'?'泡泡弹从「'+directions[s.dir]+'」来，告诉 B！':'听 A 报来袭方向，选择对应护盾。'):s.done?'双方默契才是最强武器。':'观察装甲变化，准备下一次配合。';
 $('mb-cue').textContent=waiting?(s.ready.A&&s.ready.B?Math.ceil(s.left):'双方准备后开战'):s.done?(s.win?'✓':'再试一次'):att&&who==='B'?'弱点：'+parts[s.weak]:def&&who==='A'?'来袭：'+directions[s.dir]:s.phase==='impact'?(s.effect==='block'?'挡住！':s.effect==='hit'?'命中！':'哎呀！'):Math.ceil(s.left)+' 秒';$('mb-meter').style.width=(waiting?s.left/3:att?s.left/8:def?s.left/5:0)*100+'%';
 var arena=document.querySelector('.mb-arena');arena.className='mb-arena '+(def?'charging ':'')+(s.done&&s.win?'victory ':'')+(s.phase==='impact'?s.effect:'');s.armor.forEach(function(n,i){var g=$('mb-part-'+i);g.classList.toggle('broken',n===0);g.classList.toggle('cracked',n===1);g.classList.toggle('weak',att&&who==='B'&&s.weak===i);});
 var fx=$('mb-fx');if(def&&who==='A'){var p=[[22,146],[180,18],[338,146]][s.dir];fx.innerHTML='<circle cx="'+p[0]+'" cy="'+p[1]+'" r="17" fill="#ef826d" stroke="#304f59" stroke-width="3"/><text x="'+p[0]+'" y="'+(p[1]+6)+'" text-anchor="middle" fill="white" font-size="21">'+['→','↓','←'][s.dir]+'</text>';}else if(s.phase==='impact')fx.innerHTML=s.effect==='block'?'<path d="M138 209q42 12 84 0v33q-7 32-42 40-35-8-42-40Z" fill="#90dce2" stroke="#304f59" stroke-width="5"/>':s.effect==='hit'?'<text x="180" y="208" text-anchor="middle" font-size="60" fill="#fff8cc" stroke="#b87835" stroke-width="2">✦</text>':'';else fx.innerHTML='';
 if(arena.dataset.event!==String(s.event)){arena.dataset.event=s.event;arena.classList.remove('hit','block','miss');void arena.offsetWidth;if(s.event)arena.classList.add(s.effect);}
 var k=s.id+':'+s.round+':'+s.phase;if(key!==k){key=k;var controls=$('mb-controls');if(waiting){controls.innerHTML='<button id="mb-ready">读懂了 · 准备开战</button>'; $('mb-ready').onclick=function(){act('mbReady');};}else if(s.done){controls.innerHTML=window._dungeon?'<span>即将返回地图</span>':'<button id="mb-again">再来一局</button><span>双方点击后重开</span>';if($('mb-again'))$('mb-again').onclick=function(){act('mbAgain');this.disabled=true;this.textContent='等待同伴';};}else if(turn){controls.innerHTML='<div class="mb-buttons">'+(att?parts:directions).map(function(n,i){return '<button data-mb="'+i+'">'+(att?'打':'挡')+'<strong>'+n+'</strong></button>';}).join('')+'</div>';controls.querySelectorAll('button').forEach(function(b){b.onclick=function(){act('mbAct',+b.dataset.mb);controls.querySelectorAll('button').forEach(function(x){x.disabled=true;});};});}else controls.innerHTML='<div class="mb-call">'+(att?'告诉 A 弱点部位':def?'告诉 B 来袭方向':'稍等，下一招来了')+'</div>';}
 if($('mb-ready')){$('mb-ready').disabled=s.ready[who];$('mb-ready').textContent=s.ready[who]?'已准备 · 等待同伴':'读懂了 · 准备开战';}document.querySelectorAll('[data-mb]').forEach(function(b){if(att&&s.armor[+b.dataset.mb]===0)b.disabled=true;});
}
function host(){clearTimers();clean();S.mod='boss';window._dead=false;shell('A');var s=make();active=s;var last=performance.now(),endAt=0;function tick(){if(active!==s)return;var now=performance.now();step(s,(now-last)/1000);last=now;draw(snap(s,'A'),'A');netSend({t:'mbState',state:snap(s,'B')});if(s.done){window._dead=true;if(!endAt)endAt=now+1800;if(window._dungeon&&now>=endAt){var win=s.win;clearTimers();if(win)dgBossWin();else dungeonEnd(false);}else if(!window._dungeon&&s.againA&&s.againB)host();}}tick();timers.push(setInterval(tick,60));}
function guest(){var dungeon=window._dungeon;clearTimers();clean();S.mod='boss';window._dead=false;shell('B');if(!dungeon&&PEER.conn&&!PEER.conn._bossMobileListener){PEER.conn._bossMobileListener=function(d){dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._bossMobileListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};var os=startRealtime;startRealtime=function(mode){if(mode==='boss')return host();return os.apply(this,arguments);};var og=renderRealtimeGuest;renderRealtimeGuest=function(mode){if(mode==='boss')return guest();return og.apply(this,arguments);};var hd=dgHostOnData;dgHostOnData=function(d){if(/^mb(Ready|Act|Again)$/.test(d.t)){input(active,d,'B');return;}return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(d.t==='mbState'){if(S.mod!=='boss'||!$('mb-boss'))return;if(view&&view.id!==d.state.id)guest();draw(d.state,'B');return;}return gd(d);};window.BossMobile={create:make,input:input,step:step,snapshot:snap,state:function(){return active||view;}};
})();
