(function(){
'use strict';
var observer=null;
function mountain(){return !!(window._dungeon&&typeof DUNGEON!=='undefined'&&DUNGEON&&DUNGEON.roomId==='room-16');}
var symbols=['○','△','□','⊕','◇','☆'];
function marker(ctx,x,y,cell,text,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x+cell/2,y+cell/2,cell*.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffffff';ctx.font='700 '+Math.floor(cell*.6)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x+cell/2,y+cell/2+1);}
function terrain(ctx,cell,pos){ctx.clearRect(0,0,ctx.canvas.width,ctx.canvas.height);for(var r=0;r<MAZE.rows;r++)for(var c=0;c<MAZE.cols;c++){var visible=!pos||Math.abs(r-pos[0])+Math.abs(c-pos[1])<=1;ctx.fillStyle=!visible?'#14233c':MAZE.walls[r][c]==='1'?'#415773':'#e4eef7';ctx.fillRect(c*cell,r*cell,cell,cell);if(mountain()&&visible&&MAZE.walls[r][c]==='1'){ctx.fillStyle='#6c8794';ctx.beginPath();ctx.moveTo((c+.12)*cell,(r+.84)*cell);ctx.lineTo((c+.5)*cell,(r+.18)*cell);ctx.lineTo((c+.88)*cell,(r+.84)*cell);ctx.closePath();ctx.fill();}ctx.strokeStyle=visible?'#71869f':'#1c2e49';ctx.lineWidth=.6;ctx.strokeRect(c*cell+.5,r*cell+.5,cell-1,cell-1);}}
window.mazeDrawLocal=function(ctx,cell,pos,gates){terrain(ctx,cell,pos);gates.forEach(function(g){if(Math.abs(g.r-pos[0])+Math.abs(g.c-pos[1])<=1)marker(ctx,g.c*cell,g.r*cell,cell,g.open?'✓':symbols[g.symbol],g.open?'#12786e':'#5067ba');});marker(ctx,pos[1]*cell,pos[0]*cell,cell,'A','#2461dc');var progress=document.getElementById('mz-progress');if(progress)progress.textContent=(mountain()?'路标 ':'阀门 ')+gates.filter(function(g){return g.open;}).length+' / 3';};
drawMazeFull=function(ctx,cell){terrain(ctx,cell,null);[.25,.5,.75].forEach(function(f,i){var p=MAZE.path[0][Math.floor((MAZE.path[0].length-1)*f)].split(',').map(Number);marker(ctx,p[1]*cell,p[0]*cell,cell,String(i+1),'#5067ba');});var a=MAZE.start,e=MAZE.end;marker(ctx,a[1]*cell,a[0]*cell,cell,'S','#2461dc');marker(ctx,e[1]*cell,e[0]*cell,cell,'E','#12786e');MAZE.traps.forEach(function(t){var x=(t[1]+.5)*cell,y=(t[0]+.5)*cell;ctx.fillStyle='#c33e59';ctx.beginPath();ctx.moveTo(x,y-cell*.3);ctx.lineTo(x+cell*.3,y);ctx.lineTo(x,y+cell*.3);ctx.lineTo(x-cell*.3,y);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.font='bold '+Math.floor(cell*.45)+'px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('!',x,y);});};
function polish(manual){
 if(observer){observer.disconnect();observer=null;}
 var app=$('app');app.classList.add('maze-mobile');app.dataset.mazeTheme=mountain()?'mountain':'';app.dataset.mazeRole=manual?'B':'A';
 var top=app.querySelector('.topbar'),back=$('back'),count=$('count'),again=$('again');
 if(top){top.replaceChildren();back.textContent='‹';back.setAttribute('aria-label',window._dungeon?'返回地图':'返回玩法');top.appendChild(back);var title=document.createElement('strong');title.textContent=mountain()?'山径岔路':'通风潜行';top.appendChild(title);var role=document.createElement('span');role.className='mz-role';role.textContent=manual?'B · 指挥员':'A · 潜行者';top.appendChild(role);}
 var meta=document.createElement('div');meta.className='mz-meta';meta.innerHTML=manual?'<span>全图 · 只负责指挥</span>':'<strong>图 '+(window._mazeSeed+1)+'</strong><span id="mz-progress">阀门 0 / 3</span>';if(count){meta.appendChild(count);count.setAttribute('aria-label','剩余时间');}top.after(meta);
 var card=app.querySelector(manual?'.manual-card':'#playarea');card.classList.add('mz-main');
 var oldTitle=card.querySelector('h3');if(oldTitle)oldTitle.remove();var tip=card.querySelector(manual?'.mc':'.taskline');if(tip)tip.remove();
 var intro=document.createElement('div');intro.className='mz-intro';intro.innerHTML='<h2>'+(manual?'看地图，给 A 指路':'听 B 指路，找到阀门')+'</h2><p>'+(manual?'先经过 1 / 2 / 3，再到 E 出口。':'先告诉 B 图号，再按方向移动。')+'</p>';card.prepend(intro);
 var help=document.createElement('details');help.className='mz-help';help.innerHTML='<summary>玩法说明</summary><p>'+(manual?'先按 A 报的图号切图。红色菱形是陷阱；A 只能看周围五格。到阀门前，听 A 报符号，再查下方对照。':'你只能看上下左右五格。遇到阀门，向 B 报现场符号；听他选阀门。碰墙 −5 秒、陷阱 −8 秒、阀门选错 −4 秒。')+'</p>';intro.after(help);
 var stage=card.querySelector('.stage');stage.setAttribute('aria-label',manual?'路线地图':'局部视野');var caption=document.createElement('div');caption.className='mz-map-caption';caption.textContent=manual?'S 起点 · E 出口 · ◆ 陷阱 · 1/2/3 阀门':'A 是你 · 深色区域尚不可见';stage.after(caption);
 var dp=$('dpad');if(dp){var names={up:'↑ 上',l:'← 左',d:'↓ 下',r:'右 →'};dp.querySelectorAll('button').forEach(function(b){b.textContent=names[b.dataset.d];b.setAttribute('aria-label',names[b.dataset.d]);});var label=document.createElement('p');label.className='mz-control-hint';label.textContent='点一次，移动一格';dp.before(label);}
 if(manual){var table=document.createElement('section');table.id='maze-valve-table';table.className='maze-valve-table';table.innerHTML='<h3>听符号，报阀门</h3><div class="mz-valve-grid"><div class="blue"><strong>○　◇</strong><span>蓝阀</span></div><div class="orange"><strong>△　☆</strong><span>橙阀</span></div><div class="green"><strong>□　⊕</strong><span>绿阀</span></div></div>';card.appendChild(table);app.querySelectorAll('.mz-tab').forEach(function(b){b.setAttribute('aria-pressed',b.classList.contains('on')?'true':'false');var old=b.onclick;b.onclick=function(){old.call(b);app.querySelectorAll('.mz-tab').forEach(function(x){x.setAttribute('aria-pressed',x.classList.contains('on')?'true':'false');});};});}
 if(again){again.classList.add('mz-again');again.textContent='重新开始';app.appendChild(again);}
 if(mountain()){if($('mz-progress'))$('mz-progress').textContent='路标 0 / 3';intro.querySelector('h2').textContent=manual?'看山径图，给 A 指路':'听 B 指路，穿过山径';intro.querySelector('p').textContent=manual?'经过 1 / 2 / 3 路标，再到 E 山口。':'先报地图编号，再按方向迈步。';help.querySelector('p').textContent=manual?'按 A 报的图号切换山径。红色菱形是险坡；A 只能看周围五格。到路标前，听 A 报符号，再查下方颜色对照。':'雾中只能看周围五格。遇到路标先报符号，由 B 查表告诉你颜色。撞山壁 −5 秒，险坡 −8 秒，选错 −4 秒。';caption.textContent=manual?'S 营地 · E 山口 · ◆ 险坡 · 1/2/3 路标':'A 是你 · 山峰不可通行 · 深色是迷雾';if(manual){table.querySelector('h3').textContent='听路标符号，报颜色';table.querySelectorAll('.mz-valve-grid span').forEach(function(el,i){el.textContent=['蓝路标','橙路标','绿路标'][i];});}else{var gateBox=$('maze-valve');if(gateBox){gateBox.querySelectorAll('button').forEach(function(el,i){el.textContent=['蓝路标','橙路标','绿路标'][i];});var gateHint=gateBox.querySelector('p');if(gateHint)gateHint.textContent='向 B 报符号，听他选择路标颜色。';}}}
 // The dungeon shell has a duplicate msg placeholder; retain only the actual game message.
 var messages=app.querySelectorAll('#msg');for(var i=1;i<messages.length;i++)messages[i].remove();
 observer=new MutationObserver(function(){if(S.mod!=='maze'||!app.querySelector('.mz-main')){app.classList.remove('maze-mobile');delete app.dataset.mazeRole;delete app.dataset.mazeTheme;observer.disconnect();observer=null;return;}var gate=$('maze-valve');if(gate){intro.querySelector('h2').textContent=gate.hidden?'听 B 指路，找到阀门':'报符号，按 B 说的选';intro.querySelector('p').textContent=gate.hidden?'先告诉 B 图号，再按方向移动。':'只有 B 的对照表能判断正确阀门。';if(mountain()){var clue=$('maze-valve-clue');if(clue)clue.textContent=clue.textContent.replace(/阀门/g,'路标');intro.querySelector('h2').textContent=gate.hidden?'听 B 指路，穿过山径':'报路标符号，按 B 说的选';intro.querySelector('p').textContent=gate.hidden?'先报地图编号，再按方向迈步。':'由 B 查对照表，告诉你正确颜色。';}}});observer.observe(app,{childList:true});var gate=$('maze-valve');if(gate)observer.observe(gate,{attributes:true,attributeFilter:['hidden']});
}
var run=runMaze;runMaze=function(set){run(set);polish(false);};
var manual=renderManual;renderManual=function(){var result=manual.apply(this,arguments);if(S.mod==='maze')polish(true);return result;};
})();
