/* Password strips: independent, untimed, private-view cooperative prototype. */
(function(){
'use strict';
var MODE='pwslide',PROTO='password-strip/1',session=null,view=null,selected=0,drawKey='',swipe=null;
function other(w){return w==='A'?'B':'A';}
function copy(x){return JSON.parse(JSON.stringify(x));}
function uid(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}
function strip(axis,n){return {axis:axis,pos:Math.random()<.5?0:8,target:2+Math.floor(Math.random()*5),digits:Array.from({length:n},function(){return Math.floor(Math.random()*10);})};}
function setup(s){s.bands={A:[strip('x',s.round===0?4:2)],B:[strip('x',s.round===0?4:2)]};if(s.round===1){s.bands.A.push(strip('y',2));s.bands.B.push(strip('y',2));}s.locked={A:false,B:false};s.ready={A:false,B:false};}
function create(ctx){var start=ctx&&!ctx.tutorial?1:0;var s={startRound:start,endRound:ctx?start:1,id:uid(),round:start,phase:'ready',seq:{A:0,B:0},again:{A:false,B:false},notice:{A:'',B:''}};setup(s);return s;}
function aligned(bands){return bands.every(function(b){return b.pos===b.target;});}
function input(s,d,w){
 if(!s||!['A','B'].includes(w)||!d||d.id!==s.id||d.round!==s.round||!Number.isSafeInteger(d.seq)||d.seq<=s.seq[w])return false;
 if(!['ready','move','confirm','again'].includes(d.kind))return false;
 if(d.kind==='move'&&(!Number.isInteger(d.index)||!s.bands[w][d.index]||![-1,1].includes(d.delta)))return false;
 s.seq[w]=d.seq;
 if(d.kind==='ready'&&(s.phase==='ready'||s.phase==='between')){s.ready[w]=true;if(s.ready.A&&s.ready.B){if(s.phase==='between'){s.round++;setup(s);}s.phase='play';s.notice={A:'',B:''};}return true;}
 if(d.kind==='again'&&s.phase==='done'){s.again[w]=true;return true;}
 if(s.phase!=='play')return false;
 if(d.kind==='move'&&!s.locked[w]){var b=s.bands[w][d.index];b.pos=Math.max(0,Math.min(8,b.pos+d.delta));return true;}
 if(d.kind==='confirm'){var p=other(w);if(!aligned(s.bands[p])){s.notice[w]='还没完整露出，请继续指挥同伴对齐窗口。';return false;}s.locked[p]=true;s.notice[w]='同伴的密码已确认。';if(s.locked.A&&s.locked.B){s.phase=s.round<s.endRound?'between':'done';s.ready={A:false,B:false};}return true;}return false;
}
function snapshot(s,w){var p=other(w);return {startRound:s.startRound,endRound:s.endRound,id:s.id,round:s.round,phase:s.phase,ready:copy(s.ready),again:copy(s.again),locked:copy(s.locked),notice:s.notice[w],own:s.bands[w].map(function(b){return {axis:b.axis,pos:b.pos,min:0,max:8};}),observed:copy(s.bands[p])};}
function stop(){var q=session;session=null;view=null;drawKey='';swipe=null;if(q){q.stopped=true;clearInterval(q.timer);clearTimeout(q.timeout);clearTimeout(q.finishTimer);q.clean.forEach(function(fn){fn();});}}
function packet(d){var q=session;if(q&&q.conn&&q.conn.open)q.conn.send(d);}
function fail(text){var q=session;if(!q||q.failed)return;q.failed=true;clearInterval(q.timer);clearTimeout(q.timeout);swipe=null;var el=document.getElementById('ps-status');if(el)el.textContent=text;document.querySelectorAll('.ps-shell button:not(#ps-back)').forEach(function(b){b.disabled=true;});}
function emit(kind,extra){var q=session;if(!q||q.failed||!view||(q.ctx&&!q.ctx.isActive()))return;var d=Object.assign({t:q.ctx?'psRoomInput':'psInput',roomSession:q.ctx?q.ctx.sessionId:null,id:view.id,round:view.round,seq:++q.seq,kind:kind},extra||{});if(q.role==='A'){input(q.state,d,'A');publish();}else packet(d);}
function publish(){var q=session;if(!q||q.failed||!q.state||(q.ctx&&!q.ctx.isActive()))return;if(!q.ctx&&q.state.phase==='done'&&q.state.again.A&&q.state.again.B){q.state=create();q.seq=0;selected=0;}view=snapshot(q.state,'A');draw();packet({t:q.ctx?'psRoomState':'psState',roomSession:q.ctx?q.ctx.sessionId:null,match:q.match,frame:++q.frame,state:snapshot(q.state,'B')});if(q.ctx&&q.state.phase==='done'&&!q.settled){q.settled=true;var captured=q.ctx;q.finishTimer=setTimeout(function(){if(session===q&&!q.failed&&captured.isActive())captured.finish(true);},700);}}
function btn(id,label,disabled){return '<button id="'+id+'"'+(disabled?' disabled':'')+'>'+label+'</button>';}
function exitTheme(){return !!(session&&session.ctx&&session.ctx.roomId==='room-13');}
function roundLabel(s){return (s.round-s.startRound+1)+' / '+(s.endRound-s.startRound+1);}
function icon(){if(exitTheme())return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 58V6h40v52" fill="#e7d9bd" stroke="currentColor" stroke-width="3"/><rect x="21" y="18" width="23" height="15" rx="3" fill="#fff7df" stroke="currentColor" stroke-width="2"/><path d="M28 19v13m8-13v13M41 44h6" stroke="currentColor" stroke-width="2"/></svg>';return '<svg viewBox="0 0 64 48" aria-hidden="true"><rect x="12" y="8" width="40" height="32" rx="6" fill="#fff4d6" stroke="currentColor" stroke-width="2"/><path d="M20 18h24v12H20zM3 24h12m-8-5-5 5 5 5m54-5H49m8-5 5 5-5 5" fill="none" stroke="currentColor" stroke-width="2"/><path d="M28 18v12m8-12v12" stroke="currentColor" stroke-width="2"/></svg>';}
function scaffold(role){var app=document.getElementById('app');app.innerHTML='<main class="ps-shell"><header class="ps-header">'+btn('ps-back','‹')+'<h1>密码推条</h1><span class="ps-role">'+(role?'角色 '+role:'双人解谜')+'</span></header><div id="ps-body"></div><p id="ps-status" class="ps-status" role="status" aria-live="polite"></p></main>';document.getElementById('ps-back').setAttribute('aria-label','退出密码推条');document.getElementById('ps-back').onclick=function(){clearTimers();closePeer();location.search='';};}
function observedSVG(b,i){var horiz=b.axis==='x',n=b.digits.length,base=n===4?260:150,w=horiz?n*44:54,h=horiz?52:n*40,x=(base-w)/2,y=24,distance=b.pos-b.target,shift=distance===0?0:Math.sign(distance)*(24+(Math.abs(distance)-1)*(horiz?7:4)),dx=horiz?shift:0,dy=horiz?0:shift,id='ps-clip-'+i;
 var digits=b.digits.map(function(d,j){return '<text x="'+(horiz?x+22+j*44:x+w/2)+'" y="'+(horiz?y+35:y+31+j*40)+'" text-anchor="middle">'+d+'</text>';}).join('');
 return '<svg class="ps-window" viewBox="0 0 '+base+' '+(h+48)+'" role="img" aria-label="同伴的'+(horiz?'横':'竖')+'向密码条，观察窗口边缘是否完整"><defs><clipPath id="'+id+'"><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="3"/></clipPath></defs><rect x="'+(x-14)+'" y="'+(y-12)+'" width="'+(w+28)+'" height="'+(h+24)+'" rx="10" fill="#dcd5ed"/><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="#534767"/><g clip-path="url(#'+id+')"><g class="ps-band" style="transform:translate('+dx+'px,'+dy+'px)"><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" fill="#fff6dc"/>'+digits+'<rect x="'+(x+2)+'" y="'+(y+2)+'" width="'+(w-4)+'" height="'+(h-4)+'" rx="2" fill="none" stroke="#b79557" stroke-width="2"/></g></g><rect x="'+x+'" y="'+y+'" width="'+w+'" height="'+h+'" rx="3" fill="none" stroke="#423652" stroke-width="2"/><path d="M'+(x-6)+' '+(y-5)+'h12m'+(w-12)+' 0h12M'+(x-6)+' '+(y+h+5)+'h12m'+(w-12)+' 0h12" stroke="#b36e40" stroke-width="3"/></svg>';
}
function rail(b){return '<div class="ps-touch" data-axis="'+b.axis+'" aria-label="自己的条带背面，滑动一格"><div class="ps-rail">'+Array.from({length:9},function(_,i){return '<span class="ps-notch'+(i===b.pos?' ps-current':'')+'">'+(i===b.pos?'◆':'·')+'</span>';}).join('')+'</div><small>'+(b.axis==='x'?'左右':'上下')+'滑动此处，每次一格 · 档位 '+(b.pos+1)+' / 9</small></div>';}
function draw(){var q=session;if(!q||q.failed||!view)return;var s=view,w=q.role,p=other(w),key=JSON.stringify(s)+':'+selected;if(key===drawKey)return;drawKey=key;var body=document.getElementById('ps-body');if(!body)return;var previous=body.dataset.psRound===s.id+':'+s.round?Array.from(body.querySelectorAll('.ps-band')).map(function(g){return g.style.transform;}):[];body.dataset.psRound=s.id+':'+s.round;
 if(s.phase!=='play'){
  var title=s.phase==='ready'?'你来指挥，我来推':s.phase==='between'?'横向对齐完成':(q.ctx?'出口锁已解除':'两组密码都找到了');
  var detail=s.phase==='ready'?'你只能看见 '+p+' 的密码条。告诉同伴往哪推；听同伴指挥，移动自己的条带。':s.phase==='between'?'下一轮有两条：横条是前两位，竖条是后两位。先选条带，再按方向推。':'两个人都完成了观察、指挥和对位。';
  body.innerHTML='<section class="ps-paper ps-intro">'+icon()+'<p class="ps-eyebrow">'+(s.phase==='done'?'合作完成':'第 '+(s.phase==='between'?'2 / 2':roundLabel(s))+' 轮 · 不限时')+'</p><h2>'+title+'</h2><p>'+detail+'</p>'+(s.phase==='done'?'':'<ol><li>看上方窗口，指挥同伴往哪移。</li><li>操作下方控制器，推自己的条带。</li><li>同伴四位数字完整露出后，由你确认。</li></ol>')+btn(s.phase==='done'?'ps-again':'ps-ready',s.phase==='done'?(s.again[w]?'等待同伴重开':'再来一局'):(s.ready[w]?'等待同伴准备':s.phase==='between'?'准备好 · 挑战横竖条':'读懂了 · 准备'),s.phase==='done'?s.again[w]:s.ready[w])+'<small>需要双方确认 · 不会自动开始</small></section>';
  if(q.ctx&&s.phase==='done'){document.getElementById('ps-again').remove();body.querySelector('small').textContent='机关已解除，正在返回地图…';}var b=document.getElementById(s.phase==='done'?'ps-again':'ps-ready');if(b)b.onclick=function(){emit(s.phase==='done'?'again':'ready');};
 }else{
  if(selected>=s.own.length)selected=0;var own=s.own[selected],can=aligned(s.observed),seen=s.locked[p];
  body.innerHTML='<div class="ps-meta"><span>第 '+roundLabel(s)+' 轮</span><span>不限时 · 配合对位</span></div><section class="ps-paper ps-observe"><p class="ps-eyebrow">你负责观察</p><h2>'+p+' 的密码窗口</h2><p class="ps-hint">'+(s.round?'先横条、后竖条；竖条从上往下读。':'告诉 '+p+' 往左或往右推，让纸条四边贴齐窗口。')+'</p><div class="ps-windows">'+s.observed.map(function(b,i){return '<div><span class="ps-strip-label">'+(s.round?(i?'② 竖条 · 后两位':'① 横条 · 前两位'):'横向密码条')+'</span>'+observedSVG(b,i)+'</div>';}).join('')+'</div>'+btn('ps-confirm',seen?'✓ 已确认同伴密码':can?'四位完整 · 确认同伴密码':'尚未对齐 · 继续指挥',seen||!can)+'</section><section class="ps-paper ps-control"><p class="ps-eyebrow">你负责操作 · 同伴看正面</p><h2>自己的条带背面</h2><div class="ps-select">'+s.own.map(function(b,i){return '<button data-ps-select="'+i+'" aria-pressed="'+(selected===i)+'"'+(s.locked[w]?' disabled':'')+'>'+ (i?'② 竖向条':'① 横向条')+'</button>';}).join('')+'</div>'+rail(own)+'<div class="ps-directions">'+btn('ps-minus',own.axis==='x'?'← 向左推一格':'↑ 向上推一格',s.locked[w]||own.pos===0)+btn('ps-plus',own.axis==='x'?'向右推一格 →':'向下推一格 ↓',s.locked[w]||own.pos===8)+'</div><p class="ps-hint">'+(s.locked[w]?'✓ 同伴已确认你的密码，条带已锁定。':'听 '+p+' 指挥再移动。你这里不显示自己的数字。')+'</p></section>';
  document.getElementById('ps-confirm').onclick=function(){emit('confirm');};document.getElementById('ps-minus').onclick=function(){emit('move',{index:selected,delta:-1});};document.getElementById('ps-plus').onclick=function(){emit('move',{index:selected,delta:1});};body.querySelectorAll('[data-ps-select]').forEach(function(b){b.onclick=function(){selected=Number(b.dataset.psSelect);draw();};});
 }
 if(exitTheme())body.insertAdjacentHTML('afterbegin','<div class="ps-door-status"><b>出口联锁</b><span>A '+(s.locked.A?'已解除':'待对位')+' · B '+(s.locked.B?'已解除':'待对位')+'</span></div>');
 if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)body.querySelectorAll('.ps-band').forEach(function(g,i){if(previous[i]&&previous[i]!==g.style.transform)g.animate([{transform:previous[i]},{transform:g.style.transform}],{duration:140,easing:'ease-out'});});
 document.getElementById('ps-status').textContent=s.notice|| (s.phase==='play'?'观察同伴 → 口头指挥 → 操作自己':s.phase==='done'?'双方点击后重新生成密码。':'和同伴读完分工后，再一起开始。');
}
function controls(q){var root=document.querySelector('.ps-shell');function down(e){if(!e.target.closest('.ps-touch')||!view||view.phase!=='play'||view.locked[q.role]||q.failed)return;swipe={x:e.clientX,y:e.clientY,axis:view.own[selected].axis,index:selected,id:view.id,round:view.round,pointer:e.pointerId};root.setPointerCapture(e.pointerId);}
 function up(e){var a=swipe;swipe=null;if(!a||a.pointer!==e.pointerId||!view||a.id!==view.id||a.round!==view.round)return;var delta=a.axis==='x'?e.clientX-a.x:e.clientY-a.y;if(Math.abs(delta)>=24)emit('move',{index:a.index,delta:delta>0?1:-1});}
 function cancel(){swipe=null;}function keyboard(e){if(!view||view.phase!=='play'||q.failed||e.repeat||/INPUT|TEXTAREA/.test(e.target.tagName))return;var axis=view.own[selected].axis,d=axis==='x'?{ArrowLeft:-1,ArrowRight:1}:{ArrowUp:-1,ArrowDown:1};if(d[e.key]){e.preventDefault();emit('move',{index:selected,delta:d[e.key]});}}
 root.addEventListener('pointerdown',down);root.addEventListener('pointerup',up);root.addEventListener('pointercancel',cancel);window.addEventListener('blur',cancel);window.addEventListener('keydown',keyboard);q.clean.push(function(){root.removeEventListener('pointerdown',down);root.removeEventListener('pointerup',up);root.removeEventListener('pointercancel',cancel);window.removeEventListener('blur',cancel);window.removeEventListener('keydown',keyboard);});}
function lobby(w){clearTimers();closePeer();clearNetZones();S.mod=MODE;S.role=w;window._dungeon=false;window._netMode=w==='A'?'host':'guest';selected=0;drawKey='';scaffold(w);
 var q={role:w,seq:0,frame:0,lastFrame:0,match:null,state:null,conn:null,clean:[],failed:false,accepted:false,stopped:false,lastSeen:Date.now()};session=q;
 document.getElementById('ps-body').innerHTML='<section class="ps-paper ps-intro">'+icon()+'<h2>'+(w==='A'?'创建密码推条房间':'加入密码推条房间')+'</h2><p>你看同伴的密码条，控制自己的条带。<br>连接后双方准备，再开始解谜。</p>'+(w==='A'?'<div id="ps-code" class="ps-code">····</div>':'<label for="ps-room">同伴的四位房间码</label><input id="ps-room" inputmode="numeric" maxlength="4" autocomplete="off" placeholder="例如 1234">'+btn('ps-join','加入房间'))+'</section>';
 function status(t){if(session===q&&!q.failed)document.getElementById('ps-status').textContent=t;}
 function connect(code){status('正在连接…');loadPeerLib(function(P){if(session!==q)return;if(!P){fail('联网组件加载失败，请返回重试。');return;}var p=newPeerId(w==='A'?'pwstrip-'+code:null,peerOpts());PEER.peer=p;PEER.room=code;PEER.isHost=w==='A';q.timeout=setTimeout(function(){fail('连接超时，请确认双方选择密码推条，再返回重试。');p.destroy();},15000);
 p.on('error',function(e){if(session!==q)return;fail(e.type==='unavailable-id'?'房间码已占用，请返回重新创建。':'无法连接房间，请确认房间码和玩法后返回重试。');});
 function attach(c){if(session!==q||q.conn){c.close();return;}q.conn=c;PEER.conn=c;
 c.on('data',function(d){if(session!==q||q.failed||!d)return;q.lastSeen=Date.now();
  if(!q.accepted){if(w==='A'&&d.t==='psHello'&&d.mode===MODE&&d.proto===PROTO){q.accepted=true;q.match=uid();q.state=create();clearTimeout(q.timeout);packet({t:'psWelcome',mode:MODE,proto:PROTO,match:q.match});controls(q);publish();}else if(w==='B'&&d.t==='psWelcome'&&d.mode===MODE&&d.proto===PROTO&&typeof d.match==='string'){q.accepted=true;q.match=d.match;clearTimeout(q.timeout);controls(q);}else{packet({t:'psReject'});fail('房间玩法或协议不匹配，请返回重新选择。');c.close();}return;}
  if(w==='A'&&d.t==='psInput'){input(q.state,d,'B');publish();}
  else if(w==='B'&&d.t==='psState'&&d.match===q.match&&Number.isSafeInteger(d.frame)&&d.frame>q.lastFrame){q.lastFrame=d.frame;if(view&&view.id!==d.state.id){q.seq=0;selected=0;}view=d.state;draw();}
 });
 c.on('close',function(){if(session===q)fail('同伴断线，操作已停止。请返回重新建房。');});c.on('error',function(){if(session===q)fail('连接中断，操作已停止。请返回重新建房。');});
 c.on('open',function(){if(session!==q||q.failed)return;q.lastSeen=Date.now();if(w==='B')packet({t:'psHello',mode:MODE,proto:PROTO});});
 }
 p.on('open',function(){if(session!==q)return;if(w==='A'){clearTimeout(q.timeout);document.getElementById('ps-code').textContent=code;status('把房间码告诉同伴，等待加入。');}else attach(p.connect('pwstrip-'+code,{reliable:true,metadata:{mode:MODE,proto:PROTO}}));});
 if(w==='A')p.on('connection',function(c){if(q.conn||session!==q){c.close();return;}if(!c.metadata||c.metadata.mode!==MODE||c.metadata.proto!==PROTO){c.on('open',function(){c.send({t:'psReject'});setTimeout(function(){c.close();},100);});return;}attach(c);q.timeout=setTimeout(function(){if(!q.accepted){fail('房间握手超时，请返回重试。');c.close();}},8000);});
 q.timer=setInterval(function(){if(session!==q||q.failed||!q.accepted)return;if(Date.now()-q.lastSeen>7000){fail('同伴连接无响应，操作已停止。请返回重新建房。');return;}if(w==='A')publish();else packet({t:'psPulse',match:q.match});},250);
 });}
 if(w==='A')connect(String(1000+Math.floor(Math.random()*9000)));else document.getElementById('ps-join').onclick=function(){var code=document.getElementById('ps-room').value.trim();if(!/^\d{4}$/.test(code)){status('请输入四位数字房间码。');return;}this.disabled=true;connect(code);};
}
function choose(){clearTimers();closePeer();scaffold();document.getElementById('ps-body').innerHTML='<section class="ps-paper ps-intro">'+icon()+'<h2>看同伴的密码，听同伴的指挥</h2><p>两个人交换视野，把彼此的密码条推到窗口正中。不限时，共两轮。</p>'+btn('ps-host','角色 A · 创建房间')+btn('ps-guest','角色 B · 加入房间')+'</section>';document.getElementById('ps-host').onclick=function(){lobby('A');};document.getElementById('ps-guest').onclick=function(){lobby('B');};}
function enterRoom(ctx,w){clearTimers();clearNetZones();S.mod=MODE;selected=0;drawKey='';var q={role:w,ctx:ctx,seq:0,frame:0,lastFrame:0,match:ctx.sessionId,state:null,conn:PEER.conn,clean:[],failed:false,accepted:true,stopped:false,lastSeen:Date.now()};session=q;scaffold(w);document.querySelector('.ps-shell').classList.add('ps-room');if(exitTheme())document.querySelector('.ps-header h1').textContent='出口密码锁';var captured=ctx;document.getElementById('ps-back').onclick=function(){if(captured.isActive())captured.abort();else{clearTimers();renderDungeonMenu();}};controls(q);function disconnected(){if(session===q)fail('同伴断线，出口锁操作已停止。请返回重新建房。');}if(q.conn){q.conn.on('close',disconnected);q.conn.on('error',disconnected);q.clean.push(function(){if(q.conn.off){q.conn.off('close',disconnected);q.conn.off('error',disconnected);}});}if(w==='A'){q.state=create(ctx);publish();}else document.getElementById('ps-status').textContent='等待房主同步出口锁…';q.timer=setInterval(function(){if(session!==q||q.failed||!ctx.isActive())return;if(Date.now()-q.lastSeen>7000){fail('同伴连接无响应，操作已停止。请返回重新建房。');return;}if(w==='A')publish();else packet({t:'psRoomPulse',roomSession:ctx.sessionId});},150);}
var oldHostData=dgHostOnData;dgHostOnData=function(d){if(d&&['psRoomInput','psRoomPulse'].includes(d.t)){var q=session;if(!q||!q.ctx||q.failed||!q.ctx.isActive()||d.roomSession!==q.ctx.sessionId)return;q.lastSeen=Date.now();if(d.t==='psRoomInput'&&d.kind!=='again'){input(q.state,d,'B');publish();}return;}return oldHostData(d);};
var oldGuestData=dgGuestOnData;dgGuestOnData=function(d){if(d&&d.t==='psRoomState'){var q=session;if(!q||!q.ctx||q.failed||!q.ctx.isActive()||d.roomSession!==q.ctx.sessionId||d.match!==q.match||!Number.isSafeInteger(d.frame)||d.frame<=q.lastFrame||!d.state)return;if(view&&view.id!==d.state.id)return;q.lastFrame=d.frame;q.lastSeen=Date.now();view=d.state;draw();return;}return oldGuestData(d);};
window.RoomGameAdapters=window.RoomGameAdapters||{};window.RoomGameAdapters[MODE]={host:function(ctx){enterRoom(ctx,'A');},guest:function(ctx){enterRoom(ctx,'B');}};
PLAYGROUNDS.push({id:MODE,name:'密码推条',icon:'▤',tag:'合作解谜',time:null,a:'看 B 的密码条，听指挥推自己的条带。',b:'看 A 的密码条，听指挥推自己的条带。'});
var oldClear=clearTimers;clearTimers=function(){stop();return oldClear.apply(this,arguments);};var oldRender=render;render=function(){if(S.mod===MODE)return S.role?lobby(S.role):choose();return oldRender.apply(this,arguments);};
window.PasswordStrip={create:create,input:input,snapshot:snapshot,state:function(){return view;}};
})();
