/* Four untimed cooperative puzzle prototypes. No automatic dungeon pool registration. */
(function(){
'use strict';
var META={lockbox:{name:'机关盒',icon:'⚙',a:'操作正面的滑块与齿轮，听 B 描述背面变化。',b:'按住背面锁销，观察齿轮窗口，再合力开盒。'},silhouette:{name:'影子拼图',icon:'◐',a:'调整灯光角度，听 B 描述影子该往哪边斜。',b:'对照目标轮廓旋转物件，指挥 A 调整灯光。'},evidence:{name:'证物还原',icon:'⌕',a:'检查现场物证，把细节告诉 B，一起锁定人物、工具与时间。',b:'查看人员记录与时间表，把对应关系告诉 A，一起提交结论。'},mirrors:{name:'镜面引光',icon:'◇',a:'转动蓝色镜片，与 B 一起让光线进入右侧接收器。',b:'转动橙色镜片，观察光路，告诉 A 该调哪块镜片。'}};
var IDS=Object.keys(META),active=null,view=null,dispose=null,role='A',key='',seq=0,held=false,ticket=0;
var CASES=[
 {title:'消失的怀表',scene:['窗户玻璃落在窗外：有人从室内制造了翻窗假象。','柜锁没有撬痕，锁孔内发现蓝色蜡屑。','停摆钟的指针落在整点后 10 分钟，停电记录能确定小时。'],records:['停电发生在 21 点这一小时。','林岚：蓝蜡复制钥匙；周岩：红柄钳；许晴：白色手套。','只有蓝蜡复制钥匙能无损打开柜锁，其他工具会留下划痕。'],people:['林岚','周岩','许晴'],tools:['复制钥匙','钳子','铁丝'],times:['20:10','21:10','21:40'],answer:[0,0,1],reason:'蓝蜡对应复制钥匙与林岚，停电小时与停摆分钟合起来是 21:10。'},
 {title:'温室失窃',scene:['窗台有圆形吸盘印，玻璃被完整取下。','花盆下有一段黄色胶带，上面粘着吸盘手柄的橡胶屑。','监控在浇水开始后 15 分钟失去画面。'],records:['浇水系统于 18:20 开启。','顾舟用绿色工具带，孟夏用黄色工具带，唐宁用蓝色工具带。','设备借用单：吸盘切割器由孟夏领取；顾舟借铁锤，唐宁借螺丝刀。'],people:['顾舟','孟夏','唐宁'],tools:['铁锤','螺丝刀','吸盘切割器'],times:['18:15','18:25','18:35'],answer:[1,2,2],reason:'吸盘痕与黄色胶带指向孟夏的切割器；18:20 加 15 分钟是 18:35。'},
 {title:'被调包的画',scene:['画框背面有星形螺丝的拆卸痕。','留下的手套印带一块三角补丁。','警报响起在闭馆前 25 分钟。'],records:['今晚 22:00 闭馆。','陈默的手套有圆补丁，苏禾的没有补丁，魏远的有三角补丁。','魏远借用星形扳手，陈默借小刀，苏禾借平口钳。'],people:['陈默','苏禾','魏远'],tools:['小刀','星形扳手','平口钳'],times:['21:35','21:25','22:25'],answer:[2,1,0],reason:'三角补丁与星形工具对应魏远；22:00 减 25 分钟是 21:35。'}
];
function rand(n){return Math.floor(Math.random()*n);}function clone(x){return JSON.parse(JSON.stringify(x));}
function newLight(s){s.lamp=0;s.rot=[0,0,0];s.targetLamp=pickNonzero();s.targetRot=[rand(4),rand(4),rand(4)];}
function pickNonzero(){return [-2,-1,1,2][rand(4)];}
function setupMirrors(s){var r=s.level===0?[[1,3],[1,1],[4,1],[4,4]]:s.level===1?[[1,3],[1,0],[3,0],[3,2],[5,2],[5,4]]:[[1,3],[1,5],[3,5],[3,1],[5,1],[5,4]];s.mirrors=r.map(function(p,i){return {x:p[0],y:p[1],rot:rand(2),owner:i%2?'B':'A'};});if(trace(s).hit)s.mirrors[0].rot=1-s.mirrors[0].rot;}
function make(mode){var s={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),mode:mode,ready:{A:false,B:false},started:false,done:false,win:false,level:0,revision:0,seq:{A:0,B:0},holds:{A:false,B:false},seen:{A:0,B:0},again:{A:false,B:false},msg:'阅读分工后准备。不限时，尝试不会扣血。',stage:0,slide:0,gear:0,targetGear:1+rand(5),pull:0,notes:{A:[-1,-1,-1],B:[-1,-1,-1]},votes:{A:false,B:false}};if(mode==='silhouette')newLight(s);if(mode==='mirrors')setupMirrors(s);return s;}
function win(s){s.done=true;s.win=true;s.holds={A:false,B:false};s.msg='合作完成！';}
function trace(s){var x=-1,y=3,dx=1,dy=0,path=[[-.5,3]],visited=new Set(),hit=false;for(var i=0;i<80;i++){x+=dx;y+=dy;path.push([x,y]);if(x===7&&y===4){hit=true;break;}if(x<0||x>6||y<0||y>5)break;var k=x+','+y+','+dx+','+dy;if(visited.has(k))break;visited.add(k);var m=s.mirrors.find(function(m){return m.x===x&&m.y===y;});if(m){var tx=dx;dx=m.rot?dy:-dy;dy=m.rot?tx:-tx;}}return {path:path,hit:hit};}
function action(s,d,who){if(!s||d.id!==s.id||!Number.isInteger(d.seq)||d.seq<=s.seq[who])return;s.seq[who]=d.seq;if(d.kind==='again'&&s.done){s.again[who]=true;return;}if(s.done)return;if(d.kind==='ready'){s.ready[who]=true;s.started=s.ready.A&&s.ready.B;if(s.started)s.msg={lockbox:'B 按住锁销，A 推动滑块。先一起打开第一层。',silhouette:'B 比较目标和当前投影，指挥灯光并旋转物件。',evidence:'先互报证据，再分别选人物、工具和时间。',mirrors:'从左侧光源沿光线追踪，轮流调整自己的镜片。'}[s.mode];return;}if(!s.started||d.revision!==s.revision)return;
 if(d.kind==='hold'){s.holds[who]=!!d.value;s.seen[who]=Date.now();return;}
 if(s.mode==='lockbox'){
  if(s.stage===0&&who==='A'&&d.kind==='slide'){if(!s.holds.B){s.msg='滑块被锁销卡住：请 B 按住背面锁销。';return;}s.slide++;if(s.slide>=3){s.stage=1;s.revision++;s.msg='第一层打开！A 转齿轮，B 看背面校准窗。';}}
  else if(s.stage===1&&who==='A'&&d.kind==='gear'){s.gear=(s.gear+1)%6;s.msg='齿轮转动，问 B 校准窗是否对齐。';}
  else if(s.stage===1&&who==='B'&&d.kind==='latch'){if(s.gear===s.targetGear){s.stage=2;s.revision++;s.msg='锁芯释放！两人各按住把手 1 秒。';}else s.msg='卡扣还扣不上，告诉 A 继续转齿轮。';}
 }else if(s.mode==='silhouette'){
  if(who==='A'&&d.kind==='lamp'&&(d.value===1||d.value===-1))s.lamp=Math.max(-2,Math.min(2,s.lamp+d.value));
  if(who==='B'&&d.kind==='rotate'&&Number.isInteger(d.value)&&d.value>=0&&d.value<3)s.rot[d.value]=(s.rot[d.value]+1)%4;
  if(d.kind==='check'&&who==='B'){if(s.lamp===s.targetLamp&&s.rot.every(function(n,i){return n===s.targetRot[i];})){s.level++;s.revision++;if(s.level===3)win(s);else{newLight(s);s.msg='轮廓吻合！换下一组投影。';}}else s.msg='轮廓还没重合。先对齐倾斜方向，再逐个转动物件。';}
 }else if(s.mode==='evidence'){
  if(d.kind==='note'&&Array.isArray(d.value)&&d.value.length===2&&d.value.every(function(n){return Number.isInteger(n)&&n>=0&&n<3;})){s.notes[who][d.value[0]]=d.value[1];s.votes[who]=false;}
  if(d.kind==='submit'&&s.notes[who].every(function(n){return n>=0;})){s.votes[who]=true;if(s.votes.A&&s.votes.B){if(s.notes.A.join()!==s.notes.B.join()){s.msg='两人的结论不同，先互报人物、工具和时间，再修改提交。';s.votes={A:false,B:false};}else if(s.notes.A.every(function(n,i){return n===CASES[s.level].answer[i];})){s.level++;s.revision++;s.notes={A:[-1,-1,-1],B:[-1,-1,-1]};s.votes={A:false,B:false};if(s.level===3)win(s);else s.msg='结论成立！下一案需要重新交换证据。';}else{s.msg='共同结论与证据矛盾。检查工具痕迹和时间关系，再提交。';s.votes={A:false,B:false};}}}
 }else if(s.mode==='mirrors'){
  if(d.kind==='mirror'&&Number.isInteger(d.value)&&s.mirrors[d.value]&&s.mirrors[d.value].owner===who)s.mirrors[d.value].rot=1-s.mirrors[d.value].rot;
  if(d.kind==='check'){if(trace(s).hit){s.level++;s.revision++;if(s.level===3)win(s);else{setupMirrors(s);s.msg='接收器亮起！下一层光路展开。';}}else s.msg='光还没到右侧接收器。沿光路找第一块偏转错误的镜片。';}
 }
}
function step(s,dt){if(!s.started||s.done)return;['A','B'].forEach(function(w){if(Date.now()-s.seen[w]>650)s.holds[w]=false;});if(s.mode==='lockbox'&&s.stage===2){s.pull=s.holds.A&&s.holds.B?s.pull+dt:0;if(s.pull>=1)win(s);}}
function snapshot(s,who){var v={id:s.id,mode:s.mode,ready:clone(s.ready),started:s.started,done:s.done,level:s.level,revision:s.revision,msg:s.msg,stage:s.stage,slide:s.slide,gear:s.gear,pull:s.pull,holds:clone(s.holds)};if(s.mode==='lockbox'&&who==='B')v.aligned=s.gear===s.targetGear;
 if(s.mode==='silhouette'){v.lamp=s.lamp;v.rot=s.rot.slice();if(who==='B'){v.targetLamp=s.targetLamp;v.targetRot=s.targetRot.slice();}}
 if(s.mode==='evidence'){var c=CASES[Math.min(2,s.level)];v.caseTitle=c.title;v.clues=(who==='A'?c.scene:c.records).slice();v.options=[c.people,c.tools,c.times];v.notes=s.notes[who].slice();v.voted=s.votes[who];v.partnerVoted=s.votes[who==='A'?'B':'A'];}
 if(s.mode==='mirrors'){v.mirrors=clone(s.mirrors);v.beam=trace(s);}return v;}
function send(kind,value){var s=role==='A'?active:view;if(!s)return;var d={t:'ppInput',id:s.id,revision:s.revision,seq:++seq,kind:kind,value:value};if(role==='A')action(active,d,'A');else netSend(d);}
function cleanup(){if(dispose)dispose();dispose=null;active=null;view=null;key='';held=false;}
function button(id,label){return '<button id="'+id+'">'+label+'</button>';}
function shell(mode,who){role=who;seq=0;key='';held=false;clearNetZones();var m=META[mode];$('app').innerHTML='<main class="pp-shell '+mode+'"><header><button id="back" aria-label="返回">‹</button><h1>'+m.name+'</h1><b>'+who+'</b></header><div class="pp-info"><span id="pp-progress"></span><span>不限时 · 自由尝试</span></div><section class="pp-paper"><h2 id="pp-title">先读分工</h2><p id="pp-duty">'+m[who.toLowerCase()]+'</p><div id="pp-stage"></div></section><div id="msg" role="status"></div><footer id="pp-controls"></footer></main>';$('back').onclick=function(){clearTimers();closePeer();location.search='';};
 var conn=PEER.conn;function disconnected(){cleanup();if($('msg'))$('msg').textContent='同伴断线，行动已停止。请返回重新建房。';document.querySelectorAll('.pp-shell button:not(#back)').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnected);function release(){if(held){held=false;send('hold',false);}}window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);var hb=setInterval(function(){if(held)send('hold',true);},180);dispose=function(){clearInterval(hb);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);if(conn&&conn.off)conn.off('close',disconnected);};
}
function bind(id,kind,value){var b=$(id);if(b)b.onclick=function(){send(kind,value);};}function hold(){var b=$('pp-hold');if(!b)return;b.onpointerdown=function(e){e.preventDefault();b.setPointerCapture(e.pointerId);held=true;send('hold',true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=function(){held=false;send('hold',false);};}
function svg(inner,h){return '<svg viewBox="0 0 360 '+(h||260)+'" role="img" aria-label="合作机关状态">'+inner+'</svg>';}
function projection(lamp,rot,color){var forms=[[[0,-23],[23,20],[-23,20]],[[ -22,-22],[0,-22],[0,0],[22,0],[22,22],[-22,22]],[[-24,-12],[12,-12],[12,-24],[25,0],[12,24],[12,12],[-24,12]]];return forms.map(function(points,i){var angle=rot[i]*Math.PI/2;return '<polygon points="'+points.map(function(p){var y=p[0]*Math.sin(angle)+p[1]*Math.cos(angle),x=p[0]*Math.cos(angle)-p[1]*Math.sin(angle);return (70+i*110+x+lamp*y*.42)+','+(70+y);}).join(' ')+'" fill="'+color+'" stroke="#313d50" stroke-width="2"/>';}).join('');}
function picture(s,who){if(s.mode==='lockbox')return svg('<rect x="34" y="26" width="292" height="205" rx="20" fill="#bb8157" stroke="#433b35" stroke-width="5"/><path d="M34 89h292" stroke="#433b35" stroke-width="5"/><g fill="#d3b281" stroke="#584838" stroke-width="2"><circle cx="50" cy="43" r="5"/><circle cx="309" cy="43" r="5"/><circle cx="50" cy="215" r="5"/><circle cx="309" cy="215" r="5"/></g><path d="M106 81v16m145-16v16" stroke="#ebca8c" stroke-width="15"/><rect x="68" y="116" width="130" height="32" rx="8" fill="#584d43"/><rect x="'+(70+s.slide*26)+'" y="109" width="45" height="46" rx="5" fill="#e5bb76" stroke="#433b35" stroke-width="3"/><g transform="translate(263 134) rotate('+s.gear*60+')"><circle r="33" fill="#d6b06e" stroke="#433b35" stroke-width="7"/><path d="M0-42v24M0 18v24M-42 0h24M18 0h24" stroke="#433b35" stroke-width="12"/></g><circle cx="180" cy="62" r="18" fill="'+(s.stage>0?'#9ccf9c':'#684f43')+'"/><text x="180" y="207" text-anchor="middle" fill="#fff5dc" font-size="17">'+(who==='B'&&s.stage===1?(s.aligned?'校准窗：对齐 ✓':'校准窗：未对齐'):s.stage===0?'锁销'+(s.holds.B?'已抬起':'卡住滑块'):s.stage===2?'合力拉开 '+Math.min(100,Math.round(s.pull*100))+'%':'齿轮层已打开')+'</text>');
 if(s.mode==='silhouette')return (who==='B'?'<div class="pp-caption">目标轮廓</div>'+svg(projection(s.targetLamp,s.targetRot,'#334256'),140):'<div class="pp-caption">灯光角度 '+s.lamp+' · 请 B 描述投影偏差</div>')+'<div class="pp-caption">当前投影</div>'+svg(projection(s.lamp,s.rot,'#ddac58'),140);
 if(s.mode==='evidence')return '<div class="pp-evidence">'+s.clues.map(function(c,i){return '<article><b>线索 '+(i+1)+'</b><p>'+c+'</p></article>';}).join('')+'</div>';
 var items='<rect width="360" height="280" rx="12" fill="#e4ebe9"/>';for(var x=0;x<7;x++)for(var y=0;y<6;y++)items+='<circle cx="'+(30+x*43)+'" cy="'+(25+y*43)+'" r="2" fill="#aebfbc"/>';items+='<polyline points="'+s.beam.path.map(function(p){return (30+p[0]*43)+','+(25+p[1]*43);}).join(' ')+'" fill="none" stroke="#de9541" stroke-width="5"/>';s.mirrors.forEach(function(m,i){var x=30+m.x*43,y=25+m.y*43;items+='<circle cx="'+x+'" cy="'+y+'" r="17" fill="'+(m.owner==='A'?'#a0d7e7':'#efb17c')+'" stroke="#334b55" stroke-width="2"/><path d="M'+(x-11)+' '+(y+(m.rot?-11:11))+'l22 '+(m.rot?22:-22)+'" stroke="#334b55" stroke-width="4"/><text x="'+x+'" y="'+(y-21)+'" text-anchor="middle" font-size="12">'+m.owner+(i+1)+'</text>';});items+='<rect x="325" y="182" width="26" height="28" rx="4" fill="'+(s.beam.hit?'#7cba84':'#95a8a2')+'"/><text x="14" y="149" font-size="16">→</text>';return svg(items,280);
}
function draw(s,who){if(!$('pp-stage'))return;view=s;var m=META[s.mode];$('pp-progress').textContent=s.mode==='lockbox'?'机关层 '+Math.min(3,s.stage+1)+' / 3':'进度 '+s.level+' / 3';$('pp-title').textContent=s.done?'合作完成':!s.started?'读完规则再准备':s.mode==='evidence'?s.caseTitle:s.mode==='lockbox'?['释放滑块','对齐齿轮','合力开盒'][s.stage]:m.name;$('msg').textContent=s.msg;
 var k=s.id+':'+s.revision+':'+s.started+':'+s.done;if(k!==key){key=k;held=false;var c=$('pp-controls');c.innerHTML='';if(s.done){c.innerHTML=button('pp-again','再来一局')+'<small>双方点击后重新开始</small>';bind('pp-again','again');$('pp-again').onclick=function(){send('again');this.disabled=true;this.textContent='等待同伴';};}else if(!s.started){c.innerHTML=button('pp-ready','读懂了 · 准备好了');bind('pp-ready','ready');}else if(s.mode==='lockbox'){if(s.stage===0)c.innerHTML=who==='A'?button('pp-slide','推动滑块 →'):button('pp-hold','按住抬起锁销');else if(s.stage===1)c.innerHTML=who==='A'?button('pp-gear','转动齿轮 ↻'):button('pp-latch','对齐了 · 扣上卡扣');else c.innerHTML=button('pp-hold','按住拉开盒盖');bind('pp-slide','slide');bind('pp-gear','gear');bind('pp-latch','latch');hold();}else if(s.mode==='silhouette'){c.innerHTML=who==='A'?'<div class="pp-row">'+button('pp-left','灯光向左')+button('pp-right','灯光向右')+'</div>':'<div class="pp-row">'+[0,1,2].map(function(i){return button('pp-rot-'+i,'旋转物件 '+(i+1));}).join('')+'</div>'+button('pp-check','核对轮廓');bind('pp-left','lamp',-1);bind('pp-right','lamp',1);[0,1,2].forEach(function(i){bind('pp-rot-'+i,'rotate',i);});bind('pp-check','check');}else if(s.mode==='evidence'){c.innerHTML=s.options.map(function(opts,i){return '<fieldset><legend>'+['人物','工具','时间'][i]+'</legend><div class="pp-row">'+opts.map(function(n,j){return '<button data-note="'+i+','+j+'">'+n+'</button>';}).join('')+'</div></fieldset>';}).join('')+button('pp-submit','提交我的结论');c.querySelectorAll('[data-note]').forEach(function(b){b.onclick=function(){send('note',b.dataset.note.split(',').map(Number));};});bind('pp-submit','submit');}else{c.innerHTML='<div class="pp-row">'+s.mirrors.map(function(m,i){return m.owner===who?button('pp-mirror-'+i,'转镜 '+(i+1)):'';}).join('')+'</div>'+button('pp-check','检查接收器');s.mirrors.forEach(function(m,i){bind('pp-mirror-'+i,'mirror',i);});bind('pp-check','check');}}
 $('pp-stage').innerHTML=s.done?'<div class="pp-complete">✓<p>'+({lockbox:'盒盖打开，钥匙到手',silhouette:'三组影子全部重合',evidence:'三宗证物全部还原',mirrors:'三层光路全部接通'}[s.mode])+'</p></div>':!s.started?'<div class="pp-intro">'+m.icon+'<p>两台设备，开语音交流<br>各自的信息和操作都不可缺少</p></div>':picture(s,who);
 if($('pp-ready')){$('pp-ready').disabled=s.ready[who];$('pp-ready').textContent=s.ready[who]?'等待同伴准备':'读懂了 · 准备好了';}if($('pp-hold'))$('pp-hold').classList.toggle('selected',s.holds[who]);if(s.mode==='evidence'&&s.started&&!s.done){document.querySelectorAll('[data-note]').forEach(function(b){var a=b.dataset.note.split(',').map(Number);b.classList.toggle('selected',s.notes[a[0]]===a[1]);});$('pp-submit').disabled=s.voted||s.notes.some(function(n){return n<0;});$('pp-submit').textContent=s.voted?'已提交，等待同伴':'提交我的结论';}
}
function host(mode){clearTimers();cleanup();S.mod=mode;shell(mode,'A');var s=make(mode);active=s;var last=Date.now();function tick(){if(active!==s)return;var now=Date.now();step(s,(now-last)/1000);last=now;draw(snapshot(s,'A'),'A');netSend({t:'ppState',state:snapshot(s,'B')});if(s.done&&s.again.A&&s.again.B)host(mode);}tick();timers.push(setInterval(tick,80));}
function guest(mode){clearTimers();cleanup();S.mod=mode;shell(mode,'B');if(PEER.conn&&!PEER.conn._puzzleListener){PEER.conn._puzzleListener=function(d){dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._puzzleListener);}}
function lobby(mode,who){clearTimers();closePeer();window._dungeon=false;window._netMode=who==='A'?'host':'guest';var t=++ticket,m=META[mode];$('app').innerHTML='<main class="pp-shell '+mode+'"><header><button id="back">‹</button><h1>'+m.name+'</h1><b>'+who+'</b></header><section class="pp-paper"><h2>'+(who==='A'?'创建房间':'加入房间')+'</h2><p>'+m[who.toLowerCase()]+'</p>'+(who==='B'?'<input id="rc" inputmode="numeric" maxlength="4" placeholder="四位房间码">'+button('joing','加入房间'):'')+'<p id="pp-status">'+(who==='A'?'正在连接服务…':'输入 A 的房间码')+'</p></section></main>';$('back').onclick=function(){ticket++;clearTimers();closePeer();location.search='';};function status(txt){if(t===ticket&&$('pp-status'))$('pp-status').textContent=txt;}
 function connect(code){loadPeerLib(function(P){if(t!==ticket)return;if(!P){status('联网组件加载失败，请返回重试。');return;}var p=newPeerId(who==='A'?'room'+code:null,peerOpts());PEER.peer=p;PEER.room=code;PEER.isHost=who==='A';var joined=false,timeout=setTimeout(function(){if(!joined){status('连接超时，请返回重试。');p.destroy();}},18000);timers.push(timeout);p.on('error',function(){clearTimeout(timeout);status('连接失败，请返回重试。');});function opened(c){if(t!==ticket){c.close();return;}joined=true;clearTimeout(timeout);PEER.conn=c;if(who==='A'){c.on('data',function(d){dgHostOnData(d);});host(mode);}else guest(mode);}p.on('open',function(){if(who==='A'){clearTimeout(timeout);status('房间码：'+code+' · 等待同伴加入');}else{var c=p.connect('room'+code,{reliable:true});c.on('open',function(){opened(c);});}});if(who==='A')p.on('connection',function(c){if(joined){c.close();return;}c.on('open',function(){opened(c);});});});}
 if(who==='A')connect(1000+rand(9000));else{$('joing').onclick=function(){var code=$('rc').value;if(!/^\d{4}$/.test(code)){status('请输入四位数字。');return;}this.disabled=true;connect(code);};}
}
function choose(mode){var m=META[mode];$('app').innerHTML='<main class="pp-shell '+mode+'"><header><button id="back">‹</button><h1>'+m.name+'</h1></header><section class="pp-paper"><h2>不限时合作解谜</h2><p>A：'+m.a+'</p>'+button('pp-host','A · 创建房间')+'<p>B：'+m.b+'</p>'+button('pp-join','B · 加入房间')+'</section></main>';$('back').onclick=function(){location.search='';};$('pp-host').onclick=function(){S.role='A';lobby(mode,'A');};$('pp-join').onclick=function(){S.role='B';lobby(mode,'B');};}
IDS.forEach(function(id){PLAYGROUNDS.push({id:id,name:META[id].name,icon:META[id].icon,tag:'合作解谜',time:null,a:META[id].a,b:META[id].b});});var oc=clearTimers;clearTimers=function(){cleanup();return oc();};var or=render;render=function(){if(IDS.includes(S.mod))return S.role?lobby(S.mod,S.role):choose(S.mod);return or.apply(this,arguments);};var hd=dgHostOnData;dgHostOnData=function(d){if(d&&d.t==='ppInput'){action(active,d,'B');return;}return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(d&&d.t==='ppState'){if(!IDS.includes(S.mod)||!$('pp-stage'))return;if(d.state.mode!==S.mod){$('msg').textContent='加入的房间是其他玩法，请返回选择与 A 相同的玩法。';return;}if(view&&view.id!==d.state.id)guest(S.mod);draw(d.state,'B');return;}return gd(d);};window.PuzzlePack={create:make,input:action,step:step,snapshot:snapshot,trace:trace,state:function(){return active||view;}};
})();
