/* Two-person radio. Host owns timing; each receiver gets only its own instruments. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',seq=0,held=0,terminal=null,retired=new Set(),radioConnection=null;
var clamp=function(x,a,b){return Math.max(a,Math.min(b,x));};
var feedback=null,radioCtx=null;
function session(){return window.RoomSession&&typeof RoomSession.current==='function'?RoomSession.current():null;}
function config(tier){tier=clamp(Math.round(Number(tier)||1),1,5);return {tier:tier,goal:[2,3,4,5,6][tier-1],width:[14,10,8,6,5][tier-1],hold:[1,1.4,1.8,2.2,2.6][tier-1],time:[90,110,150,180,210][tier-1],drift:[0,0,2,3,4][tier-1],gainDrift:[0,0,0,2,3][tier-1],speed:[0,0,.12,.14,.16][tier-1],noiseFor:[0,0,.7,1,1.3][tier-1]};}
function nextChannel(s){if(s.tier===1){s.tf=[40,65][s.got%2];s.tg=[60,35][s.got%2];}else{s.tf=22+s.random()*56;s.tg=22+s.random()*56;}}
function planLabel(s){return ['教学 · 固定频道','入门 · 随机频道','标准 · 频率慢漂','困难 · 双端慢漂','极限 · 双端追踪'][s.tier-1];}
function ownAligned(s){return s.quality>.86;}

function feedbackEmit(type,tag){try{if(window.GameFeedback&&typeof GameFeedback.emit==='function')GameFeedback.emit(type,{source:'dial:'+tag});}catch(_){/* Feedback must never interrupt gameplay. */}}
function feedbackState(s){
 if(!feedback||feedback.id!==s.id)feedback={id:s.id,prev:null,lastCue:-Infinity,lastLock:-Infinity,seconds:new Set(),warned:false,ended:false};
 var f=feedback,p=f.prev;if(f.ended||p&&s.elapsed<p.elapsed)return;
 var v={elapsed:s.elapsed,got:s.got,near:s.quality>.5,aligned:s.quality>.86,pair:s.quality>.86&&s.partnerGood&&!s.noise,noise:s.noise,charge:s.charge,playing:s.ready.A&&s.ready.B&&s.cd===0&&!s.done};f.prev=v;
 if(s.done){f.ended=true;return;} // RoomResults owns terminal success/fail once per resultId.
 if(!v.playing||!p||!p.playing)return;
 var now=performance.now(),type=null,tag='';
 if(s.got>p.got){type='correct';tag='fragment';}
 else if(v.noise&&!p.noise){type='warning';tag='interference';}
 else if(v.pair&&!p.pair&&now-f.lastLock>=1200){type='correct';tag='pair-aligned';f.lastLock=now;}
 else if(p.pair&&!v.pair&&!v.noise&&s.got===p.got&&s.charge<p.charge&&now-f.lastLock>=1200){type='error';tag='lock-lost';f.lastLock=now;}
 else if(now-f.lastCue>=1200&&(v.aligned&&!p.aligned||v.near&&!p.near)){type='reveal';tag='local-signal';f.lastCue=now;}
 if(type)feedbackEmit(type,tag);
 var sec=Math.ceil(s.time);
 if(sec<=10&&sec>0&&!f.warned){f.warned=true;if(!type)feedbackEmit('warning','time-low');}
 if(sec<=5&&sec>0&&!f.seconds.has(sec)){f.seconds.add(sec);if(!type)feedbackEmit('tick','time-public');}
}
function roomId(){var current=session()||radioCtx;if(current)return current.roomId||'';return window._dungeon&&typeof DUNGEON!=='undefined'&&DUNGEON?DUNGEON.roomId:'';}
var mic='<svg viewBox="0 0 48 64" aria-hidden="true"><rect x="14" y="3" width="20" height="35" rx="10" fill="currentColor"/><path d="M9 27v4a15 15 0 0 0 30 0v-4M24 46v12M13 59h22" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round"/><path d="M19 12h10M19 19h10M19 26h10" stroke="#33404a" stroke-width="2"/></svg>';
function studio(){return roomId()==='room-21';}
function studioDraw(s){if(!studio())return;var el=document.querySelector('.radio-scene');if(!el)return;el.dataset.recording=!!(s.ready.A&&s.ready.B&&s.cd===0&&!s.done&&!s.noise&&s.charge>0);$('goal').textContent='节目片段 '+s.got+' / '+s.goal;$('radio-round').textContent=s.done?'节目已录好':planLabel(s);if(s.done){$('msg').textContent=s.win?'节目已录好。好男人，收工！':'录音时间到了，和搭档重新调台。';$('radio-lock').textContent=s.win?'播音完成 · 等待返回':'本次录音结束';}else if(s.noise){$('msg').textContent='连线有杂音，稳住旋钮，录音进度会保留。';}else if(s.charge>0&&s.partnerGood&&s.quality>.86){$('msg').textContent='正在录音，双方保持住，别转过头。';}if($('radio-studio-lamp'))$('radio-studio-lamp').textContent=s.done?'录音结束':!s.ready.A||!s.ready.B||s.cd>0?'试音中':s.noise?'连线受扰':'播音中';}
function make(options){options=options||session()||radioCtx||{};var cfg=config(options.tier||3),seed=Number.isInteger(options.seed)?options.seed:Math.floor(Math.random()*4294967296);var s={id:options.runId||options.sessionId||Date.now().toString(36)+Math.random().toString(36).slice(2),tier:cfg.tier,cfg:cfg,goal:cfg.goal,hold:cfg.hold,elapsed:0,time:cfg.time,ready:{A:false,B:false},practice:{A:false,B:false},cd:3,f:25,g:50,phase:0,got:0,charge:0,inputs:{A:0,B:0},seen:{A:0,B:0},seq:{A:-1,B:-1},done:false,win:false};s.random=function(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};nextChannel(s);return s;}
function metrics(s){var c=s.cfg,target=s.tf+Math.sin(s.phase*c.speed)*c.drift,gain=s.tg+Math.sin(s.phase*c.speed*.85)*c.gainDrift,noise=c.noiseFor>0&&s.got>0&&s.phase%9>9-c.noiseFor;return {f:clamp(.86+(c.width-Math.abs(s.f-target))/100,0,1),g:clamp(.86+(c.width-Math.abs(s.g-gain))/100,0,1),noise:noise};}
function snap(s,who){var m=metrics(s);return {id:s.id,tier:s.tier,goal:s.goal,hold:s.hold,window:s.cfg.width,elapsed:s.elapsed,time:s.time,ready:s.ready,practice:s.practice,cd:s.cd,got:s.got,charge:s.charge,done:s.done,win:s.win,noise:m.noise,value:who==='A'?s.f:s.g,quality:who==='A'?m.f:m.g,partnerGood:who==='A'?m.g>.86:m.f>.86,inputs:s.inputs,tutorialTarget:s.tier===1?(who==='A'?s.tf:s.tg):null};}
function step(s,dt){if(s.done)return;var started=s.ready.A&&s.ready.B;s.f=clamp(s.f+s.inputs.A*15*dt,0,100);s.g=clamp(s.g+s.inputs.B*15*dt,0,100);if(!started)return;if(s.cd>0){s.cd=Math.max(0,s.cd-dt);return;}s.elapsed+=Math.min(dt,s.time);s.time=Math.max(0,s.time-dt);s.phase+=dt;var m=metrics(s);if(!m.noise)s.charge=clamp(s.charge+(m.f>.86&&m.g>.86?dt:-dt*.55),0,s.hold);if(s.charge>=s.hold){s.got++;s.charge=0;s.phase=0;if(s.got<s.goal)nextChannel(s);}if(s.got===s.goal||s.time===0){s.done=true;s.win=s.got===s.goal;s.inputs={A:0,B:0};}}
function input(d,w){var s=active;if(!s||d.id!==s.id||s.done)return;if(d.t==='radioReady'){if(s.practice[w])s.ready[w]=true;return;}if(!Number.isInteger(d.seq)||d.seq<=s.seq[w]||![-1,0,1].includes(d.v))return;s.seq[w]=d.seq;s.inputs[w]=d.v;s.seen[w]=performance.now();if(d.v)s.practice[w]=true;}
function act(v){var before=held;held=v;var s=role==='A'?active:view;if(!s)return;if(v&&v!==before&&!s.done)feedbackEmit('tap','adjust');var d={t:'radioInput',id:s.id,seq:++seq,v:v};if(role==='A')input(d,'A');else netSend(d);}
function clean(){feedback=null;radioCtx=null;terminal=active&&active.done?active:view&&view.done?view:terminal;if(dispose)dispose();dispose=null;active=view=null;held=0;}
function shell(w){role=w;seq=0;clearNetZones();var scene=window.RadioScenes&&window.RadioScenes[roomId()]||{};
 $('app').innerHTML='<section class="radio-scene"><div class="radio-background" aria-hidden="true"></div><div class="radio-decor radio-decor-left" aria-hidden="true"></div><div class="radio-decor radio-decor-right" aria-hidden="true"></div><main class="radio-console"><header><button id="radio-back" aria-label="返回">‹</button><strong>双人搜台</strong><b id="count">--s</b></header><div class="radio-track"><span id="goal">情报 0 / 3</span><span id="radio-round">固定频道</span></div><section class="radio-display"><div class="radio-display-label"><span>'+(w==='A'?'频率示波器':'增益接收器')+'</span><b id="radio-value">—</b></div><canvas id="radio-wave" width="600" height="300"></canvas><div class="radio-meter"><i id="radio-quality"></i></div><span id="radio-reading">等待信号</span><div class="radio-capture"><i id="radio-charge"></i><span id="radio-lock">稳定 2 秒，自动收录</span></div></section><p id="msg" class="radio-message" role="status">先试按一次调节按钮，再准备。</p><footer class="radio-controls" data-role="'+w+'"><div class="radio-duty"><b>'+w+'</b><span>'+(w==='A'?'你调频率 · 波形越平顺越接近':'你调增益 · 信号条越满越接近')+'</span></div><div class="radio-buttons"><button id="radio-minus">−<small>按住降低</small></button><div class="radio-knob" aria-hidden="true"><i></i></div><button id="radio-plus">+<small>按住升高</small></button></div><button id="radio-ready" disabled>先试按 ＋ 或 −</button><span id="radio-partner">另一位负责'+(w==='A'?'增益':'频率')+'，保持沟通</span><button id="radio-again" hidden>再来一局</button></footer></main></section>';
 if(studio()){document.querySelector('.radio-scene').classList.add('radio-studio');document.querySelector('.radio-console header strong').textContent='好男人就是我';document.querySelector('.radio-display-label span').innerHTML=mic+'<span>'+(w==='A'?'调频台':'混音台')+' · <b id="radio-studio-lamp">试音中</b></span>';document.querySelector('.radio-decor-left').innerHTML='<div class="radio-studio-mic">'+mic+'</div>';document.querySelector('.radio-decor-right').innerHTML='<div class="radio-studio-sign">ON AIR<small>深夜电台 · 录音室</small></div>';document.querySelector('.radio-duty span').textContent=w==='A'?'调频师 · 调清波形，接入来电':'混音师 · 调好增益，清晰收音';}
 ['background','left','right'].forEach(function(k){if(!scene[k])return;var img=document.createElement('img');img.src=scene[k];img.alt='';document.querySelector(k==='background'?'.radio-background':'.radio-decor-'+k).appendChild(img);});
 $('radio-back').onclick=function(){if(radioCtx&&radioCtx.abort){radioCtx.abort();return;}if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 $('radio-ready').onclick=function(){act(0);var s=role==='A'?active:view;if(!s)return;feedbackEmit('tap','ready');var d={t:'radioReady',id:s.id};if(w==='A')input(d,'A');else netSend(d);};

 [-1,1].forEach(function(v){var b=$(v<0?'radio-minus':'radio-plus');b.onpointerdown=function(e){if(b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);act(v);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=function(){act(0);};});
 function down(e){if(!['ArrowLeft','ArrowRight'].includes(e.key)||e.repeat||$('radio-plus').disabled)return;e.preventDefault();act(e.key==='ArrowLeft'?-1:1);}function up(e){if(['ArrowLeft','ArrowRight'].includes(e.key))act(0);}function blur(){act(0);}
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);var heart=setInterval(function(){if(held)act(held);},180),conn=PEER.conn;
 function closed(){clean();if($('msg')){$('msg').textContent='连接断开，请返回重新建房。';document.querySelectorAll('.radio-controls button').forEach(function(b){b.disabled=true;});}}
 if(conn)conn.on('close',closed);dispose=function(){clearInterval(heart);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);if(conn&&conn.off)conn.off('close',closed);};
}
function draw(s,w){if(!$('radio-wave'))return;view=s;feedbackState(s);var started=s.ready.A&&s.ready.B,waiting=started&&s.cd>0;
 $('count').textContent=Math.ceil(s.time)+'s';$('goal').textContent='情报 '+s.got+' / '+s.goal;$('radio-round').textContent=s.done?'收录完成':planLabel(s);$('radio-value').textContent=w==='A'?(88+s.value*.2).toFixed(1)+' MHz':Math.round(s.value)+' dB';
 $('radio-quality').style.width=s.quality*100+'%';$('radio-charge').style.width=s.charge/s.hold*100+'%';$('radio-reading').textContent=s.noise?'短暂干扰 · 保持旋钮':s.quality>.86?'你的信号已对准':s.quality>.5?'正在接近 · 小幅调整':'信号微弱 · 继续搜索';$('radio-lock').textContent=s.done?(s.win?'全部情报已收录':'本轮结束'):s.noise?'干扰中 · 收录进度保留':'收录 '+s.charge.toFixed(1)+' / '+s.hold.toFixed(1)+' 秒';
 $('radio-ready').hidden=started||s.done;$('radio-ready').disabled=!s.practice[w]||s.ready[w];$('radio-ready').textContent=s.ready[w]?'已准备，等待同伴':s.practice[w]?'练习完成 · 准备搜台':'先试按 ＋ 或 −';
 ['radio-minus','radio-plus'].forEach(function(id){$(id).disabled=s.done||waiting||(!started&&s.ready[w]);});$('radio-again').hidden=true;
 $('msg').textContent=s.done?(s.win?'收到！全部情报拼接成功。':'时间到，换个方向再搜一次。'):!started?'练习：按住调节，松手停住；双方准备后计时。':waiting?'双方就绪 · '+Math.ceil(s.cd):s.noise?'杂波来了！稳住，等待干扰过去。':s.quality>.86?(s.partnerGood?'两端对准，保持住！':'你已对准，告诉同伴继续调节。'):'寻找最清晰的位置，越过后反向微调。';
 $('radio-partner').textContent=s.partnerGood?'同伴信号已对准':'同伴正在寻找信号';document.querySelector('.radio-knob i').style.transform='rotate('+(s.value*2.7-135)+'deg)';studioDraw(s);if(s.tier===1&&!s.done&&s.cd===0){$('msg').textContent='教学目标 '+(w==='A'?(88+s.tutorialTarget*.2).toFixed(1)+' MHz':s.tutorialTarget+' dB')+' · 按住调节，两端保持 '+s.hold+' 秒';} $('radio-quality').parentElement.style.setProperty('--lock-start', '86%');
 var c=$('radio-wave').getContext('2d');c.clearRect(0,0,600,300);c.strokeStyle='#557477';c.lineWidth=1;for(var x=0;x<600;x+=30){c.beginPath();c.moveTo(x,0);c.lineTo(x,300);c.stroke();}for(var y=0;y<300;y+=30){c.beginPath();c.moveTo(0,y);c.lineTo(600,y);c.stroke();}c.strokeStyle=w==='A'?'#91e0e8':'#ffce85';c.lineWidth=4;c.beginPath();var t=performance.now()/500;for(var i=0;i<600;i++){var noise=(1-s.quality)*(Math.sin(i*1.71+t)*28+Math.sin(i*.33-t)*30)+(s.noise?Math.sin(i*.81+t)*35:0);var yy=150+Math.sin(i*.035+t)*55+noise;if(i===0)c.moveTo(i,yy);else c.lineTo(i,yy);}c.stroke();
}
function beginResult(s,w){
 if(radioCtx||session()||window._dungeon)return;
 RoomResults.begin({runId:s.id,role:w,connection:PEER.conn,gameId:'dial',title:'双人搜台',dungeon:null,
 onContinue:function(){if(w==='A')host();else guest();},
 onExit:function(){netSend({t:'bye'});clearTimers();closePeer();S.mod=null;S.role=null;render();}});
}
function resultData(s){return {win:s.win,reasonCode:s.win?'completed':'timeout',reason:s.win?'全部频道已锁定收录。':'时间耗尽，未能收齐全部频道。',metrics:{durationMs:Math.round(s.elapsed*1000),timeLeftMs:Math.round(s.time*1000),completed:s.got,goal:s.goal}};}
function host(ctx){ctx=ctx||(window._dungeon?window._roomGameContext:null);clearTimers();clean();terminal=null;radioCtx=ctx||null;S.mod='dial';window._dead=false;shell('A');var s=make(session()||ctx||{});active=s;beginResult(s,'A');var last=performance.now(),next=0;draw(snap(s,'A'),'A');var iv=setInterval(function(){if(active!==s||ctx&&ctx.isActive&&!ctx.isActive()&&!s.done){clearInterval(iv);return;}var now=performance.now(),dt=Math.min(.06,(now-last)/1000);last=now;['A','B'].forEach(function(w){if(now-s.seen[w]>650)s.inputs[w]=0;});step(s,dt);S.time=Math.ceil(s.time);if(now>=next||s.done){draw(snap(s,'A'),'A');netSend({t:'radioState',state:snap(s,'B')});next=now+66;}if(s.done&&!s.reported){s.reported=true;held=0;terminal=s;clearInterval(iv);var data=resultData(s);if(ctx)ctx.finish(data);else if(!window._dungeon)RoomResults.report(data);}},16);timers.push(iv);}
function guest(ctx){ctx=ctx||(window._dungeon?window._roomGameContext:null);if(radioConnection!==PEER.conn){retired.clear();radioConnection=PEER.conn;}if(view)retired.add(view.id);var dg=window._dungeon;clearTimers();clean();terminal=null;radioCtx=ctx||null;S.mod='dial';window._dead=false;shell('B');if(!dg&&!ctx&&PEER.conn&&!PEER.conn._radioListener){var conn=PEER.conn;conn._radioListener=function(d){if(window.RoomResults&&RoomResults.consume(d,conn))return;dgGuestOnData(d);};conn.on('data',conn._radioListener);}}
window.RoomGameAdapters=window.RoomGameAdapters||{};window.RoomGameAdapters.dial={host:host,guest:guest};
var oc=clearTimers;clearTimers=function(){clean();return oc();};var or=render;render=function(){if(S.mod==='dial'){if(!S.role)return renderPickRole();return S.role==='A'?renderHost():renderJoin();}return or();};
var oh=startHostGame;startHostGame=function(){return S.mod==='dial'?host():oh();};var og=renderGuestUI;renderGuestUI=function(code){return S.mod==='dial'?guest():og(code);};var op=renderPlayDungeonHost;renderPlayDungeonHost=function(){return S.mod==='dial'?host():op();};var om=renderManual;renderManual=function(){return S.mod==='dial'?(window._dungeon?guest():renderJoin()):om();};
var hd=dgHostOnData;dgHostOnData=function(d){if(window.RoomResults&&RoomResults.consume(d,PEER.conn))return;if(d.t==='radioInput'||d.t==='radioReady')return input(d,'B');if(d.t==='radioAgain')return;return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(window.RoomResults&&RoomResults.consume(d,PEER.conn))return;if(d.t==='radioState'){if(!d.state)return;var current=session()||radioCtx;if(current&&(d.state.id!==(current.runId||current.sessionId)||current.isActive&&!current.isActive()))return;if(retired.has(d.state.id))return;if(S.mod!=='dial'||!$('radio-wave'))return;if(view&&view.id!==d.state.id)guest(radioCtx);if(!view)beginResult(d.state,'B');draw(d.state,'B');return;}return gd(d);};
window.RadioScenes=window.RadioScenes||{};window.RadioMobile={create:make,step:step,snapshot:snap,config:config,state:function(){return active?snap(active,'A'):view|| (terminal&&terminal.cfg?snap(terminal,'A'):terminal);}};
})();
