/* Two-person radio. Host owns timing; each receiver gets only its own instruments. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',seq=0,held=0;
var clamp=function(x,a,b){return Math.max(a,Math.min(b,x));};
function make(){return {id:Date.now().toString(36)+Math.random().toString(36).slice(2),time:window._dungeon?coopTime(100):100,ready:{A:false,B:false},practice:{A:false,B:false},cd:3,f:25,g:50,tf:35+Math.random()*35,tg:30+Math.random()*40,phase:0,got:0,charge:0,inputs:{A:0,B:0},seen:{A:0,B:0},seq:{A:-1,B:-1},done:false,win:false};}
function metrics(s){var target=s.tf+(s.got===1?Math.sin(s.phase*.5)*7:0),noise=s.got===2&&s.phase%9>6.8;return {f:clamp(1-Math.abs(s.f-target)/30,0,1),g:clamp(1-Math.abs(s.g-s.tg)/35,0,1),noise:noise};}
function snap(s,who){var m=metrics(s);return {id:s.id,time:s.time,ready:s.ready,practice:s.practice,cd:s.cd,got:s.got,charge:s.charge,done:s.done,win:s.win,noise:m.noise,value:who==='A'?s.f:s.g,quality:who==='A'?m.f:m.g,partnerGood:who==='A'?m.g>.86:m.f>.86,inputs:s.inputs};}
function step(s,dt){if(s.done)return;var started=s.ready.A&&s.ready.B;s.f=clamp(s.f+s.inputs.A*15*dt,0,100);s.g=clamp(s.g+s.inputs.B*15*dt,0,100);if(!started)return;if(s.cd>0){s.cd=Math.max(0,s.cd-dt);return;}s.time=Math.max(0,s.time-dt);s.phase+=dt;var m=metrics(s);if(!m.noise)s.charge=clamp(s.charge+(m.f>.86&&m.g>.86?dt:-dt*.55),0,2);if(s.charge>=2){s.got++;s.charge=0;s.phase=0;s.tf=20+Math.random()*60;s.tg=20+Math.random()*60;}if(s.got===3||s.time===0){s.done=true;s.win=s.got===3;s.inputs={A:0,B:0};}}
function input(d,w){var s=active;if(!s||d.id!==s.id||s.done)return;if(d.t==='radioReady'){if(s.practice[w])s.ready[w]=true;return;}if(!Number.isInteger(d.seq)||d.seq<=s.seq[w]||![-1,0,1].includes(d.v))return;s.seq[w]=d.seq;s.inputs[w]=d.v;s.seen[w]=performance.now();if(d.v)s.practice[w]=true;}
function act(v){held=v;var s=role==='A'?active:view;if(!s)return;var d={t:'radioInput',id:s.id,seq:++seq,v:v};if(role==='A')input(d,'A');else netSend(d);}
function clean(){if(dispose)dispose();dispose=null;active=view=null;held=0;}
function shell(w){role=w;seq=0;clearNetZones();var scene=window.RadioScenes&&window.RadioScenes[typeof selectedRoomId==='undefined'?'':selectedRoomId]||{};
 $('app').innerHTML='<section class="radio-scene"><div class="radio-background" aria-hidden="true"></div><div class="radio-decor radio-decor-left" aria-hidden="true"></div><div class="radio-decor radio-decor-right" aria-hidden="true"></div><main class="radio-console"><header><button id="radio-back" aria-label="返回">‹</button><strong>双人搜台</strong><b id="count">--s</b></header><div class="radio-track"><span id="goal">情报 0 / 3</span><span id="radio-round">固定频道</span></div><section class="radio-display"><div class="radio-display-label"><span>'+(w==='A'?'频率示波器':'增益接收器')+'</span><b id="radio-value">—</b></div><canvas id="radio-wave" width="600" height="300"></canvas><div class="radio-meter"><i id="radio-quality"></i></div><span id="radio-reading">等待信号</span><div class="radio-capture"><i id="radio-charge"></i><span id="radio-lock">稳定 2 秒，自动收录</span></div></section><p id="msg" class="radio-message" role="status">先试按一次调节按钮，再准备。</p><footer class="radio-controls" data-role="'+w+'"><div class="radio-duty"><b>'+w+'</b><span>'+(w==='A'?'你调频率 · 波形越平顺越接近':'你调增益 · 信号条越满越接近')+'</span></div><div class="radio-buttons"><button id="radio-minus">−<small>按住降低</small></button><div class="radio-knob" aria-hidden="true"><i></i></div><button id="radio-plus">+<small>按住升高</small></button></div><button id="radio-ready" disabled>先试按 ＋ 或 −</button><span id="radio-partner">另一位负责'+(w==='A'?'增益':'频率')+'，保持沟通</span><button id="radio-again" hidden>再来一局</button></footer></main></section>';
 ['background','left','right'].forEach(function(k){if(!scene[k])return;var img=document.createElement('img');img.src=scene[k];img.alt='';document.querySelector(k==='background'?'.radio-background':'.radio-decor-'+k).appendChild(img);});
 $('radio-back').onclick=function(){if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 $('radio-ready').onclick=function(){act(0);var s=role==='A'?active:view;if(!s)return;var d={t:'radioReady',id:s.id};if(w==='A')input(d,'A');else netSend(d);};
 $('radio-again').onclick=function(){var s=w==='A'?active:view;if(!s)return;if(w==='A')active.againA=true;else netSend({t:'radioAgain',id:s.id});$('radio-again').disabled=true;$('radio-again').textContent='等待同伴再来一局';};
 [-1,1].forEach(function(v){var b=$(v<0?'radio-minus':'radio-plus');b.onpointerdown=function(e){if(b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);act(v);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=function(){act(0);};});
 function down(e){if(!['ArrowLeft','ArrowRight'].includes(e.key)||e.repeat||$('radio-plus').disabled)return;e.preventDefault();act(e.key==='ArrowLeft'?-1:1);}function up(e){if(['ArrowLeft','ArrowRight'].includes(e.key))act(0);}function blur(){act(0);}
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);var heart=setInterval(function(){if(held)act(held);},180),conn=PEER.conn;
 function closed(){clean();if($('msg')){$('msg').textContent='连接断开，请返回重新建房。';document.querySelectorAll('.radio-controls button').forEach(function(b){b.disabled=true;});}}
 if(conn)conn.on('close',closed);dispose=function(){clearInterval(heart);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);if(conn&&conn.off)conn.off('close',closed);};
}
function draw(s,w){if(!$('radio-wave'))return;view=s;var started=s.ready.A&&s.ready.B,waiting=started&&s.cd>0;
 $('count').textContent=Math.ceil(s.time)+'s';$('goal').textContent='情报 '+s.got+' / 3';$('radio-round').textContent=['固定频道','追踪漂移','干扰频道','收录完成'][s.got];$('radio-value').textContent=w==='A'?(88+s.value*.2).toFixed(1)+' MHz':Math.round(s.value)+' dB';
 $('radio-quality').style.width=s.quality*100+'%';$('radio-charge').style.width=s.charge/2*100+'%';$('radio-reading').textContent=s.noise?'短暂干扰 · 保持旋钮':s.quality>.86?'你的信号已对准':s.quality>.5?'正在接近 · 小幅调整':'信号微弱 · 继续搜索';$('radio-lock').textContent=s.done?(s.win?'三段情报已收录':'本轮结束'):s.noise?'干扰中 · 收录进度保留':'收录 '+s.charge.toFixed(1)+' / 2.0 秒';
 $('radio-ready').hidden=started||s.done;$('radio-ready').disabled=!s.practice[w]||s.ready[w];$('radio-ready').textContent=s.ready[w]?'已准备，等待同伴':s.practice[w]?'练习完成 · 准备搜台':'先试按 ＋ 或 −';
 ['radio-minus','radio-plus'].forEach(function(id){$(id).disabled=s.done||waiting||(!started&&s.ready[w]);});$('radio-again').hidden=!s.done||!!window._dungeon;
 $('msg').textContent=s.done?(s.win?'收到！三段情报拼接成功。':'时间到，换个方向再搜一次。'):!started?'练习：按住调节，松手停住；双方准备后计时。':waiting?'双方就绪 · '+Math.ceil(s.cd):s.noise?'杂波来了！稳住，等待干扰过去。':s.quality>.86?(s.partnerGood?'两端对准，保持住！':'你已对准，告诉同伴继续调节。'):'寻找最清晰的位置，越过后反向微调。';
 $('radio-partner').textContent=s.partnerGood?'同伴信号已对准':'同伴正在寻找信号';document.querySelector('.radio-knob i').style.transform='rotate('+(s.value*2.7-135)+'deg)';
 var c=$('radio-wave').getContext('2d');c.clearRect(0,0,600,300);c.strokeStyle='#557477';c.lineWidth=1;for(var x=0;x<600;x+=30){c.beginPath();c.moveTo(x,0);c.lineTo(x,300);c.stroke();}for(var y=0;y<300;y+=30){c.beginPath();c.moveTo(0,y);c.lineTo(600,y);c.stroke();}c.strokeStyle=w==='A'?'#91e0e8':'#ffce85';c.lineWidth=4;c.beginPath();var t=performance.now()/500;for(var i=0;i<600;i++){var noise=(1-s.quality)*(Math.sin(i*1.71+t)*28+Math.sin(i*.33-t)*30)+(s.noise?Math.sin(i*.81+t)*35:0);var yy=150+Math.sin(i*.035+t)*55+noise;if(i===0)c.moveTo(i,yy);else c.lineTo(i,yy);}c.stroke();
}
function host(){clearTimers();clean();S.mod='dial';window._dead=false;shell('A');var s=make();active=s;var last=performance.now(),next=0,end=0;draw(snap(s,'A'),'A');var iv=setInterval(function(){if(active!==s){clearInterval(iv);return;}var now=performance.now(),dt=Math.min(.06,(now-last)/1000);last=now;['A','B'].forEach(function(w){if(now-s.seen[w]>650)s.inputs[w]=0;});step(s,dt);S.time=Math.ceil(s.time);if(now>=next){draw(snap(s,'A'),'A');netSend({t:'radioState',state:snap(s,'B')});next=now+66;}if(s.done){if(!end)end=now+1500;if(window._dungeon&&now>=end){var win=s.win;clearTimers();dungeonEnd(win);}else if(!window._dungeon&&s.againA&&s.againB)host();}},16);timers.push(iv);}
function guest(){var dg=window._dungeon;clearTimers();clean();S.mod='dial';window._dead=false;shell('B');if(!dg&&PEER.conn&&!PEER.conn._radioListener){PEER.conn._radioListener=function(d){dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._radioListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};var or=render;render=function(){if(S.mod==='dial'){if(!S.role)return renderPickRole();return S.role==='A'?renderHost():renderJoin();}return or();};
var oh=startHostGame;startHostGame=function(){return S.mod==='dial'?host():oh();};var og=renderGuestUI;renderGuestUI=function(code){return S.mod==='dial'?guest():og(code);};var op=renderPlayDungeonHost;renderPlayDungeonHost=function(){return S.mod==='dial'?host():op();};var om=renderManual;renderManual=function(){return S.mod==='dial'?(window._dungeon?guest():renderJoin()):om();};
var hd=dgHostOnData;dgHostOnData=function(d){if(d.t==='radioInput'||d.t==='radioReady')return input(d,'B');if(d.t==='radioAgain'){if(active&&active.done&&active.id===d.id)active.againB=true;return;}return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(d.t==='radioState'){if(S.mod!=='dial'||!$('radio-wave'))return;if(view&&view.id!==d.state.id)guest();draw(d.state,'B');return;}return gd(d);};
window.RadioScenes=window.RadioScenes||{};window.RadioMobile={create:make,step:step,snapshot:snap,state:function(){return active||view;}};
})();
