/* 默数开灯: standalone cooperative search, host-authoritative rhythm and collision. */
(function(){
'use strict';
var MODE='lightsearch',active=null,view=null,who='A',serial=0,sequence=0,ticket=0,loop=null,release=null,held='none',lastRevision=-1,lastRound=0,stopped=false,context=null,settled=false;
var DIRECTIONS={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0],none:[0,0]};
var META={id:MODE,name:'默数开灯',icon:'💡',tag:'默契搜索',time:null,a:'默数约 10 秒，拉一下灯绳。踩准节奏，房间亮 10 秒；拉错后按新的起拍重新默数。',b:'趁灯亮记住房间，沿通道寻找配电箱。走到旁边，亲手扳下总开关。暗处也能慢慢移动。'};
var GRID=['#########','#.......#','#..##...#','#.......#','###.##..#','#.......#','#..##.###','#.......#','#..##...#','#.......#','#########'];
var FURNITURE=[{x:3,y:2,w:2,h:1,type:'shelf',label:'书柜'},{x:1,y:4,w:2,h:1,type:'sofa',label:'沙发'},{x:4,y:4,w:2,h:1,type:'desk',label:'工作台'},{x:3,y:6,w:2,h:1,type:'shelf',label:'书柜'},{x:6,y:6,w:2,h:1,type:'sofa',label:'沙发'},{x:3,y:8,w:2,h:1,type:'desk',label:'矮柜'}];
function create(now,round){var options=[[7,1],[1,1],[7,5]],target=options[Math.floor(Math.random()*options.length)];return {id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),round:round||1,revision:0,ready:{A:false,B:false},started:false,done:false,win:false,again:{A:false,B:false},seq:{A:0,B:0},anchor:null,brightUntil:0,missed:false,cueUntil:0,event:0,feedback:'',pullAt:-Infinity,player:{x:1,y:9},dir:'none',moveAt:now,lease:0,map:GRID.slice(),objects:[{id:'main',x:target[0],y:target[1],type:'switch',label:'配电箱'},{id:'box',x:1,y:7,type:'box',label:'收纳箱'},{id:'plant',x:5,y:5,type:'plant',label:'绿植'}],bMessage:'沿通道找配电箱，走到旁边才能操作。',facing:'up',last:{x:1,y:9},interacted:false};}
function light(s,now){return s.done&&s.win||s.started&&now<s.brightUntil;}
function nearObject(s){return s.objects.find(function(o){return Math.abs(o.x-s.player.x)+Math.abs(o.y-s.player.y)<=1;})||null;}
function readable(s,x,y,now){return light(s,now)||Math.hypot(x-s.player.x,y-s.player.y)<=1.7;}
function snapshot(s,role,now){var out={theme:s.theme||'',mode:MODE,protocol:1,id:s.id,round:s.round,revision:s.revision,ready:{A:s.ready.A,B:s.ready.B},started:s.started,done:s.done,win:s.win,again:{A:s.again.A,B:s.again.B},lit:light(s,now)};
 if(role==='A'){out.cue=s.started&&now<s.cueUntil;out.event=s.event;out.feedback=s.feedback;}
 else {out.player={x:s.player.x,y:s.player.y};out.facing=s.facing;out.dir=s.dir;out.message=s.bMessage;out.interacted=s.interacted;out.cells=[];out.objects=[];out.furniture=[];if(s.started){for(var y=0;y<s.map.length;y++)for(var x=0;x<s.map[y].length;x++)if(readable(s,x,y,now))out.cells.push({x:x,y:y,wall:s.map[y][x]==='#'});out.objects=s.objects.filter(function(o){return readable(s,o.x,o.y,now);}).map(function(o){return Object.assign({},o);});out.furniture=FURNITURE.filter(function(f){for(var y=f.y;y<f.y+f.h;y++)for(var x=f.x;x<f.x+f.w;x++)if(readable(s,x,y,now))return true;return false;}).map(function(f){return Object.assign({},f);});var obj=nearObject(s);out.near=obj?{id:obj.id,label:obj.label,type:obj.type}:null;}else out.near=null;}
 return out;
}
function resetBeat(s,now,reason){s.anchor=now;s.brightUntil=0;s.cueUntil=now+1400;s.feedback=reason+' · 从现在重新默数';s.event++;}
function step(s,now){if(!s.started||s.done)return;if(!s.missed&&now-s.anchor>10000+(s.beatWindow||1500)){resetBeat(s,now,'错过窗口了');s.missed=true;}
 if(now>s.lease)s.dir='none';if(s.dir==='none'||now<s.moveAt)return;var d=DIRECTIONS[s.dir],nx=s.player.x+d[0],ny=s.player.y+d[1];s.facing=s.dir;s.moveAt=now+(light(s,now)?180:300);
 if(ny<0||nx<0||ny>=s.map.length||nx>=s.map[0].length||s.map[ny][nx]==='#'){s.bMessage='前面走不通，换个方向。';return;}s.last={x:s.player.x,y:s.player.y};s.player={x:nx,y:ny};var obj=nearObject(s);s.bMessage=obj?(obj.type==='switch'?'配电箱就在身边，试着扳下总开关。':'靠近'+obj.label+'，可以查看。'):'已向'+({up:'上',down:'下',left:'左',right:'右'}[s.dir])+'移动一格。';}
function input(s,d,role,now){if(role!=='A'&&role!=='B')return false;if(!s||!d||d.t!=='lsAction'||d.id!==s.id||!Number.isSafeInteger(d.seq)||d.seq<=s.seq[role]||d.seq>s.seq[role]+256||d.seq>1e9)return false;
 var allowed=role==='A'?['ready','pull','again']:['ready','move','interact','again'];if(allowed.indexOf(d.action)<0)return false;if(d.action==='move'&&!Object.prototype.hasOwnProperty.call(DIRECTIONS,d.value))return false;
 if(d.action==='again'){if(!s.done)return false;s.seq[role]=d.seq;s.again[role]=true;return true;}if(s.done)return false;
 if(d.action==='ready'){if(s.started)return false;s.seq[role]=d.seq;s.ready[role]=true;if(s.ready.A&&s.ready.B){s.started=true;s.anchor=now;s.cueUntil=now+1600;s.event++;s.feedback='现在起拍 · 在心里默数';s.moveAt=now;s.bMessage='行动开始。寻找配电箱，A 正在控制灯光。';}return true;}
 if(!s.started)return false;s.seq[role]=d.seq;
 if(d.action==='pull'){if(now-s.pullAt<220)return false;s.pullAt=now;var delta=now-s.anchor;if(delta>=10000-(s.beatWindow||1500)&&delta<=10000+(s.beatWindow||1500)){s.brightUntil=now+10000;s.anchor=now;s.missed=false;s.cueUntil=0;s.feedback='拉对了，灯亮了 · 继续默数';s.event++;}else{resetBeat(s,now,delta<8500?'早了':'晚了');s.missed=false;}return true;}
 if(d.action==='move'){if(d.value!==s.dir)s.moveAt=now;s.dir=d.value;s.lease=now+650;step(s,now);return true;}
 if(d.action==='interact'){var obj=nearObject(s);if(!obj)return false;if(obj.type==='switch'){s.done=s.win=true;s.dir='none';s.bMessage='总开关已合上，房间恢复照明！';s.feedback='同伴打开了总开关！';}else{s.interacted=true;s.bMessage=obj.type==='box'?'箱里只有旧工具，总开关不在这里。':'这是一盆绿植，继续找墙边的配电箱。';}return true;}return false;
}
function cleanup(){if(loop){clearInterval(loop);loop=null;}if(release){release();release=null;}active=null;view=null;held='none';sequence=0;lastRevision=-1;lastRound=0;ticket++;context=null;settled=false;}
function act(action,value){if(stopped||context&&!context.isActive())return;var s=who==='A'?active:view;if(!s)return;var d={t:'lsAction',id:s.id,seq:++sequence,action:action,value:value,sessionId:context?context.sessionId:null};if(who==='A')input(active,d,'A',performance.now());else netSend(d);}
function motion(dir){held=dir;act('move',dir);}
function stop(reason){if(stopped)return;stopped=true;if(active)active.dir='none';held='none';if(loop){clearInterval(loop);loop=null;}if(release){release();release=null;}if(view)view.stopped=true;var msg=$('ls-message');if(msg)msg.textContent=reason;document.querySelectorAll('.ls-game button:not(#ls-back)').forEach(function(b){b.disabled=true;});var head=$('ls-heading');if(head)head.textContent='连接已停止';}
function leave(){if(context){var ctx=context;clearTimers();if(ctx.isActive()&&PEER.conn&&PEER.conn.open)ctx.abort();else{S.mod='dungeon';renderDungeonMenu();}return;}netSend({t:'lsBye'});clearTimers();closePeer();location.search='';}
function shell(role){who=role;stopped=false;clearNetZones();window._keys={};window.onkeydown=window.onkeyup=null;window._mazeMove=null;
 $('app').innerHTML='<main class="ls-game" data-role="'+role+'"><header class="ls-header"><button id="ls-back" aria-label="返回">‹</button><strong>默数开灯</strong><span>'+role+' · '+(role==='A'?'灯控员':'搜索员')+'</span></header><section class="ls-intro"><h1 id="ls-heading">读懂规则再准备</h1><p>'+(role==='A'?'在心里默数约 10 秒，拉一下灯绳。':'趁亮灯看清房间，走到配电箱旁边。')+'</p><details><summary>玩法说明</summary><p>'+(role==='A'?'双方准备后会给一次起拍。从起拍或上次拉动开始，默数约 10 秒再拉。拉对就亮 10 秒，太早、太晚或漏拉会变暗；失误后按新起拍重新默数。不会显示倒计时。':'按方向在房间内移动，家具挡路时换条通道。亮时看全图，暗时只有脚边一点光。找到配电箱后，走近并扳下总开关。普通物件也可以走近查看。')+'</p></details></section><section class="ls-arena">'+(role==='A'?'<div class="ls-lamp-art" aria-hidden="true"><svg viewBox="0 0 320 260"><path class="ls-cord" d="M160 0v72"/><path class="ls-shade" d="M119 72h82l34 55H85z"/><path class="ls-glow" d="M90 133h140l48 95H42z"/><path class="ls-cord" d="M245 94v98"/><circle class="ls-handle" cx="245" cy="205" r="13"/></svg></div><div id="ls-cue" role="status"></div><p id="ls-light-state"></p>':'<canvas id="ls-map" width="540" height="660" aria-label="搜索房间：方向按钮移动，靠近配电箱操作"></canvas><div id="ls-wait-map">双方准备后进入房间</div>')+'</section><p id="ls-message" role="status">等待同伴准备。</p><footer class="ls-controls"><button id="ls-ready" class="ls-primary">我准备好了</button><p id="ls-partner"></p>'+(role==='A'?'<button id="ls-pull" class="ls-primary" disabled>拉一下灯绳</button>':'<button id="ls-interact" disabled>靠近物件后查看</button><div class="ls-dpad"><button data-ls-dir="up" aria-label="向上移动">↑ 上</button><button data-ls-dir="left" aria-label="向左移动">← 左</button><button data-ls-dir="down" aria-label="向下移动">↓ 下</button><button data-ls-dir="right" aria-label="向右移动">右 →</button></div>')+'<button id="ls-again" class="ls-primary" hidden>再来一局</button></footer></main>';
 $('ls-back').onclick=leave;$('ls-ready').onclick=function(){act('ready');};$('ls-again').onclick=function(){act('again');};
 if(role==='A')$('ls-pull').onclick=function(){act('pull');};else{$('ls-interact').onclick=function(){act('interact');};document.querySelectorAll('[data-ls-dir]').forEach(function(b){b.onpointerdown=function(e){if(b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);motion(b.dataset.lsDir);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=function(){motion('none');};});$('ls-map').onclick=function(e){if(!view||!view.near)return;var r=this.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*9),y=Math.floor((e.clientY-r.top)/r.height*11);var object=view.objects.find(function(o){return o.id===view.near.id;});if(object&&object.x===x&&object.y===y)act('interact');};}
 function keydown(e){if(e.repeat||stopped||e.ctrlKey||e.altKey||e.metaKey||/INPUT|TEXTAREA|SUMMARY/.test(e.target.tagName))return;if(role==='A'&&e.target.tagName!=='BUTTON'&&(e.code==='Space'||e.code==='Enter')){e.preventDefault();if(!$('ls-pull').disabled)act('pull');}var map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',KeyW:'up',KeyS:'down',KeyA:'left',KeyD:'right'};if(role==='B'&&map[e.code]){e.preventDefault();if(view&&view.started&&!view.done)motion(map[e.code]);}if(role==='B'&&e.code==='KeyE'){e.preventDefault();act('interact');}}
 function keyup(e){if(role==='B'&&/^(Arrow|Key[WASD])/.test(e.code))motion('none');}function blur(){if(role==='B')motion('none');}function hidden(){if(document.hidden)blur();}
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);var heartbeat=setInterval(function(){if(role==='B'&&held!=='none'&&!document.hidden)motion(held);},180);
 var conn=PEER.conn;function close(){stop('同伴已断开，行动停止。请返回重新建房。');}if(conn)conn.on('close',close);
 release=function(){clearInterval(heartbeat);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);if(conn&&conn.off){conn.off('close',close);conn.off('data',packet);}};
}
function tileIcon(c,o,u){var x=(o.x+.5)*u,y=(o.y+.5)*u;c.save();c.translate(x,y);c.lineWidth=2;c.strokeStyle='#25374c';if(o.type==='switch'){c.fillStyle='#d6eee6';c.fillRect(-u*.34,-u*.36,u*.68,u*.72);c.strokeRect(-u*.34,-u*.36,u*.68,u*.72);c.fillStyle='#14786a';c.fillRect(-u*.15,-u*.2,u*.3,u*.4);c.strokeStyle='#fff';c.lineWidth=4;c.beginPath();c.moveTo(0,u*.15);c.lineTo(u*.1,-u*.16);c.stroke();}else if(o.type==='box'){c.fillStyle='#b79b8b';c.fillRect(-u*.32,-u*.28,u*.64,u*.56);c.strokeRect(-u*.32,-u*.28,u*.64,u*.56);c.beginPath();c.moveTo(-u*.32,0);c.lineTo(u*.32,0);c.stroke();}else{c.fillStyle='#678b73';[-.2,0,.2].forEach(function(dx){c.beginPath();c.ellipse(dx*u,-u*.16,u*.13,u*.25,dx*3,0,Math.PI*2);c.fill();});c.fillStyle='#9b8cac';c.fillRect(-u*.17,u*.1,u*.34,u*.25);}c.restore();}
function scene(s){var canvas=$('ls-map'),c=canvas.getContext('2d'),u=60;c.fillStyle='#101b2c';c.fillRect(0,0,540,660);if(!s.started)return;
 c.save();if(!s.lit){c.beginPath();c.arc((s.player.x+.5)*u,(s.player.y+.5)*u,u*1.7,0,Math.PI*2);c.clip();}
 s.cells.forEach(function(t){c.fillStyle=t.wall?(s.theme==='ghost'?'#43445e':'#40516b'):(s.theme==='ghost'?'#c6d4e0':'#dbe6ed');c.fillRect(t.x*u,t.y*u,u,u);c.strokeStyle=t.wall?'#52637b':'#c4d2df';c.lineWidth=1;c.strokeRect(t.x*u+.5,t.y*u+.5,u-1,u-1);});
 s.furniture.forEach(function(f){c.fillStyle=f.type==='sofa'?'#7d86ad':f.type==='desk'?'#9c9eaa':'#768ca3';c.fillRect(f.x*u+5,f.y*u+5,f.w*u-10,f.h*u-10);c.strokeStyle='#3a4b63';c.lineWidth=3;c.strokeRect(f.x*u+5,f.y*u+5,f.w*u-10,f.h*u-10);if(f.type==='shelf'){for(var i=15;i<f.w*u-12;i+=13){c.strokeStyle=i%2?'#bdd7dd':'#ced4df';c.beginPath();c.moveTo(f.x*u+i,f.y*u+15);c.lineTo(f.x*u+i,f.y*u+32);c.stroke();}}else{c.strokeStyle='#c2cad8';c.beginPath();c.moveTo(f.x*u+15,f.y*u+18);c.lineTo((f.x+f.w)*u-15,f.y*u+18);c.stroke();}c.font='24px sans-serif';c.textAlign='center';c.fillStyle='#102335';c.fillText(f.label,(f.x+f.w/2)*u,(f.y+.8)*u);});
 if(s.theme==='ghost'){c.save();c.translate(7.5*u,3.5*u);c.fillStyle='#e8edf5';c.beginPath();c.moveTo(-18,22);c.lineTo(-18,-4);c.arc(0,-4,18,Math.PI,0);c.lineTo(18,22);c.lineTo(6,15);c.lineTo(0,22);c.lineTo(-6,15);c.closePath();c.fill();c.fillStyle='#43445e';c.fillRect(-9,-5,5,7);c.fillRect(4,-5,5,7);c.restore();}
 s.objects.forEach(function(o){tileIcon(c,o,u);if(s.near&&o.id===s.near.id){c.strokeStyle='#087b70';c.lineWidth=4;c.strokeRect(o.x*u+3,o.y*u+3,u-6,u-6);}});
 var x=(s.player.x+.5)*u,y=(s.player.y+.5)*u;c.fillStyle='#147c93';c.strokeStyle='#ffffff';c.lineWidth=3;c.beginPath();c.arc(x,y,u*.23,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#fff';c.textAlign='center';c.textBaseline='middle';c.font='bold 18px sans-serif';c.fillText('B',x,y+1);c.restore();
}
function draw(s){if(!$('ls-heading'))return;view=s;var root=document.querySelector('.ls-game');root.dataset.theme=s.theme||'';root.querySelector('.ls-header strong').textContent=s.theme==='ghost'?'幽宅灯控':'默数开灯';root.dataset.lit=s.lit?'true':'false';root.dataset.phase=s.done?'done':s.started?'play':'ready';
 $('ls-heading').textContent=s.done?'房间亮起来了':!s.started?'先读规则，再准备':who==='A'?'默数后，拉一下':s.lit?'灯亮了，记住房间':'借着微光继续找';
 $('ls-ready').hidden=s.started||s.done;$('ls-ready').disabled=s.ready[who];$('ls-ready').textContent=s.ready[who]?'已准备':'我准备好了';$('ls-partner').textContent=s.done?'双方点击，再玩一次':!s.started?(s.ready[who==='A'?'B':'A']?'同伴已准备':'等待同伴准备'):'';
 $('ls-again').hidden=!s.done||!!context;if(context&&s.done)$('ls-partner').textContent='搜索完成，返回地图';$('ls-again').disabled=s.again[who];$('ls-again').textContent=s.again[who]?'已准备，等待同伴':'再来一局';
 if(who==='A'){$('ls-pull').hidden=!s.started||s.done;$('ls-pull').disabled=!s.started||s.done;$('ls-cue').textContent=s.cue?'现在起拍':'';$('ls-light-state').textContent=s.done?'总开关已合上':s.lit?'房间亮着':s.started?'房间只有微光':'灯绳由你控制';$('ls-message').textContent=s.done?s.feedback:!s.started?'准备好后，会给一次起拍提示。':s.feedback;}
 if(s.theme==='ghost'&&!s.started){document.querySelector('.ls-intro>p').textContent=who==='A'?'替同伴守住幽宅灯光，默数约 10 秒再拉绳。':'女鬼在等你。借灯光找配电箱，让幽宅恢复照明。';}
 if(who==='B'){$('ls-wait-map').hidden=s.started;$('ls-interact').hidden=!s.started||s.done;$('ls-interact').disabled=!s.started||s.done||!s.near;$('ls-interact').textContent=s.near?(s.near.type==='switch'?'扳下总开关':'查看'+s.near.label):'靠近物件后查看';document.querySelectorAll('[data-ls-dir]').forEach(function(b){b.disabled=!s.started||s.done;b.setAttribute('aria-pressed',s.dir===b.dataset.lsDir?'true':'false');});document.querySelector('.ls-dpad').hidden=!s.started||s.done;$('ls-message').textContent=s.started?s.message:'A 控制灯光，你负责在房间里搜索。';scene(s);}
}
function packet(d){if(!d||typeof d!=='object'||stopped)return;if(context&&(!context.isActive()||d.sessionId!==context.sessionId))return;if(d.t==='lsBye'){stop('同伴离开了房间，行动停止。');return;}if(who==='A'){if(d.t==='lsAction')input(active,d,'B',performance.now());return;}
 if(d.t!=='lsState'||!d.state)return;var s=d.state;if(s.mode!==MODE||s.protocol!==1||!Number.isSafeInteger(s.round)||s.round<lastRound||!Number.isSafeInteger(s.revision))return;if(s.round===lastRound&&(s.revision<=lastRevision||view&&view.id!==s.id))return;if(s.round>lastRound){sequence=0;held='none';lastRound=s.round;lastRevision=-1;}lastRevision=s.revision;draw(s);
}
function start(role,ctx){clearTimers();context=ctx||null;settled=false;who=role;stopped=false;lastRound=0;lastRevision=-1;shell(role);if(!ctx)PEER.conn.on('data',packet);if(role==='A'){active=create(performance.now(),++serial);active.theme=ctx&&ctx.roomId==='room-2'?'ghost':'';active.beatWindow=[1500,1200,900,700][Math.max(0,Math.min(3,(ctx?ctx.tier:1)-1))];loop=setInterval(function(){if(!active||stopped)return;if(ctx&&!ctx.isActive()){cleanup();return;}var now=performance.now();step(active,now);active.revision++;draw(snapshot(active,'A',now));netSend({t:'lsState',sessionId:ctx?ctx.sessionId:null,state:snapshot(active,'B',now)});if(ctx&&active.done&&!settled){settled=true;var win=active.win;clearTimers();ctx.finish(win);return;}if(!ctx&&active.done&&active.again.A&&active.again.B){active=create(now,++serial);sequence=0;}},50);draw(snapshot(active,'A',performance.now()));}}
window.RoomGameAdapters=window.RoomGameAdapters||{};window.RoomGameAdapters[MODE]={host:function(ctx){start('A',ctx);},guest:function(ctx){start('B',ctx);}};
var oldHostData=dgHostOnData;dgHostOnData=function(d){if(d&&/^ls/.test(d.t)){if(context&&who==='A')packet(d);return;}return oldHostData.apply(this,arguments);};
var oldGuestData=dgGuestOnData;dgGuestOnData=function(d){if(d&&/^ls/.test(d.t)){if(context&&who==='B')packet(d);return;}return oldGuestData.apply(this,arguments);};

function lobby(role){clearTimers();closePeer();S.mod=MODE;S.role=role;who=role;stopped=false;window._dungeon=false;window._netMode=role==='A'?'host':'guest';var current=++ticket;
 $('app').innerHTML='<main class="ls-game" data-role="'+role+'"><header class="ls-header"><button id="ls-back" aria-label="返回">‹</button><strong>默数开灯</strong><span>'+role+'</span></header><h1>'+(role==='A'?'创建房间':'加入房间')+'</h1><p>'+META[role.toLowerCase()]+'</p>'+(role==='B'?'<label for="ls-code">A 的四位房间码</label><input id="ls-code" inputmode="numeric" maxlength="4" autocomplete="off"><button id="ls-join" class="ls-primary">加入房间</button>':'')+'<p id="ls-status" role="status">'+(role==='A'?'正在创建房间…':'输入房间码后加入')+'</p></main>';$('ls-back').onclick=leave;
 function status(message){if(ticket===current&&$('ls-status'))$('ls-status').textContent=message;}
 function connect(code){loadPeerLib(function(P){if(current!==ticket)return;if(!P){status('联网组件未能加载，请返回重试。');return;}var p=newPeerId(role==='A'?'lightsearch-'+code:null,peerOpts()),joined=false,pending=false;PEER.peer=p;PEER.room=code;PEER.isHost=role==='A';var timeout=setTimeout(function(){if(!joined&&current===ticket){status('找不到默数开灯房间，请核对房间码和玩法后返回重试。');p.destroy();}},18000);timers.push(timeout);
 function opened(c){if(current!==ticket){c.close();return;}joined=true;clearTimeout(timeout);PEER.conn=c;start(role);}
 function handshake(c){if(current!==ticket){c.close();return;}var accepted=false,limit=setTimeout(function(){if(!accepted){status('玩法握手未完成，请确认双方都是默数开灯并返回重试。');c.close();pending=false;}},6000);timers.push(limit);
 function receive(d){if(current!==ticket||accepted)return;var expected=role==='A'?'lsHello':'lsWelcome';if(!d||d.t!==expected||d.mode!==MODE||d.protocol!==1){clearTimeout(limit);c.off('data',receive);if(role==='A')c.send({t:'lsReject',mode:MODE,protocol:1});status('双方玩法或版本不一致，请重新进入默数开灯。');pending=false;setTimeout(function(){c.close();},80);return;}accepted=true;clearTimeout(limit);c.off('data',receive);if(role==='A')c.send({t:'lsWelcome',mode:MODE,protocol:1});opened(c);}
 c.on('data',receive);c.on('close',function(){clearTimeout(limit);if(!accepted&&current===ticket){pending=false;status('入房未完成：请核对玩法和版本后重试。');}});if(role==='B')c.send({t:'lsHello',mode:MODE,protocol:1});}
 p.on('open',function(){if(current!==ticket){p.destroy();return;}if(role==='A'){clearTimeout(timeout);status('默数开灯房间码：'+code+' · 等待 B 加入');}else{var c=p.connect('lightsearch-'+code,{reliable:true,metadata:{mode:MODE,protocol:1}});c.on('open',function(){handshake(c);});}});
 p.on('connection',function(c){if(role!=='A'||joined||pending){c.close();return;}if(!c.metadata||c.metadata.mode!==MODE||c.metadata.protocol!==1){c.on('open',function(){c.send({t:'lsReject',mode:MODE,protocol:1});setTimeout(function(){c.close();},80);});return;}pending=true;c.on('open',function(){handshake(c);});});
 p.on('error',function(e){clearTimeout(timeout);status(e&&e.type==='peer-unavailable'?'找不到默数开灯房间：请核对四位码，确认 A 也在这个玩法。':'连接失败，请返回重试。');});
 });}
 if(role==='A')connect(1000+Math.floor(Math.random()*9000));else $('ls-join').onclick=function(){var code=$('ls-code').value;if(!/^\d{4}$/.test(code)){status('请输入四位数字。');return;}this.disabled=true;connect(code);};
}
function choose(){clearTimers();closePeer();$('app').innerHTML='<main class="ls-game"><header class="ls-header"><button id="ls-back" aria-label="返回">‹</button><strong>默数开灯</strong></header><h1>一人控灯，一人搜索</h1><p>灯光是你们的暗号。开语音，用两台设备合作。</p><section class="ls-choice"><h2>A · 灯控员</h2><p>'+META.a+'</p><button id="ls-host" class="ls-primary">创建房间</button><h2>B · 搜索员</h2><p>'+META.b+'</p><button id="ls-guest" class="ls-primary">加入房间</button></section></main>';$('ls-back').onclick=leave;$('ls-host').onclick=function(){lobby('A');};$('ls-guest').onclick=function(){lobby('B');};}
if(!PLAYGROUNDS.some(function(p){return p.id===MODE;}))PLAYGROUNDS.push(META);
var originalClear=clearTimers;clearTimers=function(){cleanup();return originalClear.apply(this,arguments);};var originalRender=render;render=function(){if(S.mod===MODE)return S.role?lobby(S.role):choose();return originalRender.apply(this,arguments);};
window.RhythmLight={create:create,input:input,step:step,snapshot:snapshot,state:function(){return view;}};
})();

