(function(g){
'use strict';
let active=null,developer=false,selected='room-1',tier=1,epoch=0;
const originalSend=netSend;
function current(){return active?Object.freeze({...active.meta}):null;}
function send(payload){if(active&&PEER.conn?.open)PEER.conn.send({t:'directData',runId:active.meta.runId,payload});}
netSend=function(payload){if(active)return send(payload);return originalSend(payload);};
function stop(){epoch++;if(active){active.ended=true;active.controller?.abort();active.lease?.release();}active=null;clearTimers();RoomResults.close();}
function room(){return ROOM_CATALOG.find(r=>r.id===selected);}
function button(label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;return b;}
function shell(title){const app=document.getElementById('app');app.replaceChildren();const panel=document.createElement('main');panel.className='direct-room';const h=document.createElement('h1');h.textContent=title;panel.append(h);app.append(panel);return panel;}
function lobby(){stop();closePeer();try{localStorage.setItem('roomlab-last-view','lobby');}catch(_){}
 const app=document.getElementById('app');app.innerHTML='<section class="room-select"><h1 class="room-title" id="room-title"></h1><div class="room-carousel"><button class="room-arrow prev" id="room-prev" aria-label="上一间">❮</button><img id="room-cover" class="room-cover" alt="密室封面"><button class="room-arrow next" id="room-next" aria-label="下一间">❯</button></div><div class="room-info" id="room-info"></div><p class="room-pagination" id="room-pagination"></p><div class="room-actions"><button class="room-action create" id="dm2">创建房间<small>角色 A · 选择难度</small></button><button class="room-action join" id="dm3">加入房间<small>角色 B · 跟随同伴</small></button></div></section>';
 const page=app.firstElementChild;function paint(r){selected=r.id;document.getElementById('room-title').textContent=r.theme+' | '+r.name;const info=document.getElementById('room-info');info.replaceChildren();for(const [cls,text]of [['room-recommend','['+r.recommend+']'],['room-meta',(r.rating?r.rating+'分 | ':'')+r.minutes+'分钟 | 2人开场'],['room-tag',r.difficulty],['room-tag',r.tag]]){const el=document.createElement('span');el.className=cls;el.textContent=text;info.append(el);}document.getElementById('room-pagination').textContent=(RoomDirectory.plans.findIndex(x=>x.roomId===r.id)+1)+' / 17';}
 const rooms=RoomDirectory.plans.map(p=>ROOM_CATALOG.find(r=>r.id===p.roomId));const covers=RoomCoverLoader.mount({root:page,image:document.getElementById('room-cover'),rooms,initialId:selected,onReady:paint});document.getElementById('room-prev').onclick=()=>covers.move(-1);document.getElementById('room-next').onclick=()=>covers.move(1);let x=0;page.onpointerdown=e=>x=e.clientX;page.onpointerup=e=>{if(Math.abs(e.clientX-x)>50)covers.move(e.clientX<x?1:-1);};document.getElementById('dm2').onclick=()=>levels(selected);document.getElementById('dm3').onclick=join;
}
function levels(id=selected){stop();selected=id;const r=room();if(!r)return lobby();try{localStorage.setItem('roomlab-last-room',id);localStorage.setItem('roomlab-last-view','levels');}catch(_){}const p=shell(r.name),plan=RoomDirectory.getPlan(id);const name=document.createElement('p');name.textContent=plan.title;p.append(name);const state=RoomLevelProgress.status(id,developer);state.labels.forEach((label,i)=>p.append(button(label+(i+1>state.unlockedThrough?' · 未解锁':''),()=>{tier=i+1;try{localStorage.setItem('roomlab-last-tier',String(tier));}catch(_){}host();},i+1>state.unlockedThrough)));p.append(button('加入同伴',join),button('返回密室',lobby));}
function fail(message){stop();closePeer();const p=shell(message);p.append(button('返回难度选择',()=>levels()));}
async function begin(meta,role){
 if(!meta||meta.protocol!==1||typeof meta.runId!=='string'||!meta.runId||!RoomDirectory.getPlan(meta.roomId)||RoomDirectory.getPlan(meta.roomId).primary!==meta.mode||!Number.isInteger(meta.tier)||meta.tier<1||meta.tier>5)return false;
 stop();selected=meta.roomId;tier=meta.tier;const boundConnection=PEER.conn;const runDeveloper=role==='A'?developer:meta.developer===true;const s=active={meta:Object.freeze({...meta,role,developer:runDeveloper}),ended:false};S.mod=meta.mode;S.role=role;g._dungeon=false;g._dgNode=null;g._netMode=role==='A'?'host':'guest';
 const ctx={...s.meta,sessionId:meta.runId,tutorial:meta.tier===1,isActive:()=>active===s&&!s.ended&&PEER.conn===boundConnection&&!!boundConnection?.open,send:payload=>{if(active!==s||s.ended||PEER.conn!==boundConnection||!boundConnection?.open)return false;boundConnection.send({t:'directData',runId:s.meta.runId,payload});return true;},finish:data=>role==='A'&&active===s&&!s.ended?RoomResults.report(data):false,abort:()=>fail('本局已结束')};
 const save=r=>{if(r.win)RoomLevelProgress.complete({roomId:meta.roomId,tier:meta.tier,resultId:r.resultId,win:true,developer:runDeveloper});};
 RoomResults.begin({runId:meta.runId,role,connection:PEER.conn,gameId:meta.mode,title:RoomDirectory.getPlan(meta.roomId).title,roomTitle:room().name,roomSession:s.meta,developer:runDeveloper,tutorial:meta.tier===1,onResult:save,apply:data=>{if(data.win)save({win:true,resultId:meta.runId+':result'});},onContinue:()=>levels(meta.roomId),onExit:()=>{closePeer();levels(meta.roomId);}});
 s.controller=new AbortController();try{s.lease=await RoomAssets.prepare(RoomAssets.manifest(['room:'+meta.roomId,'mode:'+meta.mode]),{signal:s.controller.signal});}catch(e){if(active===s)fail('素材未加载完成，请返回重试');return false;}if(!ctx.isActive())return false;
 const adapter=RoomGameAdapters[meta.mode];if(!adapter?.[role==='A'?'host':'guest']){fail('该玩法正在接入，请稍后重试');return false;}adapter[role==='A'?'host':'guest'](ctx);return true;
}
function bind(conn,role,meta){PEER.conn=conn;let offered=false;conn.on('data',async d=>{if(PEER.conn!==conn)return;if(d&&['roomResult','roomResultAck','roomResultAdvance'].includes(d.t)){RoomResults.consume(d,conn);return;}if(d?.t==='directOffer'&&role==='B'){if(active||offered)return;offered=true;if(await begin(d.meta,'B'))conn.send({t:'directReady',runId:d.meta.runId});return;}if(d?.t==='directReady'&&role==='A'&&d.runId===meta.runId&&!active){begin(meta,'A');return;}if(d?.t!=='directData'||!active||d.runId!==active.meta.runId)return;const payload=d.payload;if(RoomResults.consume(payload,conn))return;(role==='A'?dgHostOnData:dgGuestOnData)(payload);});conn.on('close',()=>{if(active&&PEER.conn===conn)fail('同伴已断开连接');});if(role==='A')conn.send({t:'directOffer',meta});}
function host(){if(!RoomLevelProgress.canPlay(selected,tier,developer))return levels();closePeer();const token=++epoch,p=shell('创建房间'),text=document.createElement('p');text.textContent='连接中…';p.append(text,button('返回',()=>{epoch++;closePeer();levels();}));loadPeerLib(lib=>{if(token!==epoch)return;if(!lib)return fail('联网组件加载失败');const code=String(Math.floor(1000+Math.random()*9000)),peer=newPeerId('direct'+code,peerOpts());PEER.peer=peer;PEER.room=code;PEER.isHost=true;peer.on('open',()=>text.textContent='房间码：'+code);peer.on('error',()=>fail('连接失败，请重新创建'));peer.on('connection',conn=>{if(PEER.conn?.open){conn.close();return;}conn.on('open',()=>bind(conn,'A',{protocol:1,roomId:selected,mode:RoomDirectory.getPlan(selected).primary,tier,developer,runId:crypto.randomUUID()}));});});}
function join(){closePeer();const p=shell('加入同伴'),input=document.createElement('input');input.inputMode='numeric';input.maxLength=4;input.placeholder='四位房间码';p.append(input,button('加入',()=>{if(!/^\d{4}$/.test(input.value))return;loadPeerLib(lib=>{if(!lib)return fail('联网组件加载失败');const peer=newPeerId(undefined,peerOpts());PEER.peer=peer;PEER.isHost=false;peer.on('open',()=>{const conn=peer.connect('direct'+input.value,{reliable:true});conn.on('open',()=>bind(conn,'B'));});peer.on('error',()=>fail('加入失败，请检查房间码'));});}),button('返回',()=>levels()));}
function boot(){for(const r of ROOM_CATALOG)RoomAssets.register('room:'+r.id,[{src:'assets/rooms/webp/'+r.id+'.webp',fallback:r.image}]);try{const saved=localStorage.getItem('roomlab-last-room');if(RoomDirectory.getPlan(saved))selected=saved;const storedTier=Number(localStorage.getItem('roomlab-last-tier'));if(Number.isInteger(storedTier)&&storedTier>=1&&storedTier<=5)tier=storedTier;if(localStorage.getItem('roomlab-last-view')==='levels'){levels(selected);return;}}catch(_){}lobby();}
g.RoomSession=Object.freeze({current,boot,lobby,levels,send,setDeveloper:value=>{if(active)throw Error('Cannot change access during a run');developer=!!value;},begin});
})(window);
