/* A controls the reveal; B submits a private recording. Host owns attempts. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',draft=[],focus=0,draftKey='',serial=0,resultTerminal=null,lastResultRound=0;
function config(tier){tier=Math.max(1,Math.min(4,tier||1));return {tier:tier,count:[4,7,6,3][tier-1],chances:tier<3?3:2,kind:tier===4?'math':tier===3?'mixed':'digits',flash:tier===4?2:1.2,limit:tier===4?35:null};}
function photoRoom(){return !!(window._dungeon&&typeof DUNGEON!=='undefined'&&DUNGEON&&DUNGEON.roomId==='room-18');}
function make(tier){var cfg=config(tier),answer=[],clues=[],alphabet='23456789ACDEFHJKLMNPRTUVWXY';for(var i=0;i<cfg.count;i++){if(cfg.kind==='math'){var a=2+Math.floor(Math.random()*8),b=2+Math.floor(Math.random()*8),mul=Math.random()<.5;clues.push(a+(mul?' × ':' + ')+b);answer.push(String(mul?a*b:a+b));}else{var n=cfg.kind==='mixed'?alphabet[Math.floor(Math.random()*alphabet.length)]:String(Math.floor(Math.random()*10));clues.push(n);answer.push(n);}}if(cfg.kind==='mixed'){clues[0]=answer[0]='ACDEFHJKLMNPRTUVWXY'[Math.floor(Math.random()*18)];clues[1]=answer[1]=String(2+Math.floor(Math.random()*8));}return {theme:photoRoom()?'photos':'',id:Date.now().toString(36)+'-'+(++serial),runSerial:serial,durationMs:0,cfg:cfg,answer:answer,clues:clues,left:cfg.chances,attempt:0,phase:'read',elapsed:0,time:null,done:false,win:false,msg:'先阅读规则。两人商量好后，由 A 开始扫描。',againA:false,againB:false};}
function snap(s,who){var out={theme:s.theme||'',id:s.id,runSerial:s.runSerial,cfg:s.cfg,left:s.left,attempt:s.attempt,phase:s.phase,time:s.time,done:s.done,win:s.win,msg:s.msg};if(who==='A'&&s.phase==='show'){var i=Math.floor(s.elapsed/s.cfg.flash);out.index=s.order[i];out.clue=s.clues[out.index];}return out;}
function lose(s,why){if(s.done)return;s.left--;s.time=null;s.phase=s.left>0?'read':'result';s.msg=why+(s.left>0?' 本轮机会已扣除，A 可准备后重新扫描。':' 机会已用完。');if(!s.left){s.done=true;s.win=false;}}
function begin(s){if(s.phase!=='read'||s.done)return;s.attempt++;s.elapsed=0;s.time=null;s.order=Array.from({length:s.cfg.count},function(_,i){return i;});for(var i=s.order.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),v=s.order[i];s.order[i]=s.order[j];s.order[j]=v;}s.phase='show';s.msg='扫描中：仔细观察，B 可以边听边记录。';}
function step(s,dt){if(s.done)return;if(s.phase==='show'||s.phase==='write')s.durationMs+=dt*1000;if(s.phase==='show'){s.elapsed+=dt;if(s.elapsed>=s.cfg.count*s.cfg.flash){s.phase='write';s.time=s.cfg.limit;s.msg=s.cfg.kind==='math'?'扫描结束，B 计算并填写每道题的答案。':'扫描结束，B 检查记录后提交；不计时。';}}else if(s.phase==='write'&&s.time!==null){s.time=Math.max(0,s.time-dt);if(s.time===0)lose(s,'答题超时。');}}
function input(d,who){var s=active;if(!s||d.id!==s.id)return;if(d.t==='vmAgain'&&s.done){s[who==='A'?'againA':'againB']=true;return;}if(s.done||d.attempt!==s.attempt)return;if(who==='A'&&d.t==='vmBegin')begin(s);else if(who==='A'&&d.t==='vmRetry'&&s.phase==='write')lose(s,'A 选择重新看。');else if(who==='B'&&d.t==='vmSubmit'&&s.phase==='write'){if(!Array.isArray(d.code)||d.code.length!==s.cfg.count||!d.code.every(function(x){return typeof x==='string'&&/^[A-Z0-9]{1,2}$/.test(x);}))return;if(d.code.every(function(x,i){return x===s.answer[i];})){s.done=true;s.win=true;s.phase='result';s.msg='档案解锁，机密到手！';}else lose(s,'记录不符（无论 A 报错或 B 写错，共扣 1 次）。');}}
function action(t,code){var s=role==='A'?active:view;if(!s)return;var d={t:t,id:s.id,attempt:s.attempt,code:code};if(role==='A')input(d,'A');else netSend(d);}
function clean(){resultTerminal=null;if(dispose)dispose();dispose=null;active=null;view=null;draftKey='';}
function shell(who){role=who;clearNetZones();window._mazeMove=null;window._keys={};window.onkeydown=window.onkeyup=null;
 $('app').innerHTML='<section class="vm-shell" data-role="'+who+'"><header class="vm-top"><button id="back" aria-label="返回">‹</button><strong>档案窃取</strong><span class="vm-role">'+who+' · '+(who==='A'?'观察员':'记录员')+'</span></header><div class="vm-status"><span id="vm-mode"></span><b id="vm-lives">等待连接</b></div><main class="vm-main"><div class="vm-intro"><h1 id="vm-heading">正在连接</h1><p id="vm-instruction"></p></div><details class="vm-help"><summary>玩法说明</summary><p id="vm-rules"></p></details><div id="vm-display"></div><p id="msg" role="status"></p></main><footer class="vm-controls" id="vm-controls"></footer></section>';
 $('back').onclick=function(){if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 var conn=PEER.conn;function disconnect(){clean();window._dead=true;if($('msg'))$('msg').textContent='连接断开，行动停止。请返回重新建房。';document.querySelectorAll('.vm-controls button,.vm-slot').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnect);
 function key(e){if(who!=='B'||!view||!['show','write'].includes(view.phase)||e.ctrlKey||e.metaKey||e.altKey)return;if(/^[a-z0-9]$/i.test(e.key)){e.preventDefault();write(e.key.toUpperCase());}else if(e.key==='Backspace'){e.preventDefault();erase();}else if(e.key==='Enter'&&!$('vm-submit').disabled){e.preventDefault();action('vmSubmit',draft.slice());}}
 window.addEventListener('keydown',key);dispose=function(){window.removeEventListener('keydown',key);if(conn&&conn.off)conn.off('close',disconnect);};
}
function write(n){if(!view||!['show','write'].includes(view.phase))return;if(view.cfg.kind!=='mixed'&&!/^\d$/.test(n))return;if(view.cfg.kind==='mixed'&&!/^[0-9ACDEFHJKLMNPRTUVWXY]$/.test(n))return;if(view.cfg.kind==='math'){draft[focus]=(draft[focus]+n).slice(-2);}else{draft[focus]=n;focus=Math.min(draft.length-1,focus+1);}record();}
function erase(){if(!view||!['show','write'].includes(view.phase))return;if(!draft[focus]&&focus>0)focus--;draft[focus]=draft[focus].slice(0,-1);record();}
function record(){document.querySelectorAll('.vm-slot').forEach(function(b,i){b.classList.toggle('on',i===focus);b.classList.toggle('filled',!!draft[i]);b.setAttribute('aria-pressed',i===focus?'true':'false');b.querySelector('strong').textContent=draft[i]||'—';});var submit=$('vm-submit');if(submit){var missing=draft.filter(function(n){return !n;}).length;submit.disabled=!view||view.phase!=='write'||missing>0;$('vm-input-hint').textContent=missing?'还差 '+missing+' 项'+(view.cfg.kind==='math'?' · 可输入两位数':''):view.phase==='show'?'记录已填满，扫描结束后提交':'记录已填满，请核对后提交';}}
function emblem(type){return '<svg class="vm-emblem" viewBox="0 0 80 80" fill="none" aria-hidden="true">'+(type==='win'?'<circle cx="40" cy="40" r="31"/><path d="m24 41 11 11 22-24"/>':type==='lose'?'<circle cx="40" cy="40" r="31"/><path d="m29 29 22 22m0-22L29 51"/>':'<path d="M18 13h30l14 14v40H18zM48 13v16h14M29 43h22M29 53h14"/>')+'</svg>';}
function keypad(kind){var pad=$('vm-keys'),chars=kind==='letters'?'ACDEFHJKLMNPRTUVWXY':'1234567890';pad.className='vm-keypad '+(kind==='letters'?'letters':'');pad.innerHTML=chars.split('').map(function(n){return '<button data-char="'+n+'">'+n+'</button>';}).join('')+'<button id="vm-delete" aria-label="删除一位">⌫</button>'+(kind==='letters'?'':'<button id="vm-next">下一格 →</button>');pad.querySelectorAll('[data-char]').forEach(function(b){b.onclick=function(){write(b.dataset.char);};});$('vm-delete').onclick=erase;if($('vm-next'))$('vm-next').onclick=function(){focus=(focus+1)%draft.length;record();};document.querySelectorAll('[data-keyboard]').forEach(function(b){b.setAttribute('aria-pressed',b.dataset.keyboard===kind?'true':'false');});}
function observationSlots(s){return '<div class="vm-observation" style="--columns:'+s.cfg.count+'" aria-label="档案观察格">'+Array.from({length:s.cfg.count},function(_,i){return '<div class="vm-observation-slot" data-observation="'+i+'"><strong>—</strong></div>';}).join('')+'</div><p class="vm-observation-hint">'+(s.phase==='read'?'开始后，内容会在对应格里逐一亮起':s.phase==='show'?'仅 A 可见 · 每次只显示一格':'内容已隐藏，等待 B 提交记录')+'</p>';}
function draw(s,who){if(!$('vm-display'))return;view=s;var root=document.querySelector('.vm-shell');root.dataset.theme=s.theme||'';root.querySelector('.vm-top strong').textContent=s.theme==='photos'?'旧照片档案':'档案窃取';root.dataset.phase=s.phase;root.dataset.kind=s.cfg.kind;root.dataset.outcome=s.done?(s.win?'win':'lose'):'';
 $('vm-lives').textContent='机会 '+s.left+' / '+s.cfg.chances;$('vm-mode').textContent=s.cfg.kind==='math'?s.cfg.count+' 道算式':s.cfg.count+' 位'+(s.cfg.kind==='mixed'?'数字 + 字母':'数字');
 var title=s.done?(s.win?'档案已解锁':'机会用完了'):s.phase==='read'?(who==='A'?'准备好再开始':'等 A 开始扫描'):s.phase==='show'?(who==='A'?'看清后，报给 B':'听同伴，记内容'):(who==='A'?'交给 B 核对':'核对后提交');
 $('vm-heading').textContent=title;$('vm-instruction').textContent=s.done?(s.win?'配合成功，机密已拿到。':'重新商量报数节奏，再试一次。'):s.phase==='read'?(who==='A'?'你负责看和报，B 负责记录。':'开始后，点击对应格子输入。'):s.phase==='show'?(who==='A'?'看清亮起的内容，告诉 B。':'点选格子可以修改记录。'):(who==='A'?'档案已隐藏，不用抢时间。':s.cfg.kind==='math'?'填写计算结果 · 剩余 '+Math.ceil(s.time)+' 秒':'确认每一位都记对，再提交。');
 if(who==='A'&&s.phase==='write'&&s.cfg.kind==='math')$('vm-instruction').textContent='B 正在计算 · 剩余 '+Math.ceil(s.time)+' 秒';
 $('vm-rules').textContent=(s.cfg.kind==='math'?'A 看算式，每题显示 2 秒；B 填计算结果，扫描后有 35 秒答题。':'内容随机逐格亮起，每格显示 1.2 秒；B 可边听边填，普通记忆不计时。')+'双方共享 '+s.cfg.chances+' 次机会。提交错误或主动重新看，每轮扣 1 次。';
 $('msg').textContent=s.phase==='read'&&s.attempt?s.msg:'';$('msg').hidden=!$('msg').textContent;
 var k=s.id+':'+s.attempt+':'+s.phase+':'+who;if(draftKey!==k){var reset=!draftKey.startsWith(s.id+':'+s.attempt+':');draftKey=k;var display=$('vm-display'),controls=$('vm-controls');var selectedBank=controls.querySelector('[data-keyboard][aria-pressed="true"]');var bank=!reset&&selectedBank?selectedBank.dataset.keyboard:'digits';controls.innerHTML='';document.querySelector('.vm-help').open=false;
 if(s.done&&window.RoomResults){display.innerHTML='';controls.innerHTML='';}
 else if(s.done){display.innerHTML='<div class="vm-result">'+emblem(s.win?'win':'lose')+'<span>'+(s.win?'本次合作完成':'本次合作结束')+'</span></div>';controls.innerHTML=window._dungeon?'<span>即将返回地图</span>':'<button id="vm-again" class="vm-primary">再来一局</button><span>双方点击后开始新一局</span>';if($('vm-again'))$('vm-again').onclick=function(){action('vmAgain');this.disabled=true;this.textContent='已准备，等待同伴';};}
 else if(who==='A'){
 display.innerHTML=observationSlots(s);
 if(s.phase==='read'){controls.innerHTML='<button id="vm-start" class="vm-primary">'+(s.attempt?'开始下一次扫描':'开始扫描')+'</button><span>确认 B 能听到你，再开始</span>';$('vm-start').onclick=function(){action('vmBegin');};}
 else if(s.phase==='write'){controls.innerHTML='<button id="vm-retry" class="vm-secondary">没记住？重新看</button><span>会消耗 1 次机会</span>';$('vm-retry').onclick=function(){controls.innerHTML='<div class="vm-confirm"><strong>'+(s.left===1?'这是最后一次机会':'重新看会扣 1 次机会')+'</strong><p>'+(s.left===1?'放弃后，本局将结束。':'当前记录会在下一次扫描时清空。')+'</p><div><button id="vm-cancel">继续等 B</button><button id="vm-confirm-retry">'+(s.left===1?'放弃本局':'确认重新看')+'</button></div></div>';$('vm-confirm-retry').onclick=function(){action('vmRetry');};$('vm-cancel').onclick=function(){draftKey='';draw(s,who);};};}
 }else{
 if(reset){draft=Array(s.cfg.count).fill('');focus=0;}
 if(s.phase==='read'){display.innerHTML='<div class="vm-slots" style="--columns:'+s.cfg.count+'">'+draft.map(function(_,i){return '<button class="vm-slot" disabled aria-label="记录格"><strong>—</strong></button>';}).join('')+'</div>';controls.innerHTML='<div class="vm-wait"><i></i>等待 A 点击开始</div>';}
 else{display.innerHTML='<div class="vm-slots" style="--columns:'+s.cfg.count+'">'+draft.map(function(_,i){return '<button class="vm-slot" data-i="'+i+'" aria-label="第 '+(i+1)+' 位"><strong>—</strong></button>';}).join('')+'</div><p id="vm-input-hint"></p>';display.querySelectorAll('button').forEach(function(b){b.onclick=function(){focus=+b.dataset.i;record();};});controls.innerHTML=(s.cfg.kind==='mixed'?'<div class="vm-keyboard-tabs"><button data-keyboard="digits">数字 123</button><button data-keyboard="letters">字母 ABC</button></div>':'')+'<div id="vm-keys"></div><button id="vm-submit" class="vm-primary" disabled>提交记录</button>';controls.querySelectorAll('[data-keyboard]').forEach(function(b){b.onclick=function(){keypad(b.dataset.keyboard);};});keypad(bank);$('vm-submit').onclick=function(){action('vmSubmit',draft.slice());};record();}
 }
 }
 if(s.theme==='photos'){if(s.done){$('vm-heading').textContent=s.win?'旧照片已归档':'回忆机会用完了';$('vm-instruction').textContent=s.win?'你们一起补全了照片背面的记录。':'商量好报数节奏，再整理这些回忆。';}else if(s.phase==='read'){$('vm-heading').textContent=who==='A'?'准备翻看旧照片':'等 A 翻开照片';$('vm-instruction').textContent=who==='A'?'看清照片背面的内容，告诉 B。':'听同伴描述，在空格中记录。';}var start=$('vm-start');if(start)start.textContent=s.attempt?'再次翻看照片':'开始翻看照片';var hint=document.querySelector('.vm-observation-hint');if(hint)hint.textContent=s.phase==='read'?'翻开后，照片背面的编号会逐一显现':s.phase==='show'?'每次翻开一张 · 看清后告诉同伴':'照片已收起，等待 B 核对记录';}
 if(who==='A'){document.querySelectorAll('.vm-observation-slot').forEach(function(cell,i){var shown=s.phase==='show'&&i===s.index;cell.classList.toggle('is-revealed',shown);cell.querySelector('strong').textContent=shown?s.clue:'—';});}else record();
}
function beginResult(s,who){if(window._dungeon||!window.RoomResults)return;RoomResults.begin({runId:s.id,role:who,connection:PEER.conn,gameId:'vault',title:'档案窃取',dungeon:null,onContinue:function(){if(who==='A')host();},onExit:function(){clearTimers();closePeer();location.search='';}});}
function resultData(s){var metrics={durationMs:s.durationMs,mistakesRemaining:s.left,maxMistakes:s.cfg.chances,goal:s.cfg.count};if(s.win)metrics.completed=s.cfg.count;if(s.time!==null)metrics.timeLeftMs=s.time*1000;return{win:s.win,reasonCode:s.win?'completed':'attempts_exhausted',reason:s.win?'记录核对正确，档案已解锁。':'看写机会已耗尽。',metrics:metrics};}
function host(){clearTimers();clean();resultTerminal=null;S.mod='vault';window._dead=false;shell('A');var s=make(typeof coopDifficulty==='function'?coopDifficulty().tier:1);active=s;beginResult(s,'A');var resultContext=window._dungeon?window._roomGameContext:null;var last=performance.now(),reported=false,iv;function tick(){if(active!==s||reported)return;var now=performance.now();step(s,Math.max(0,(now-last)/1000));last=now;draw(snap(s,'A'),'A');netSend({t:'vmState',state:snap(s,'B')});if(s.done){reported=true;window._dead=true;resultTerminal=snap(s,'A');clearInterval(iv);if(resultContext)resultContext.finish(resultData(s));else if(window.RoomResults)RoomResults.report(resultData(s));}}iv=setInterval(tick,70);timers.push(iv);tick();}
function guest(){resultTerminal=null;lastResultRound=0;var dungeon=window._dungeon;clearTimers();clean();S.mod='vault';window._dead=false;shell('B');if(!dungeon&&PEER.conn&&!PEER.conn._vaultMobileListener){var bound=PEER.conn;PEER.conn._vaultMobileListener=function(d){if(PEER.conn!==bound)return;if(window.RoomResults&&RoomResults.consume(d,bound))return;dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._vaultMobileListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};
var op=renderPlay;renderPlay=function(){if(S.mod==='vault')return renderHost();return op.apply(this,arguments);};
var om=renderManual;renderManual=function(){if(S.mod==='vault')return window._dungeon?guest():renderJoin();return om.apply(this,arguments);};renderVaultManual=function(){return window._dungeon?guest():renderJoin();};
var od=renderPlayDungeonHost;renderPlayDungeonHost=function(){if(S.mod==='vault')return host();return od.apply(this,arguments);};
var oh=startHostGame;startHostGame=function(){if(S.mod==='vault')return host();return oh.apply(this,arguments);};
var og=renderGuestUI;renderGuestUI=function(){if(S.mod==='vault')return guest();return og.apply(this,arguments);};
var hd=dgHostOnData;dgHostOnData=function(d){if(/^vm(Begin|Retry|Submit|Again)$/.test(d.t)){input(d,'B');return;}return hd(d);};
var gd=dgGuestOnData;dgGuestOnData=function(d){if(d.t==='vmState'){if(S.mod!=='vault'||!$('vm-display'))return;if(!Number.isSafeInteger(d.state.runSerial)||d.state.runSerial<lastResultRound)return;if(d.state.runSerial===lastResultRound&&view&&view.id!==d.state.id)return;lastResultRound=d.state.runSerial;beginResult(d.state,'B');draw(d.state,'B');if(d.state.done)resultTerminal=d.state;return;}return gd(d);};
window.VaultMobile={create:make,step:step,snapshot:snap,begin:begin,state:function(){return active||view||resultTerminal;}};
})();
