/* A controls the reveal; B submits a private recording. Host owns attempts. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',draft=[],focus=0,draftKey='',serial=0;
function config(tier){tier=Math.max(1,Math.min(4,tier||1));return {tier:tier,count:[5,7,6,3][tier-1],chances:tier<3?3:2,kind:tier===4?'math':tier===3?'mixed':'digits',flash:tier===4?2:1.2,limit:tier===4?35:null};}
function make(tier){var cfg=config(tier),answer=[],clues=[],alphabet='23456789ACDEFHJKLMNPRTUVWXY';for(var i=0;i<cfg.count;i++){if(cfg.kind==='math'){var a=2+Math.floor(Math.random()*8),b=2+Math.floor(Math.random()*8),mul=Math.random()<.5;clues.push(a+(mul?' × ':' + ')+b);answer.push(String(mul?a*b:a+b));}else{var n=cfg.kind==='mixed'?alphabet[Math.floor(Math.random()*alphabet.length)]:String(Math.floor(Math.random()*10));clues.push(n);answer.push(n);}}if(cfg.kind==='mixed'){clues[0]=answer[0]='ACDEFHJKLMNPRTUVWXY'[Math.floor(Math.random()*18)];clues[1]=answer[1]=String(2+Math.floor(Math.random()*8));}return {id:Date.now().toString(36)+'-'+(++serial),cfg:cfg,answer:answer,clues:clues,left:cfg.chances,attempt:0,phase:'read',elapsed:0,time:null,done:false,win:false,msg:'先阅读规则。两人商量好后，由 A 开始扫描。',againA:false,againB:false};}
function snap(s,who){var out={id:s.id,cfg:s.cfg,left:s.left,attempt:s.attempt,phase:s.phase,time:s.time,done:s.done,win:s.win,msg:s.msg};if(who==='A'&&s.phase==='show'){var i=Math.floor(s.elapsed/s.cfg.flash);out.index=s.order[i];out.clue=s.clues[out.index];}return out;}
function lose(s,why){if(s.done)return;s.left--;s.time=null;s.phase=s.left>0?'read':'result';s.msg=why+(s.left>0?' 本轮机会已扣除，A 可准备后重新扫描。':' 机会已用完。');if(!s.left){s.done=true;s.win=false;}}
function begin(s){if(s.phase!=='read'||s.done)return;s.attempt++;s.elapsed=0;s.time=null;s.order=Array.from({length:s.cfg.count},function(_,i){return i;});for(var i=s.order.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),v=s.order[i];s.order[i]=s.order[j];s.order[j]=v;}s.phase='show';s.msg='扫描中：A 报位序和内容，B 可以边听边记录。';}
function step(s,dt){if(s.done)return;if(s.phase==='show'){s.elapsed+=dt;if(s.elapsed>=s.cfg.count*s.cfg.flash){s.phase='write';s.time=s.cfg.limit;s.msg=s.cfg.kind==='math'?'扫描结束，B 计算并填写每道题的答案。':'扫描结束，B 检查记录后提交；不计时。';}}else if(s.phase==='write'&&s.time!==null){s.time=Math.max(0,s.time-dt);if(s.time===0)lose(s,'答题超时。');}}
function input(d,who){var s=active;if(!s||d.id!==s.id)return;if(d.t==='vmAgain'&&s.done){s[who==='A'?'againA':'againB']=true;return;}if(s.done||d.attempt!==s.attempt)return;if(who==='A'&&d.t==='vmBegin')begin(s);else if(who==='A'&&d.t==='vmRetry'&&s.phase==='write')lose(s,'A 选择重新看。');else if(who==='B'&&d.t==='vmSubmit'&&s.phase==='write'){if(!Array.isArray(d.code)||d.code.length!==s.cfg.count||!d.code.every(function(x){return typeof x==='string'&&/^[A-Z0-9]{1,2}$/.test(x);}))return;if(d.code.every(function(x,i){return x===s.answer[i];})){s.done=true;s.win=true;s.phase='result';s.msg='档案解锁，机密到手！';}else lose(s,'记录不符（无论 A 报错或 B 写错，共扣 1 次）。');}}
function action(t,code){var s=role==='A'?active:view;if(!s)return;var d={t:t,id:s.id,attempt:s.attempt,code:code};if(role==='A')input(d,'A');else netSend(d);}
function clean(){if(dispose)dispose();dispose=null;active=null;view=null;draftKey='';}
function shell(who){role=who;clearNetZones();window._mazeMove=null;window._keys={};window.onkeydown=window.onkeyup=null;
 $('app').innerHTML='<section class="vm-shell"><header class="vm-top"><button id="back" aria-label="返回">‹</button><strong>档案窃取</strong><span class="vm-role '+who+'">'+who+' · '+(who==='A'?'观察员':'记录员')+'</span></header><div class="vm-status"><b id="vm-lives">等待连接</b><span id="vm-mode"></span></div><section class="vm-card"><h2 id="vm-heading">阅读行动规则</h2><p id="vm-rules"></p><div id="vm-display"></div></section><p id="msg" role="status">等待同伴…</p><footer class="vm-controls" id="vm-controls"></footer></section>';
 $('back').onclick=function(){if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 var conn=PEER.conn;function disconnect(){clean();window._dead=true;if($('msg'))$('msg').textContent='连接断开，行动停止。请返回重新建房。';document.querySelectorAll('.vm-controls button,.vm-slot').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnect);
 function key(e){if(who!=='B'||!view||!['show','write'].includes(view.phase)||e.ctrlKey||e.metaKey||e.altKey)return;if(/^[a-z0-9]$/i.test(e.key)){e.preventDefault();write(e.key.toUpperCase());}else if(e.key==='Backspace'){e.preventDefault();erase();}else if(e.key==='Enter'&&!$('vm-submit').disabled){e.preventDefault();action('vmSubmit',draft.slice());}}
 window.addEventListener('keydown',key);dispose=function(){window.removeEventListener('keydown',key);if(conn&&conn.off)conn.off('close',disconnect);};
}
function write(n){if(!view||!['show','write'].includes(view.phase))return;if(view.cfg.kind!=='mixed'&&!/^\d$/.test(n))return;if(view.cfg.kind==='mixed'&&!/^[0-9ACDEFHJKLMNPRTUVWXY]$/.test(n))return;if(view.cfg.kind==='math'){draft[focus]=(draft[focus]+n).slice(-2);}else{draft[focus]=n;focus=Math.min(draft.length-1,focus+1);}record();}
function erase(){if(!view||!['show','write'].includes(view.phase))return;if(!draft[focus]&&focus>0)focus--;draft[focus]=draft[focus].slice(0,-1);record();}
function record(){document.querySelectorAll('.vm-slot').forEach(function(b,i){b.classList.toggle('on',i===focus);b.querySelector('strong').textContent=draft[i]||'·';});var submit=$('vm-submit');if(submit)submit.disabled=!view||view.phase!=='write'||draft.some(function(n){return !n;});}
function draw(s,who){if(!$('vm-display'))return;view=s;$('vm-lives').textContent='剩余机会 '+s.left+' / '+s.cfg.chances;$('vm-mode').textContent=s.cfg.kind==='math'?'算术 · '+s.cfg.count+' 题':s.cfg.count+' 位 · '+(s.cfg.kind==='mixed'?'数字＋字母':'数字');
 $('vm-heading').textContent=s.done?(s.win?'行动成功':'行动失败'):s.phase==='read'?'先读规则，再开始':s.phase==='show'?'扫描进行中':s.cfg.kind==='math'?'答题剩余 '+Math.ceil(s.time)+' 秒':'核对记录 · 不计时';
 $('vm-rules').textContent=(who==='A'?'你看档案，报「第几位、什么内容」。':'你听 A 报位序，点对应格子填写。')+(s.cfg.kind==='math'?'每题显示 2 秒，B 填计算结果；扫描后限时 35 秒。':'每位显示 1.2 秒，扫描后可慢慢核对。')+'双方共享机会，提交错误或重新看均扣 1 次。';$('msg').textContent=s.msg;
 var k=s.id+':'+s.attempt+':'+s.phase+':'+who;if(draftKey!==k){var reset=!draftKey.startsWith(s.id+':'+s.attempt+':');draftKey=k;var display=$('vm-display'),controls=$('vm-controls');controls.innerHTML='';
 if(who==='A'){display.innerHTML='<div class="vm-reveal"><small id="vm-index"></small><strong id="vm-clue"></strong></div>';if(s.phase==='read'){controls.innerHTML='<button id="vm-start" class="vm-primary A">'+(s.attempt?'准备好了 · 再看一次':'我准备好了 · 开始扫描')+'</button>'; $('vm-start').onclick=function(){action('vmBegin');};}else if(s.phase==='write'){controls.innerHTML='<button id="vm-retry" class="vm-secondary">没记住 · 重新看（扣 1 次）</button><span>等待 B 核对并提交</span>';if(s.left===1)$('vm-retry').textContent='放弃本轮（最后 1 次机会）';$('vm-retry').onclick=function(){action('vmRetry');};}}
 else{if(reset){draft=Array(s.cfg.count).fill('');focus=0;}display.innerHTML='<div class="vm-slots" style="grid-template-columns:repeat('+(s.cfg.count===5?5:s.cfg.count===7?4:3)+',minmax(0,1fr))">'+draft.map(function(_,i){return '<button class="vm-slot" data-i="'+i+'" aria-label="第 '+(i+1)+' 位"><small>'+(s.cfg.kind==='math'?'题 ':'位 ')+(i+1)+'</small><strong>·</strong></button>';}).join('')+'</div>';display.querySelectorAll('button').forEach(function(b){b.onclick=function(){focus=+b.dataset.i;record();};});
 if(['show','write'].includes(s.phase)){var chars=s.cfg.kind==='mixed'?'1234567890ACDEFHJKLMNPRTUVWXY':'1234567890';controls.innerHTML='<div class="vm-keypad '+(s.cfg.kind==='mixed'?'mixed':'')+'">'+chars.split('').map(function(n){return '<button data-char="'+n+'">'+n+'</button>';}).join('')+'<button id="vm-delete" aria-label="删除">⌫</button><button id="vm-next">下一格</button></div><button id="vm-submit" class="vm-primary B" disabled>核对完毕 · 提交</button>';controls.querySelectorAll('[data-char]').forEach(function(b){b.onclick=function(){write(b.dataset.char);};});$('vm-delete').onclick=erase;$('vm-next').onclick=function(){focus=(focus+1)%draft.length;record();};$('vm-submit').onclick=function(){action('vmSubmit',draft.slice());};}else if(!s.done)controls.innerHTML='<div class="vm-wait">等待 A 点击开始<br><small>不用准备按钮，开始后直接记录</small></div>';record();}
 if(s.done){controls.innerHTML=window._dungeon?'<span>即将返回地图</span>':'<button id="vm-again" class="vm-primary '+who+'">再来一局</button><span>双方都点击后重新开始</span>';if($('vm-again'))$('vm-again').onclick=function(){action('vmAgain');this.disabled=true;this.textContent='等待同伴重开';};}}
 if(who==='A'){$('vm-index').textContent=s.phase==='show'?'第 '+(s.index+1)+(s.cfg.kind==='math'?' 题':' 位'):s.phase==='read'?'准备时间不限':'档案已隐藏';$('vm-clue').textContent=s.phase==='show'?s.clue:s.done?(s.win?'✓':'×'):'?';}else record();
}
function host(){clearTimers();clean();S.mod='vault';window._dead=false;shell('A');var s=make(typeof coopDifficulty==='function'?coopDifficulty().tier:1);active=s;var last=performance.now(),endAt=0;function tick(){if(active!==s)return;var now=performance.now();step(s,Math.max(0,(now-last)/1000));last=now;draw(snap(s,'A'),'A');netSend({t:'vmState',state:snap(s,'B')});if(s.done){window._dead=true;if(!endAt)endAt=now+1400;if(window._dungeon&&now>=endAt){var win=s.win;clearTimers();dungeonEnd(win);}else if(!window._dungeon&&s.againA&&s.againB)host();}}tick();timers.push(setInterval(tick,70));}
function guest(){var dungeon=window._dungeon;clearTimers();clean();S.mod='vault';window._dead=false;shell('B');if(!dungeon&&PEER.conn&&!PEER.conn._vaultMobileListener){PEER.conn._vaultMobileListener=function(d){dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._vaultMobileListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};
var op=renderPlay;renderPlay=function(){if(S.mod==='vault')return renderHost();return op.apply(this,arguments);};
var om=renderManual;renderManual=function(){if(S.mod==='vault')return window._dungeon?guest():renderJoin();return om.apply(this,arguments);};renderVaultManual=function(){return window._dungeon?guest():renderJoin();};
var od=renderPlayDungeonHost;renderPlayDungeonHost=function(){if(S.mod==='vault')return host();return od.apply(this,arguments);};
var oh=startHostGame;startHostGame=function(){if(S.mod==='vault')return host();return oh.apply(this,arguments);};
var og=renderGuestUI;renderGuestUI=function(){if(S.mod==='vault')return guest();return og.apply(this,arguments);};
var hd=dgHostOnData;dgHostOnData=function(d){if(/^vm(Begin|Retry|Submit|Again)$/.test(d.t)){input(d,'B');return;}return hd(d);};
var gd=dgGuestOnData;dgGuestOnData=function(d){if(d.t==='vmState'){if(S.mod!=='vault'||!$('vm-display'))return;if(view&&view.id!==d.state.id){guest();}draw(d.state,'B');return;}return gd(d);};
window.VaultMobile={create:make,step:step,snapshot:snap,begin:begin,state:function(){return active||view;}};
})();
