/* Stepwise asymmetric wire puzzle. Stable IDs, host-owned outcome and rescue. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',key='',selected=null,serial=0;
var colors=['红','蓝','黄'],textures=['实线','条纹','圆点'],symbols=['△','○','□'];
var metadata=PLAYGROUNDS.find(function(p){return p.id==='wires';});if(metadata){metadata.a='报线号、颜色、纹理；选线后确认剪断。剪后揭示灯色和接头，重新向 B 报信息。';metadata.b='每次只看当前一步规则，听现场特征判断线号。首次剪错时，听 A 报符号并选择旁路。';}
function make(tier){tier=Math.max(1,Math.min(4,tier||1));var count=[6,7,8,8][tier-1],w=[];for(var i=0;i<count;i++)w.push({id:i+1,color:colors[Math.floor(Math.random()*3)],texture:textures[Math.floor(Math.random()*3)],cut:false});return {id:Date.now().toString(36)+'-'+(++serial),tier:tier,wires:w,round:0,ready:{A:false,B:false},cd:3,time:typeof coopTime==='function'?coopTime(90):90,light:Math.random()<.5?'蓝':'黄',plug:Math.random()<.5?'△':'○',lastColor:null,rescue:null,rescueUsed:false,done:false,win:false,msg:'双方读完职责，准备后开始。',againA:false,againB:false};}
function choose(s){var live=s.wires.filter(function(w){return !w.cut;}),pool,high=false;
 if(s.round===0){pool=live.filter(function(w){return w.color==='红';});if(pool.length>=2)high=true;else{pool=live.filter(function(w){return w.color==='蓝';});if(!pool.length){pool=live;high=true;}}}
 else if(s.round===1){pool=live.filter(function(w){return w.texture===(s.light==='蓝'?'条纹':'圆点');});high=s.light!=='蓝';}
 else {pool=live.filter(function(w){return s.plug==='△'?w.color===s.lastColor:w.color!==s.lastColor;});high=s.plug!=='△';}
 if(!pool.length){pool=live;high=false;}return pool.reduce(function(a,b){return (high?b.id>a.id:b.id<a.id)?b:a;}).id;
}
function rules(round){return round===0?['先问 A：红线有几根？','红线至少 2 根 → 剪编号最大的红线。','否则，有蓝线 → 剪编号最小的蓝线。','红线不足 2 根且没有蓝线 → 剪编号最大的线。']:round===1?['先问 A：新亮的灯是什么颜色？','蓝灯 → 剪编号最小的条纹线。','黄灯 → 剪编号最大的圆点线。','没有这种纹理 → 剪编号最小的未剪线。']:['先问 A：接头形状、上一刀的线色。','△ 接头 → 剪与上一刀同色、编号最小的线。','○ 接头 → 剪与上一刀异色、编号最大的线。','没有符合条件的线 → 剪编号最小的未剪线。'];}
function snapshot(s,who){var out={id:s.id,round:s.round,ready:s.ready,cd:s.cd,time:s.time,rescueUsed:s.rescueUsed,done:s.done,win:s.win,msg:s.msg};if(s.rescue)out.rescue={left:s.rescue.left,held:s.rescue.held,symbol:who==='A'?s.rescue.symbol:undefined};if(who==='A'){out.wires=s.wires;out.light=s.round>=1?s.light:null;out.plug=s.round>=2?s.plug:null;out.lastColor=s.lastColor;}else out.rules=rules(s.round);return out;}
function finishGame(s,win,msg){s.done=true;s.win=win;s.msg=msg;s.rescue=null;}
function input(s,d,who){if(!s||d.id!==s.id)return;if(d.t==='wmAgain'&&s.done){s[who==='A'?'againA':'againB']=true;return;}if(s.done)return;if(d.t==='wmReady'){s.ready[who]=true;return;}if(d.round!==s.round||!s.ready.A||!s.ready.B||s.cd>0)return;
 if(s.rescue){if(who==='A'&&d.t==='wmHold'){s.rescue.held=!!d.v;s.rescue.seen=performance.now();}else if(who==='B'&&d.t==='wmBypass'){if(!s.rescue.held){s.msg='先让 A 按住断路开关，再选择旁路。';return;}if(d.symbol===s.rescue.symbol){s.rescue=null;s.msg='旁路接通，短路解除！重新判断，刚才的线还没有剪断。';}else finishGame(s,false,'旁路选择错误，警报触发。');}return;}
 if(who!=='A'||d.t!=='wmCut'||!Number.isInteger(d.wire))return;var wire=s.wires.find(function(w){return w.id===d.wire&&!w.cut;});if(!wire)return;
 if(wire.id!==choose(s)){if(s.rescueUsed){finishGame(s,false,'再次剪错，警报触发。');return;}s.rescueUsed=true;s.rescue={left:8,held:false,seen:0,symbol:symbols[Math.floor(Math.random()*symbols.length)]};s.msg='短路！A 按住断路开关并报符号，B 选择同形旁路。';return;}
 wire.cut=true;s.lastColor=wire.color;s.round++;if(s.round===3)finishGame(s,true,'三路警报已解除，拆线成功！');else s.msg=s.round===1?'第一刀完成，指示灯亮了！A 报灯色，B 查看第二步。':'第二刀完成，接头露出来了！A 报接头形状与上一刀线色。';
}
function step(s,dt){if(s.done||!s.ready.A||!s.ready.B)return;if(s.cd>0){s.cd=Math.max(0,s.cd-dt);return;}if(s.rescue){s.rescue.left-=dt;if(performance.now()-s.rescue.seen>650)s.rescue.held=false;if(s.rescue.left<=0)finishGame(s,false,'救场超时，警报触发。');return;}s.time=Math.max(0,s.time-dt);if(s.time===0)finishGame(s,false,'时间到，警报触发。');}
function clean(){if(dispose)dispose();dispose=null;active=null;view=null;key='';selected=null;}
function act(t,extra){var s=role==='A'?active:view;if(!s)return;var d=Object.assign({t:t,id:s.id,round:s.round},extra||{});if(role==='A')input(s,d,'A');else netSend(d);}
function shell(who){role=who;clearNetZones();window._wirePick=window._wireKey=window._mazeMove=null;window._keys={};window.onkeydown=window.onkeyup=null;
 $('app').innerHTML='<section class="wm-shell"><header class="wm-top"><button id="back" aria-label="返回">‹</button><strong>警报拆线</strong><span class="wm-role '+who+'">'+who+' · '+(who==='A'?'拆线员':'指挥员')+'</span></header><div class="wm-status"><b id="wm-progress">拆线 0 / 3</b><span id="count">准备中</span></div><section class="wm-panel"><h2 id="wm-title"></h2><p id="wm-duty"></p><div id="wm-clues"></div><div id="wm-content"></div></section><p id="msg" role="status"></p><footer id="wm-controls" class="wm-controls"></footer></section>';
 $('back').onclick=function(){if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 var held=false;function release(){if(held){held=false;act('wmHold',{v:false});}}function down(e){var b=e.target.closest('#wm-hold');if(!b||b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);held=true;act('wmHold',{v:true});}function keyboard(e){if(e.repeat)return;if(e.key===' '&&$('wm-hold')){e.preventDefault();held=true;act('wmHold',{v:true});}else if(e.key==='Enter'&&$('wm-cut')&&!$('wm-cut').disabled){e.preventDefault();$('wm-cut').click();}}
 function up(e){if(e.key===' ')release();}var el=document.querySelector('.wm-shell');el.addEventListener('pointerdown',down);el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('lostpointercapture',release);window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);window.addEventListener('keydown',keyboard);window.addEventListener('keyup',up);var heartbeat=setInterval(function(){if(held)act('wmHold',{v:true});},180),conn=PEER.conn;
 function disconnected(){clean();window._dead=true;if($('msg'))$('msg').textContent='连接断开，拆线已停止。请返回重新建房。';document.querySelectorAll('.wm-shell button:not(#back)').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnected);
 dispose=function(){clearInterval(heartbeat);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);window.removeEventListener('keydown',keyboard);window.removeEventListener('keyup',up);if(conn&&conn.off)conn.off('close',disconnected);};
}
function draw(s,who){if(!$('wm-content'))return;view=s;var waiting=!s.ready.A||!s.ready.B||s.cd>0;$('count').textContent=s.done?'已结束':!s.ready.A||!s.ready.B?'准备中':s.cd>0?Math.ceil(s.cd):s.rescue?'救场 '+Math.ceil(s.rescue.left)+'s':Math.ceil(s.time)+'s';$('wm-progress').textContent='拆线 '+Math.min(3,s.round)+' / 3';$('msg').textContent=s.msg;
 $('wm-title').textContent=s.done?(s.win?'解除成功':'警报触发'):s.rescue?'紧急旁路':waiting?'先确认分工':'第 '+(s.round+1)+' 刀 · '+['颜色数量','灯色与纹理','接头与上一刀'][s.round];$('wm-duty').textContent=who==='A'?'你看线板，向 B 报特征。点选线，再按下方按钮确认剪断；线号始终不变。':'你看当前规则，询问 A 现场特征，再报明确线号。每剪对一刀，规则自动更新。';
 var k=s.id+':'+s.round+':'+waiting+':'+!!s.rescue+':'+s.done;if(key!==k){key=k;selected=null;var content=$('wm-content'),controls=$('wm-controls');content.innerHTML='';controls.innerHTML='';$('wm-clues').innerHTML='';
 if(s.done){content.innerHTML='<div class="wm-result">'+(s.win?'✓':'!')+'</div>';controls.innerHTML=window._dungeon?'<span>即将返回地图</span>':'<button id="wm-again" class="wm-primary '+who+'">再来一局</button><span>双方都点击后重开</span>';if($('wm-again'))$('wm-again').onclick=function(){act('wmAgain');this.disabled=true;this.textContent='等待同伴';};}
 else if(s.rescue){content.innerHTML=who==='A'?'<div class="wm-fuse"><small>把这个符号报给 B</small><strong>'+s.rescue.symbol+'</strong></div>':'<div class="wm-rule">听 A 报符号，等 A 按住开关后，选择相同形状的旁路。选错会失败。</div>';controls.innerHTML=who==='A'?'<button id="wm-hold" class="wm-primary A">按住断路开关</button>':'<div class="wm-bypass">'+symbols.map(function(x){return '<button data-symbol="'+x+'">'+x+'</button>';}).join('')+'</div><span id="wm-hold-status"></span>';controls.querySelectorAll('[data-symbol]').forEach(function(b){b.onclick=function(){act('wmBypass',{symbol:b.dataset.symbol});};});}
 else {if(who==='A'){$('wm-clues').innerHTML='<span>指示灯：'+(s.light||'剪完第一刀揭示')+'</span><span>接头：'+(s.plug||'剪完第二刀揭示')+'</span>'+(s.lastColor?'<span>上一刀：'+s.lastColor+'线</span>':'');content.innerHTML='<div class="wm-board">'+s.wires.map(function(w){return '<button class="wm-wire '+(w.cut?'cut':'')+'" data-wire="'+w.id+'" '+(w.cut||waiting?'disabled':'')+' aria-label="'+w.id+'号 '+w.color+'色 '+w.texture+(w.cut?' 已剪断':'')+'"><b>'+w.id+'</b><i class="'+({红:'red',蓝:'blue',黄:'yellow'}[w.color])+' '+({实线:'solid',条纹:'stripe',圆点:'dot'}[w.texture])+'"></i><span>'+w.color+' · '+w.texture+(w.cut?' ✓':'')+'</span></button>';}).join('')+'</div>';content.querySelectorAll('[data-wire]').forEach(function(b){b.onclick=function(){selected=+b.dataset.wire;content.querySelectorAll('button').forEach(function(x){x.classList.toggle('selected',x===b);});$('wm-cut').disabled=false;$('wm-cut').textContent='确认剪断 '+selected+' 号线';};});if(!waiting){controls.innerHTML='<button id="wm-cut" class="wm-primary A" disabled>先点选一根线</button><span>'+(s.rescueUsed?'救场已使用，下次剪错将失败':'首次剪错可协作救场一次')+'</span>';$('wm-cut').onclick=function(){if(selected===null)return;act('wmCut',{wire:selected});selected=null;this.disabled=true;};}}
 else content.innerHTML='<ol class="wm-rules">'+s.rules.map(function(r){return '<li>'+r+'</li>';}).join('')+'</ol><div class="wm-rule-foot">只考虑未剪断的线 · 线号不重新排列</div>';
 if(waiting){controls.innerHTML='<button id="wm-ready" class="wm-primary '+who+'">我已读懂 · 准备好了</button><span id="wm-wait"></span>';$('wm-ready').onclick=function(){act('wmReady');};}else if(who==='B')controls.innerHTML='<div class="wm-command"><b>向 A 报：剪「几号线」</b><span>等 A 确认剪断后，查看新规则</span></div>';}
 }
 if($('wm-ready')){$('wm-ready').disabled=s.ready[who];$('wm-ready').textContent=s.ready[who]?'已准备':'我已读懂 · 准备好了';$('wm-wait').textContent=s.ready.A&&s.ready.B?'即将开始':'等待同伴准备';}if($('wm-hold-status'))$('wm-hold-status').textContent=s.rescue.held?'A 已按住 · 现在选择旁路':'等待 A 按住断路开关';if(s.rescue&&who==='B')document.querySelectorAll('[data-symbol]').forEach(function(b){b.disabled=!s.rescue.held;});
}
function host(){clearTimers();clean();S.mod='wires';window._dead=false;shell('A');var s=make(typeof coopDifficulty==='function'?coopDifficulty().tier:1);active=s;var last=performance.now(),endAt=0;function tick(){if(active!==s)return;var now=performance.now();step(s,(now-last)/1000);last=now;draw(snapshot(s,'A'),'A');netSend({t:'wmState',state:snapshot(s,'B')});if(s.done){window._dead=true;if(!endAt)endAt=now+1300;if(window._dungeon&&now>=endAt){var win=s.win;clearTimers();dungeonEnd(win);}else if(!window._dungeon&&s.againA&&s.againB)host();}}tick();timers.push(setInterval(tick,70));}
function guest(){var dungeon=window._dungeon;clearTimers();clean();S.mod='wires';window._dead=false;shell('B');if(!dungeon&&PEER.conn&&!PEER.conn._wiresMobileListener){PEER.conn._wiresMobileListener=function(d){dgGuestOnData(d);};PEER.conn.on('data',PEER.conn._wiresMobileListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};var op=renderPlay;renderPlay=function(){if(S.mod==='wires')return renderHost();return op.apply(this,arguments);};var om=renderManual;renderManual=function(){if(S.mod==='wires')return window._dungeon?guest():renderJoin();return om.apply(this,arguments);};var od=renderPlayDungeonHost;renderPlayDungeonHost=function(){if(S.mod==='wires')return host();return od.apply(this,arguments);};var oh=startHostGame;startHostGame=function(){if(S.mod==='wires')return host();return oh.apply(this,arguments);};var og=renderGuestUI;renderGuestUI=function(){if(S.mod==='wires')return guest();return og.apply(this,arguments);};var hd=dgHostOnData;dgHostOnData=function(d){if(/^wm(Ready|Cut|Hold|Bypass|Again)$/.test(d.t)){input(active,d,'B');return;}return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(d.t==='wmState'){if(S.mod!=='wires'||!$('wm-content'))return;if(view&&view.id!==d.state.id)guest();draw(d.state,'B');return;}return gd(d);};
window.WiresMobile={create:make,step:step,snapshot:snapshot,target:choose,input:input,state:function(){return active||view;}};
})();
