/* Stepwise asymmetric wire puzzle. Stable IDs, host-owned outcome and rescue. */
(function(){
'use strict';
var active=null,view=null,dispose=null,role='A',key='',selected=null,serial=0,roomCtx=null,lastTerminal=null,expectedRun=null,highestGeneration=0,sessionConnection=null;
var colors=['红','蓝','黄'],textures=['实线','条纹','圆点'],symbols=['△','○','□'];
function wireArt(w){var color={红:'#f0755f',蓝:'#75c6e1',黄:'#f7ce59'}[w.color],path=w.cut?'M18 22 C48 22 48 9 80 10 L103 15 M135 29 C161 36 188 13 222 22':'M18 22 C48 22 48 9 80 10 S130 37 164 27 S192 14 222 22';return '<svg viewBox="0 0 240 44" preserveAspectRatio="none" aria-hidden="true"><rect x="4" y="12" width="20" height="20" rx="3" fill="#acb8b0" stroke="#182e32" stroke-width="3"/><rect x="216" y="12" width="20" height="20" rx="3" fill="#acb8b0" stroke="#182e32" stroke-width="3"/><path d="'+path+'" fill="none" stroke="#172d31" stroke-width="15" stroke-linecap="round"/><path d="'+path+'" fill="none" stroke="'+color+'" stroke-width="10" stroke-linecap="round"/>'+(w.texture==='实线'?'':'<path d="'+path+'" fill="none" stroke="#253b40" stroke-width="'+(w.texture==='条纹'?10:3)+'" stroke-dasharray="'+(w.texture==='条纹'?'3 12':'1 11')+'" stroke-linecap="'+(w.texture==='条纹'?'butt':'round')+'"/>')+(w.cut?'<path d="M103 15l8 3m24 11l-8 -3" stroke="#edb576" stroke-width="5"/>':'')+'</svg>';}
var metadata=PLAYGROUNDS.find(function(p){return p.id==='wires';});if(metadata){metadata.a='报线号、颜色、纹理；选线后确认剪断。剪后揭示灯色和接头，重新向 B 报信息。';metadata.b='每次只看当前一步规则，听现场特征判断线号。首次剪错时，听 A 报符号并选择旁路。';}
function settings(tier){tier=Math.max(1,Math.min(5,Number(tier)||1));return {tier:tier,count:tier+3,goal:[3,3,3,4,5][tier-1],time:[180,150,150,165,180][tier-1],maxMistakes:[4,3,2,2,2][tier-1],rescueLimit:[3,2,1,1,1][tier-1],rescueSeconds:[20,14,10,8,6][tier-1],penalty:[0,3,5,8,10][tier-1]};}
function make(tier){var cfg=settings(tier),w=[];for(var i=0;i<cfg.count;i++)w.push({id:i+1,color:cfg.tier===1?['红','蓝','黄','红'][i]:colors[Math.floor(Math.random()*3)],texture:cfg.tier===1?['实线','条纹','圆点','条纹'][i]:textures[Math.floor(Math.random()*3)],cut:false});return {id:Date.now().toString(36)+'-'+(++serial),generation:serial,tier:cfg.tier,cfg:cfg,durationMs:0,mistakes:0,rescueCount:0,rescueSucceeded:false,reasonCode:null,wires:w,round:0,ready:{A:false,B:false},cd:3,time:cfg.time,light:cfg.tier===1?'蓝':Math.random()<.5?'蓝':'黄',plug:cfg.tier===1?'△':Math.random()<.5?'△':'○',decoder:cfg.tier<3?'正向':Math.random()<.5?'正向':'反向',serialOdd:cfg.tier===1?true:Math.random()<.5,routeColor:cfg.tier===1?'红':colors[Math.floor(Math.random()*3)],decoderTexture:cfg.tier===1?'实线':textures[Math.floor(Math.random()*3)],warning:cfg.tier===1?'奇数':Math.random()<.5?'奇数':'偶数',cutColors:[],lastColor:null,rescue:null,rescueUsed:false,done:false,win:false,msg:cfg.tier===1?'教学：固定线板。先剪 4 号，再报新灯色给 B。救场有 20 秒。':'双方读完职责，准备后开始。'};}
function choose(s){var live=s.wires.filter(function(w){return !w.cut;}),pool,high=false;
 if(s.round===0){pool=live.filter(function(w){return w.color==='红';});if(pool.length>=2)high=true;else{pool=live.filter(function(w){return w.color==='蓝';});if(!pool.length){pool=live;high=true;}}}
 else if(s.round===1){pool=live.filter(function(w){return w.texture===(s.light==='蓝'?'条纹':'圆点');});high=s.light!=='蓝';if(s.tier>=3&&s.decoder==='反向')high=!high;}
 else if(s.round===2){pool=live.filter(function(w){return s.plug==='△'?w.color===s.lastColor:w.color!==s.lastColor;});high=s.plug!=='△';if(s.tier>=4&&!s.serialOdd)high=!high;}
 else if(s.round===3){pool=live.filter(function(w){return w.color===s.routeColor&&w.texture===s.decoderTexture&&(s.tier<5||w.id%2===0);});}
 else{var last=s.cutColors.slice(-2);pool=live.filter(function(w){return !last.includes(w.color)&&(s.warning==='奇数'?w.id%2===1:w.id%2===0);});high=true;}
 if(!pool.length){pool=live;high=false;}return pool.reduce(function(a,b){return (high?b.id>a.id:b.id<a.id)?b:a;}).id;
}
function rules(s){var r=s.round,more=s.tier>=3,high=s.decoder==='反向';if(r===0)return ['先问 A：红线有几根？','红线至少 2 根 → 剪编号最大的红线。','否则，有蓝线 → 剪编号最小的蓝线。','红线不足 2 根且没有蓝线 → 剪编号最大的线。'];
 if(r===1)return ['先问 A：新亮的灯色。'+(more?'你这页是「'+s.decoder+'」规则，A 看不到。':''),'蓝灯 → 剪编号'+(more&&high?'最大':'最小')+'的条纹线。','黄灯 → 剪编号'+(more&&high?'最小':'最大')+'的圆点线。','没有这种纹理 → 剪编号最小的未剪线。'];
 if(r===2)return ['先问 A：接头、上一刀线色'+(s.tier>=4?'、铭牌奇偶。':'。'),'△ → 同色中最小号；○ → 异色中最大号。',s.tier>=4?'铭牌为偶数时，以上最大/最小反过来。':'先确认上一刀颜色，再报线号。','没有符合条件的线 → 剪编号最小的未剪线。'];
 if(r===3)return ['先问 A：新露出的支路色。','你的私有纹理是「'+s.decoderTexture+'」。','同时符合支路色、该纹理'+(s.tier===5?'、偶数线号':'')+' → 剪最小号。','没有同时符合条件的线 → 剪最小未剪线。'];
 return ['先问 A：警示奇偶和最近两刀颜色。','排除最近两刀的颜色，保留符合警示奇偶的线。','候选线中剪最大号。','没有候选 → 剪最小未剪线。'];}
function snapshot(s,who){var out={id:s.id,generation:s.generation,roomSession:s.roomSession||null,durationMs:s.durationMs,mistakes:s.mistakes,rescueSucceeded:s.rescueSucceeded,reasonCode:s.reasonCode,round:s.round,ready:s.ready,cd:s.cd,time:s.time,tier:s.tier,cfg:s.cfg,rescueCount:s.rescueCount,rescueUsed:s.rescueUsed,done:s.done,win:s.win,msg:s.msg};if(s.rescue)out.rescue={left:s.rescue.left,held:s.rescue.held,symbol:who==='A'?s.rescue.symbol:undefined};if(who==='A'){out.wires=s.wires;out.light=s.round>=1?s.light:null;out.plug=s.round>=2?s.plug:null;out.lastColor=s.lastColor;out.serialOdd=s.round>=2&&s.tier>=4?s.serialOdd:null;out.routeColor=s.round>=3?s.routeColor:null;out.warning=s.round>=4?s.warning:null;out.recentColors=s.round>=4?s.cutColors.slice(-2):null;}else out.rules=rules(s);return out;}
function finishGame(s,win,msg,code){if(s.done)return;s.done=true;s.win=win;s.msg=msg;s.reasonCode=code;s.rescue=null;}
function rescueFail(s,msg,code){s.rescue=null;if(s.tier<=2&&++s.mistakes<s.cfg.maxMistakes){s.msg=msg+' 已扣一次容错，重新判断当前刀。';return;}finishGame(s,false,msg,code);}
function input(s,d,who){if(!s||d.id!==s.id)return;if(s.done)return;if(d.t==='wmReady'){s.ready[who]=true;return;}if(d.round!==s.round||!s.ready.A||!s.ready.B||s.cd>0)return;
 if(s.rescue){if(who==='A'&&d.t==='wmHold'){s.rescue.held=!!d.v;s.rescue.seen=performance.now();}else if(who==='B'&&d.t==='wmBypass'){if(!s.rescue.held){s.msg='先让 A 按住断路开关，再选择旁路。';return;}if(d.symbol===s.rescue.symbol){s.rescue=null;s.rescueSucceeded=true;s.msg='旁路接通，短路解除！重新判断，刚才的线还没有剪断。';}else rescueFail(s,'旁路选择错误。','wires_bypass_wrong');}return;}
 if(who!=='A'||d.t!=='wmCut'||!Number.isInteger(d.wire))return;var wire=s.wires.find(function(w){return w.id===d.wire&&!w.cut;});if(!wire)return;
 if(wire.id!==choose(s)){s.mistakes++;s.time=Math.max(0,s.time-s.cfg.penalty);if(s.mistakes>=s.cfg.maxMistakes||s.rescueCount>=s.cfg.rescueLimit){finishGame(s,false,'容错已用完，警报触发。','wires_wrong_cut');return;}s.rescueCount++;s.rescueUsed=true;s.rescue={left:s.cfg.rescueSeconds,held:false,seen:0,symbol:s.tier===1?'△':symbols[Math.floor(Math.random()*symbols.length)]};s.msg='短路！A 按住断路开关并报符号，B 选择同形旁路。';return;}
 wire.cut=true;s.lastColor=wire.color;s.cutColors.push(wire.color);s.round++;if(s.round===s.cfg.goal)finishGame(s,true,'全部线路已解除，拆线成功！','wires_disarmed');else s.msg=s.round===1?'第一刀完成，指示灯亮了！A 报灯色，B 查看第二步。':s.round===2?'接头已露出！报形状、上一刀线色与铭牌。':s.round===3?'支路已露出！A 报支路色，B 查私有纹理。':'最终警示已亮起！报奇偶和最近两刀颜色。';
}
function step(s,dt){if(s.done||!s.ready.A||!s.ready.B)return;s.durationMs+=dt*1000;if(s.cd>0){s.cd=Math.max(0,s.cd-dt);return;}if(s.rescue){s.rescue.left-=dt;if(performance.now()-s.rescue.seen>650)s.rescue.held=false;if(s.rescue.left<=0)rescueFail(s,'救场超时。','wires_rescue_timeout');return;}s.time=Math.max(0,s.time-dt);if(s.time===0)finishGame(s,false,'时间到，警报触发。','wires_timeout');}
function clean(){if(active&&active.done)lastTerminal=active;else if(view&&view.done)lastTerminal=view;if(dispose)dispose();dispose=null;active=null;view=null;key='';selected=null;}
function act(t,extra){if(roomCtx&&roomCtx.isActive&&!roomCtx.isActive())return;var s=role==='A'?active:view;if(!s)return;var d=Object.assign({t:t,id:s.id,round:s.round},extra||{});if(role==='A')input(s,d,'A');else netSend(d);}
function shell(who){role=who;lastTerminal=null;clearNetZones();window._wirePick=window._wireKey=window._mazeMove=null;window._keys={};window.onkeydown=window.onkeyup=null;
 $('app').innerHTML='<section class="wm-shell"><header class="wm-top"><button id="back" aria-label="返回">‹</button><strong>警报拆线</strong><span class="wm-role wm-role-'+who+'">'+who+' · '+(who==='A'?'拆线员':'指挥员')+'</span></header><div class="wm-status"><b id="wm-progress">拆线 0 / 3</b><span id="count">准备中</span></div><section class="wm-panel"><h2 id="wm-title"></h2><p id="wm-duty"></p><div id="wm-clues"></div><div id="wm-content"></div></section><p id="msg" role="status"></p><footer id="wm-controls" class="wm-controls"></footer></section>';
 $('back').onclick=function(){if(roomCtx&&roomCtx.abort)roomCtx.abort();else if(window._dungeon)dungeonAbort();else{clearTimers();closePeer();location.search='';}};
 var held=false;function release(){if(held){held=false;act('wmHold',{v:false});}}function down(e){var b=e.target.closest('#wm-hold');if(!b||b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);held=true;act('wmHold',{v:true});}function keyboard(e){if(e.repeat)return;if(e.key===' '&&$('wm-hold')){e.preventDefault();held=true;act('wmHold',{v:true});}else if(e.key==='Enter'&&$('wm-cut')&&!$('wm-cut').disabled){e.preventDefault();$('wm-cut').click();}}
 function up(e){if(e.key===' ')release();}var el=document.querySelector('.wm-shell');el.addEventListener('pointerdown',down);el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('lostpointercapture',release);window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);window.addEventListener('keydown',keyboard);window.addEventListener('keyup',up);var heartbeat=setInterval(function(){if(held)act('wmHold',{v:true});},180),conn=PEER.conn;
 function disconnected(){clean();window._dead=true;if($('msg'))$('msg').textContent='连接断开，拆线已停止。请返回重新建房。';document.querySelectorAll('.wm-shell button:not(#back)').forEach(function(b){b.disabled=true;});}if(conn)conn.on('close',disconnected);
 dispose=function(){clearInterval(heartbeat);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);window.removeEventListener('keydown',keyboard);window.removeEventListener('keyup',up);if(conn&&conn.off)conn.off('close',disconnected);};
}
function draw(s,who){if(!$('wm-content'))return;view=s;document.querySelector('.wm-shell').classList.toggle('wm-finished',!!s.done);document.querySelector('.wm-shell').dataset.role=who;var waiting=!s.ready.A||!s.ready.B||s.cd>0;$('count').textContent=s.done?'已结束':!s.ready.A||!s.ready.B?'准备中':s.cd>0?Math.ceil(s.cd):s.rescue?'救场 '+Math.ceil(s.rescue.left)+'s':Math.ceil(s.time)+'s';$('wm-progress').textContent='拆线 '+Math.min(s.cfg.goal,s.round)+' / '+s.cfg.goal;$('msg').textContent=s.msg;
 $('wm-title').textContent=s.done?(s.win?'解除成功':'警报触发'):s.rescue?'紧急旁路':waiting?'先确认分工':'第 '+(s.round+1)+' 刀 · '+['颜色数量','灯色与纹理','接头与上一刀','支路组合','末路筛选'][s.round];$('wm-duty').textContent=who==='A'?'你看线板，向 B 报特征。点选线，再按下方按钮确认剪断；线号始终不变。':'你看当前规则，询问 A 现场特征，再报明确线号。每剪对一刀，规则自动更新。';
 var k=s.id+':'+s.round+':'+waiting+':'+!!s.rescue+':'+s.done;if(key!==k){key=k;selected=null;var content=$('wm-content'),controls=$('wm-controls');content.innerHTML='';controls.innerHTML='';$('wm-clues').innerHTML='';
 if(s.done){content.innerHTML='';controls.innerHTML='<span>本轮结束，正在同步结算…</span>';}
 else if(s.rescue){content.innerHTML=who==='A'?'<div class="wm-fuse"><small>把这个符号报给 B</small><strong>'+s.rescue.symbol+'</strong></div>':'<div class="wm-rule">听 A 报符号，等 A 按住开关后选择同形旁路。'+(s.tier<=2?'选错扣一次容错，尚有容错可继续。':'选错会失败。')+'</div>';controls.innerHTML=who==='A'?'<button id="wm-hold" class="wm-primary wm-action-A">按住断路开关</button>':'<div class="wm-bypass">'+symbols.map(function(x){return '<button data-symbol="'+x+'">'+x+'</button>';}).join('')+'</div><span id="wm-hold-status"></span>';controls.querySelectorAll('[data-symbol]').forEach(function(b){b.onclick=function(){act('wmBypass',{symbol:b.dataset.symbol});};});}
 else {if(who==='A'){$('wm-clues').innerHTML='<span>指示灯：'+(s.light||'剪完第一刀揭示')+'</span><span>接头：'+(s.plug||'剪完第二刀揭示')+'</span>'+(s.lastColor?'<span>上一刀：'+s.lastColor+'线</span>':'')+(s.serialOdd!==null&&s.serialOdd!==undefined?'<span>铭牌：'+(s.serialOdd?'奇数':'偶数')+'</span>':'')+(s.routeColor?'<span>支路：'+s.routeColor+'</span>':'')+(s.warning?'<span>警示：'+s.warning+' · 最近两刀：'+s.recentColors.join('、')+'</span>':'');content.innerHTML='<div class="wm-board"><div class="wm-device-head"><span>拆弹线路 · 固定线号</span><b id="wm-fuse-clock">--</b></div>'+s.wires.map(function(w){return '<button class="wm-wire '+(w.cut?'cut':'')+'" data-wire="'+w.id+'" '+(w.cut||waiting?'disabled':'')+' aria-label="'+w.id+'号 '+w.color+'色 '+w.texture+(w.cut?' 已剪断':'')+'"><b class="wm-wire-number">'+w.id+'</b><span class="wm-cable">'+wireArt(w)+'</span><span class="wm-wire-label">'+w.color+' · '+w.texture+(w.cut?' · 已断':'')+'</span></button>';}).join('')+'<div class="wm-device-foot"><span>●</span> 双重确认后剪断</div></div>';content.querySelectorAll('[data-wire]').forEach(function(b){b.onclick=function(){selected=+b.dataset.wire;content.querySelectorAll('button').forEach(function(x){x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('wm-cut').disabled=false;$('wm-cut').textContent='确认剪断 '+selected+' 号线';};});if(!waiting){controls.innerHTML='<button id="wm-cut" class="wm-primary wm-action-A" disabled>先点选一根线</button><span>'+('剩余容错 '+Math.max(0,s.cfg.maxMistakes-s.mistakes)+' · 旁路救场 '+Math.max(0,s.cfg.rescueLimit-s.rescueCount)+' 次')+'</span>';$('wm-cut').onclick=function(){if(selected===null)return;act('wmCut',{wire:selected});selected=null;this.disabled=true;};}}
 else content.innerHTML='<ol class="wm-rules">'+s.rules.map(function(r){return '<li>'+r+'</li>';}).join('')+'</ol><div class="wm-rule-foot">只考虑未剪断的线 · 线号不重新排列</div>';
 if(waiting){controls.innerHTML='<button id="wm-ready" class="wm-primary wm-action-'+who+'">我已读懂 · 准备好了</button><span id="wm-wait"></span>';$('wm-ready').onclick=function(){act('wmReady');};}else if(who==='B')controls.innerHTML='<div class="wm-command"><b>向 A 报：剪「几号线」</b><span>等 A 确认剪断后，查看新规则</span></div>';}
 }
 if($('wm-hold'))$('wm-hold').setAttribute('aria-pressed',String(!!(s.rescue&&s.rescue.held)));if($('wm-fuse-clock'))$('wm-fuse-clock').textContent=waiting?'待命':Math.ceil(s.time)+'s';if($('wm-ready')){$('wm-ready').disabled=s.ready[who];$('wm-ready').textContent=s.ready[who]?'已准备':'我已读懂 · 准备好了';$('wm-wait').textContent=s.ready.A&&s.ready.B?'即将开始':'等待同伴准备';}if($('wm-hold-status'))$('wm-hold-status').textContent=s.rescue.held?'A 已按住 · 现在选择旁路':'等待 A 按住断路开关';if(s.rescue&&who==='B')document.querySelectorAll('[data-symbol]').forEach(function(b){b.disabled=!s.rescue.held;});
}
function resultData(s){return {win:s.win,reason:s.msg,reasonCode:({wires_disarmed:'completed',wires_wrong_cut:'attempts_exhausted',wires_bypass_wrong:'incorrect_answer',wires_rescue_timeout:'timeout',wires_timeout:'timeout'})[s.reasonCode]||'objective_failed',metrics:{durationMs:Math.round(s.durationMs),timeLeftMs:Math.round(s.time*1000),completed:s.wires.filter(function(w){return w.cut;}).length,goal:s.cfg.goal,mistakesRemaining:Math.max(0,s.cfg.maxMistakes-s.mistakes),maxMistakes:s.cfg.maxMistakes,rescueUsed:s.rescueUsed?1:0,rescueSucceeded:s.rescueSucceeded?1:0}};}
function bindResults(id){if(roomCtx)return;RoomResults.begin({runId:id,role:role,connection:PEER.conn,gameId:'wires',title:'警报拆线',dungeon:null,onContinue:function(){if(role==='A')host();else guest();},onExit:function(){clearTimers();closePeer();window._netMode=null;S.role=null;render();}});}
function host(ctx){var session=window.RoomSession&&RoomSession.current();clearTimers();clean();roomCtx=ctx||(window._dungeon&&window._roomGameContext&&window._roomGameContext.mode==='wires'?window._roomGameContext:null);S.mod='wires';window._dead=false;shell('A');var s=make(session?session.tier:roomCtx?roomCtx.tier:typeof coopDifficulty==='function'?coopDifficulty().tier:1);s.roomSession=session?session.runId:roomCtx&&(roomCtx.runId||roomCtx.sessionId);s.id=s.roomSession||s.id;active=s;expectedRun=s.id;bindResults(s.id);var last=performance.now();function tick(){if(active!==s||roomCtx&&roomCtx.isActive&&!roomCtx.isActive())return;var now=performance.now();step(s,(now-last)/1000);last=now;draw(snapshot(s,'A'),'A');netSend({t:s.synced?'wmState':'wmStart',state:snapshot(s,'B')});if(s.done){window._dead=true;lastTerminal=s;if(!s.reported){s.reported=true;var data=resultData(s);if(roomCtx)roomCtx.finish(data);else RoomResults.report(data);}}}tick();timers.push(setInterval(tick,70));}
function guest(ctx){var session=window.RoomSession&&RoomSession.current();var dungeon=!session&&!!window._dungeon;clearTimers();clean();roomCtx=ctx||(window._dungeon&&window._roomGameContext&&window._roomGameContext.mode==='wires'?window._roomGameContext:null);expectedRun=null;S.mod='wires';window._dead=false;shell('B');if(sessionConnection!==PEER.conn){sessionConnection=PEER.conn;highestGeneration=0;}if(!dungeon&&PEER.conn&&!PEER.conn._wiresMobileListener){var conn=PEER.conn;conn._wiresMobileListener=function(d){if(RoomResults.consume(d,conn))return;if(conn!==PEER.conn)return;dgGuestOnData(d);};conn.on('data',conn._wiresMobileListener);}}
var oc=clearTimers;clearTimers=function(){clean();return oc();};var op=renderPlay;renderPlay=function(){if(S.mod==='wires')return renderHost();return op.apply(this,arguments);};var om=renderManual;renderManual=function(){if(S.mod==='wires')return window._dungeon?guest():renderJoin();return om.apply(this,arguments);};var od=renderPlayDungeonHost;renderPlayDungeonHost=function(){if(S.mod==='wires')return host();return od.apply(this,arguments);};var oh=startHostGame;startHostGame=function(){if(S.mod==='wires')return host();return oh.apply(this,arguments);};var og=renderGuestUI;renderGuestUI=function(){if(S.mod==='wires')return guest();return og.apply(this,arguments);};var hd=dgHostOnData;dgHostOnData=function(d){if(window.RoomResults&&RoomResults.consume(d,PEER.conn))return;if(d.t==='wmSynced'){if(active&&d.id===active.id)active.synced=true;return;}if(/^wm(Ready|Cut|Hold|Bypass)$/.test(d.t)){if(roomCtx&&roomCtx.isActive&&!roomCtx.isActive())return;input(active,d,'B');return;}return hd(d);};var gd=dgGuestOnData;dgGuestOnData=function(d){if(window.RoomResults&&RoomResults.consume(d,PEER.conn))return;if(d.t==='wmStart'||d.t==='wmState'){if(S.mod!=='wires'||!$('wm-content')||!d.state)return;var s=d.state;if(roomCtx&&roomCtx.isActive&&!roomCtx.isActive())return;if(roomCtx&&s.roomSession!==(roomCtx.runId||roomCtx.sessionId))return;if(d.t==='wmStart'){if(!Number.isInteger(s.generation)||s.generation<highestGeneration&&!roomCtx)return;if(expectedRun&&s.id!==expectedRun)return;if(!expectedRun){if(s.generation===highestGeneration&&!roomCtx)return;highestGeneration=s.generation;expectedRun=s.id;bindResults(s.id);}netSend({t:'wmSynced',id:s.id});}if(s.id!==expectedRun)return;draw(s,'B');if(s.done){window._dead=true;lastTerminal=s;}return;}return gd(d);};

window.RoomGameAdapters=window.RoomGameAdapters||{};window.RoomGameAdapters.wires={host:host,guest:guest};
window.WiresMobile={settings:settings,create:make,step:step,snapshot:snapshot,target:choose,input:input,resultData:resultData,state:function(){return active||view||lastTerminal;}};
})();
