/* Formal session adapter. Historical stapler is a functional fixture, not an approved riddle. */
(function(){'use strict';
const VERSION='picture-guess-v1';
const CONTENT='three-tier-1';
function card(){return q.config;}
function mine(){return card().offsets.map((_,i)=>i).filter(i=>i%2===(q.role==='A'?0:1));}
function limit(value){return Math.max(-card().moveLimit,Math.min(card().moveLimit,Math.round(value)));}
let q=null;
const el=id=>document.getElementById(id);
function sound(type){if(window.GameFeedback)GameFeedback.emit(type,{source:'picture-guess'});}
function stop(){if(!q)return;clearInterval(q.timer);q.clean.forEach(f=>f());q=null;}
function send(kind,extra={}){if(!q||!q.ctx.isActive()||q.failed||q.stalled||!q.view)return;const d={t:'pgInput',protocol:VERSION,contentVersion:CONTENT,runId:q.view.runId,seq:++q.seq,kind,...extra};if(q.role==='A'){PictureCore.input(q.state,d,'A',q.card);publish();}else q.ctx.send(d);}
function packet(d){if(!q||q.failed||!q.ctx.isActive()||d.protocol!==VERSION||d.runId!==q.ctx.sessionId)return;if(d.contentVersion!==CONTENT){fail('双方玩法版本不一致，请刷新后重新进入。');return;}q.seen=Date.now();q.stalled=false;if(q.role==='A'&&d.t==='pgInput'){PictureCore.input(q.state,d,'B',q.card);publish();}else if(q.role==='B'&&d.t==='pgState'&&Number.isSafeInteger(d.frame)&&d.frame>q.frame){if(!validState(d.state)){fail('题目配置不同步，请返回重试。');return;}q.frame=d.frame;q.anchor={time:d.now,local:performance.now()};draw(d.state);}}
function publish(){if(!q||q.role!=='A'||!q.ctx.isActive()||q.failed)return;PictureCore.tick(q.state);const s=PictureCore.snapshot(q.state,q.card);draw(s);q.ctx.send({t:'pgState',protocol:VERSION,contentVersion:CONTENT,runId:q.ctx.sessionId,frame:++q.frame,now:Date.now(),state:s});if(['solved','failed'].includes(s.phase)&&s.revealed.A&&s.revealed.B&&!q.settled){q.settled=true;q.ctx.finish({win:s.phase==='solved',reasonCode:s.phase==='solved'?'completed':'timeout',reason:s.phase==='solved'?'共同辨认出了图片中的物品':'时间到了，答案已揭晓',rulesVersion:VERSION,metrics:{completed:s.phase==='solved'?1:0,goal:1,guesses:s.history.length,movesA:s.moves.A,movesB:s.moves.B,functionalFixture:true,rulesVersion:VERSION}});}}
function validState(s){const c=card();return s&&s.runId===q.ctx.sessionId&&s.cardId===c.id&&s.layoutId===c.layoutId&&s.difficulty===c.difficulty&&s.windowWidth===c.windowWidth&&s.answerLength===c.answerLength&&['prepare','play','proposal','solved','failed'].includes(s.phase)&&Array.isArray(s.offsets)&&s.offsets.length===c.offsets.length&&s.offsets.every(x=>Number.isInteger(x)&&Math.abs(x)<=c.moveLimit)&&s.ready&&s.revealed&&s.moves&&['A','B'].every(w=>typeof s.ready[w]==='boolean'&&typeof s.revealed[w]==='boolean'&&Number.isSafeInteger(s.moves[w])&&s.moves[w]>=0)&&(['prepare','solved','failed'].includes(s.phase)||Number.isFinite(s.deadline))&&(!['solved','failed'].includes(s.phase)||typeof s.answer==='string')&&Array.isArray(s.history)&&(s.phase!=='proposal'||s.proposal&&typeof s.proposal.id==='string'&&typeof s.proposal.text==='string'&&['A','B'].includes(s.proposal.by));}
function board(s){const c=card(),height=360/s.offsets.length,base=-(360-c.windowWidth)/2;return '<div class="pg-board" style="--pg-width:'+c.windowWidth+'px;--pg-row:'+height+'px" aria-label="窄窗拼图：拖动当前选中的本人条片">'+s.offsets.map((x,i)=>'<div class="pg-strip" data-row="'+i+'"><small>'+(i+1)+' · '+(i%2?'B':'A')+'</small><svg viewBox="0 '+i*height+' '+c.windowWidth+' '+height+'"><g data-band="'+i+'" transform="translate('+(base+x)+' 0)"><image href="'+c.image+'" width="360" height="360"/></g></svg></div>').join('')+'</div>';}
function button(id,text){return '<button id="'+id+'">'+text+'</button>';}
function release(){if(!q||!q.drag)return;const d=q.drag;q.drag=null;if(el('pg-scene')?.hasPointerCapture(d.pointer))el('pg-scene').releasePointerCapture(d.pointer);if(q.view?.phase==='play')send('move',{index:d.index,value:d.start});paint();}
function paint(){if(!q?.view)return;document.querySelectorAll('[data-band]').forEach(g=>{const i=+g.dataset.band;g.setAttribute('transform','translate('+(-(360-card().windowWidth)/2+(q.drag?.index===i?q.drag.value:q.view.offsets[i]))+' 0)');});document.querySelectorAll('[data-select]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.select===q.selected)));document.querySelectorAll('[data-row]').forEach(r=>r.classList.toggle('pg-selected',+r.dataset.row===q.selected));}
function draw(s){if(!q)return;const old=q.view;q.view=s;const key=s.runId+':'+(['play','proposal'].includes(s.phase)?'play':s.phase);if(old&&old.phase!==s.phase){release();sound(s.phase==='solved'?'correct':s.phase==='failed'?'error':'tap');}if(old&&s.history.length>old.history.length&&s.phase==='play')sound(s.history.at(-1).accepted?'error':'tap');
if(key!==q.layout){q.layout=key;q.entry=null;const scene=el('pg-scene'),controls=el('pg-controls');
if(s.phase==='prepare'){scene.innerHTML='<h2>一起猜出图片里的物品</h2><p>'+card().label+' · '+card().brief+'</p><p>你移动第 '+mine().map(i=>i+1).join('、')+' 条。先选条号，再左右拖图。认出来就能提案，不必拼齐；同伴确认后验证，猜错继续拼。</p><p>先试一下：拖动下方练习条，或点微调。</p><div id="pg-practice" aria-label="无答案练习条"><span>←　练习条　→</span></div>'+button('pg-practice-step','微调练习条')+'<p>双方准备后开始 90 秒；确认答案时继续计时。</p><small>当前为功能测试题，题材及三档难度尚待验证。</small>';controls.innerHTML=button('pg-ready','完成练习后准备');const practiced=()=>{q.practiced=true;el('pg-practice').classList.add('practiced');el('pg-ready').disabled=false;el('pg-ready').textContent='读懂了 · 准备';};el('pg-practice-step').onclick=practiced;let start=null;el('pg-practice').onpointerdown=e=>{start=e.clientX;e.currentTarget.setPointerCapture(e.pointerId);};el('pg-practice').onpointermove=e=>{if(start!==null&&Math.abs(e.clientX-start)>8)practiced();};el('pg-practice').onpointerup=el('pg-practice').onpointercancel=()=>{start=null;};el('pg-ready').onclick=()=>send('ready');}
else if(['solved','failed'].includes(s.phase)){scene.innerHTML='<h2 id="pg-answer"></h2><img class="pg-reveal" src="'+card().image+'" alt="完整物品线稿"><p>'+(s.phase==='solved'?'猜对就完成，不必移动剩余条片。':'时间到了。看看完整图，再与同伴讨论线索。')+'</p><details><summary>回看初始切片</summary>'+board({offsets:card().offsets})+'</details><small>重玩同题用于熟悉操作，不算首次发现测试。</small>';el('pg-answer').textContent=(s.phase==='solved'?'猜对了：':'答案：')+s.answer;controls.innerHTML=button('pg-result','已看完 · 查看结算');el('pg-result').onclick=()=>send('reveal');}
else{scene.innerHTML='<div class="ps-select">'+mine().map(i=>'<button data-select="'+i+'">第 '+(i+1)+' 条</button>').join('')+'</div>'+board(s)+'<div class="ps-directions">'+button('pg-left','← 微调')+button('pg-right','微调 →')+'</div>';controls.innerHTML='<div id="pg-entry"></div><section id="pg-proposal" hidden></section>';q.entry=PictureAnswerInput.mount(el('pg-entry'),{length:s.answerLength,inputId:'pg-answer-input',onSubmit:text=>send('propose',{text})});scene.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{release();q.selected=+b.dataset.select;paint();});el('pg-left').onclick=()=>nudge(-6);el('pg-right').onclick=()=>nudge(6);scene.onpointerdown=e=>{if(q.failed||q.stalled||q.view.phase!=='play'||!e.target.closest('.pg-board')||e.button!==0)return;e.preventDefault();q.drag={pointer:e.pointerId,x:e.clientX,index:q.selected,start:q.view.offsets[q.selected],value:q.view.offsets[q.selected],sent:0};scene.setPointerCapture(e.pointerId);};scene.onpointermove=e=>{const d=q?.drag;if(!d||d.pointer!==e.pointerId||q.view.phase!=='play')return;if(Math.abs(e.clientX-d.x)<8&&!d.moved)return;d.moved=true;d.value=limit(d.start+(e.clientX-d.x)*card().windowWidth/scene.querySelector('svg').clientWidth);paint();if(Date.now()-d.sent>40){d.sent=Date.now();send('move',{index:d.index,value:d.value});}};scene.onpointerup=e=>{const d=q?.drag;if(!d||d.pointer!==e.pointerId)return;q.drag=null;if(scene.hasPointerCapture(e.pointerId))scene.releasePointerCapture(e.pointerId);if(d.moved)send('move',{index:d.index,value:d.value});};scene.onpointercancel=release;}}
el('pg-status').textContent=s.notice;
if(s.phase==='prepare'){el('pg-ready').disabled=!q.practiced||s.ready[q.role];if(s.ready[q.role])el('pg-ready').textContent='已准备 · 等同伴';}
else if(['solved','failed'].includes(s.phase)){el('pg-result').disabled=!!s.revealed[q.role];if(s.revealed[q.role])el('pg-result').textContent='等同伴看完';}
else{paint();const pending=s.phase==='proposal';q.entry.lock(pending);el('pg-entry').hidden=false;el('pg-proposal').hidden=!pending;el('pg-scene').querySelectorAll('button').forEach(b=>b.disabled=pending);if(pending&&el('pg-proposal').dataset.id!==s.proposal.id){const box=el('pg-proposal');box.dataset.id=s.proposal.id;box.replaceChildren();const text=document.createElement('p');text.textContent=s.proposal.by+' 提议：'+s.proposal.text;box.append(text);if(s.proposal.by!==q.role){for(const [id,label,accept]of[['pg-accept','同意 · 验证',true],['pg-reject','继续找线索',false]]){const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=()=>send('respond',{proposalId:s.proposal.id,accept});box.append(b);}}else{const p=document.createElement('p');p.textContent='等同伴确认；条片暂时停住，倒计时继续。';box.append(p);}}}
if(q.stalled){el('pg-status').textContent='等待同伴恢复响应，倒计时继续；恢复后自动同步。';document.querySelectorAll('.pg-shell button:not(#pg-menu)').forEach(b=>b.disabled=true);q.entry?.lock(true);}
clock();}
function nudge(delta){if(q.stalled||q.view.phase!=='play')return;send('move',{index:q.selected,value:limit(q.view.offsets[q.selected]+delta)});}
function clock(){if(!q?.view)return;const s=q.view,now=q.role==='A'?Date.now():q.anchor?q.anchor.time+performance.now()-q.anchor.local:Date.now();el('pg-clock').textContent=s.phase==='prepare'?'准备中':['solved','failed'].includes(s.phase)?'已结束':Math.max(0,Math.ceil((s.deadline-now)/1000))+' 秒';}
function fail(message){if(!q||q.failed)return;release();q.failed=true;el('pg-status').textContent=typeof message==='string'?message:'同伴连接中断，操作已停止。请通过菜单返回。';document.querySelectorAll('.pg-shell button:not(#pg-menu),.pg-shell input').forEach(b=>b.disabled=true);}
async function enter(ctx,role){clearTimers();clearNetZones();S.mod='pwslide';const config=PictureGuessDeck.get(ctx.difficulty);if(ctx.tier!==[1,3,5][ctx.difficulty-1])throw Error('密码猜图难度不同步');const own=q={ctx,role,config,seq:0,frame:0,view:null,selected:role==='A'?0:1,seen:Date.now(),clean:[],failed:false,practiced:false};el('app').innerHTML='<main class="ps-shell ps-room pg-shell"><header class="ps-header">'+button('pg-menu','☰')+'<h1>密码猜图</h1><span class="ps-role">'+role+' · <span id="pg-clock">准备中</span></span></header><section id="pg-scene" class="ps-paper"></section><p id="pg-status" class="ps-status" role="status">等待同步…</p><footer id="pg-controls"></footer></main>';el('pg-menu').onclick=()=>ctx.menu?ctx.menu({help:'选择本人条号后拖图；猜出物品即可提案。双方准备后计时，菜单和提案不会暂停。',release}):RoomShell.menu({release});window.addEventListener('blur',release);own.clean.push(()=>window.removeEventListener('blur',release));const conn=typeof PEER!=='undefined'&&PEER.conn;if(conn){conn.on('close',fail);conn.on('error',fail);own.clean.push(()=>{conn.off?.('close',fail);conn.off?.('error',fail);});}
if(role==='A'){try{const response=await fetch('experiments/picture-strip/host-answers.json',{cache:'no-store'});if(!response.ok)throw Error('answer');const answers=await response.json();if(q!==own||!ctx.isActive())return;const record=answers[config.id];own.card={...config,answer:typeof record==='string'?record:record.answer};if(typeof own.card.answer!=='string'||Array.from(PictureCore.fixedText(own.card.answer)).length!==config.answerLength)throw Error('answer');own.state=PictureCore.create(own.card,ctx.sessionId);publish();}catch(e){if(q===own){fail();el('pg-status').textContent='题目加载失败，请通过菜单返回重试。';}return;}}
own.timer=setInterval(()=>{if(q!==own||own.failed||!ctx.isActive())return;own.stalled=Date.now()-own.seen>9000;if(own.stalled)release();if(role==='A')publish();else ctx.send({t:'pgPulse',protocol:VERSION,contentVersion:CONTENT,runId:ctx.sessionId});if(role==='B'&&own.view)draw(own.view);clock();},200);}
const host=dgHostOnData,guest=dgGuestOnData;dgHostOnData=function(d){if(d&&['pgInput','pgPulse'].includes(d.t)){packet(d);return;}return host(d);};dgGuestOnData=function(d){if(d?.t==='pgState'){packet(d);return;}return guest(d);};const clear=clearTimers;clearTimers=function(){stop();return clear.apply(this,arguments);};
window.RoomGameAdapters=window.RoomGameAdapters||{};window.PictureGuessAdapter={ruleset:VERSION,host:ctx=>enter(ctx,'A'),guest:ctx=>enter(ctx,'B')};window.PictureGuess={state:()=>q?.view,version:VERSION,contentVersion:CONTENT};
})();
