/* Resource readiness is separate from gameplay readiness. One transport listener remains authoritative. */
(function(g){
'use strict';
let installed=false, booted=false, current=null, mapLease=null, nodeLease=null, mapConn=null, mapRoute=null, serial=0, highest=0, observedConn=null, entering=false;
let last={stage:'startup',completed:0,total:0,error:null}, bootLease=null;
let prefetch=null,prefetchKey='',mapInterrupted=false,bossPermit=null;
const $=s=>document.querySelector(s), version=()=>String(g.APP_VER||''), role=()=>g._netMode==='host'?'A':'B';
function route(){return g.DUNGEON&&(DUNGEON.route&&DUNGEON.route.id||DUNGEON.roomId);}
function connected(){const s=g.DungeonConnection&&DungeonConnection.status();return !!(g.PEER&&PEER.conn&&PEER.conn.open&&(!s||s.state==='connected'));}
function mapReady(){return connected()&&mapConn===PEER.conn&&mapRoute===route();}
function room(){return (g.ROOM_CATALOG||[]).find(r=>g.DUNGEON&&r.id===DUNGEON.roomId)|| (typeof selectedRoom==='function'?selectedRoom():null);}
function view(){ $('#room-boot')?.remove();let el=$('#room-loading');if(el)return el;el=document.createElement('section');el.id='room-loading';el.className='rl-screen';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-labelledby','rl-title');el.innerHTML='<div class="rl-card"><div class="rl-door" aria-hidden="true"><i></i><span>两位，请进</span></div><p class="rl-eyebrow">再做一分钟朋友</p><h1 id="rl-title" data-rl-title>正在准备房间</h1><p data-rl-detail></p><progress data-rl-progress max="1" value="0" aria-label="资源准备进度"></progress><p data-rl-count role="status" aria-live="polite"></p><div class="rl-people"><span data-rl-a>A · 准备中</span><span data-rl-b>B · 准备中</span></div><p data-rl-error role="alert"></p><div class="rl-actions"><button type="button" data-rl-retry hidden>重新加载</button><button type="button" data-rl-back>返回地图</button></div></div>';document.body.appendChild(el);const app=$('#app');if(app)app.inert=true;el.onkeydown=e=>{if(e.key==='Tab'){const buttons=Array.from(el.querySelectorAll('button')).filter(b=>!b.hidden&&!b.disabled);if(!buttons.length){e.preventDefault();return;}if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0].focus();}}};return el;}
function hide(){ $('#room-loading')?.remove();const app=$('#app');if(app)app.inert=false; }
function paint(s){last={stage:s.kind||s.stage,attemptId:s.batch?.attemptId||null,roomId:s.batch?.roomId||null,nodeId:s.batch?.nodeId||null,mode:s.batch?.mode||null,localReady:!!s.localReady,remoteReady:!!s.remoteReady,completed:s.completed||0,total:s.total||0,error:s.error||null,warning:s.warning||null};
 const el=view();el.dataset.stage=last.stage;el.dataset.attemptId=last.attemptId||'';const title=el.querySelector('[data-rl-title]'),detail=el.querySelector('[data-rl-detail]'),p=el.querySelector('progress');
 title.textContent=s.kind==='startup'?'正在打开怪房子':s.kind==='map'?'正在展开密室地图':'正在准备下一关';detail.textContent=s.kind==='startup'?'准备游戏界面和首屏素材':(room()?.name||'密室')+(s.kind==='node'?' · '+(g.PLAYGROUNDS?.find(p=>p.id===s.batch?.mode)?.name||'下一关'):'');
 p.max=Math.max(1,last.total);p.value=last.completed;el.querySelector('[data-rl-count]').textContent=s.waiting?'等待房主准备地图':s.localReady&&s.kind!=='startup'?'你已准备好，等待同伴':last.total?'已准备 '+last.completed+' / '+last.total+' 项':'正在核对所需素材';
 el.querySelector('.rl-people').hidden=s.kind==='startup';for(const r of ['A','B']){const ready=r===role()?s.localReady:s.remoteReady;const row=el.querySelector('[data-rl-'+r.toLowerCase()+']');row.textContent=r+' · '+(ready?'已就绪':'准备中');row.dataset.ready=String(!!ready);}
 el.querySelector('[data-rl-error]').textContent=s.error||s.warning||'';const retry=el.querySelector('[data-rl-retry]');retry.hidden=!s.error&&!s.warning;retry.onclick=s.kind==='startup'?()=>location.reload():()=>retryCurrent();const back=el.querySelector('[data-rl-back]');back.textContent=s.kind==='startup'?'返回首页':s.kind==='map'?'返回密室选择':'返回地图';back.onclick=s.kind==='startup'?()=>{location.href=location.pathname;}:()=>cancel(true,'返回');
}
function release(which){const lease=which==='map'?mapLease:nodeLease;if(lease)lease.release();if(which==='map')mapLease=null;else nodeLease=null;}
function stopGather(){if(!g.DUNGEON)return;clearTimeout(DUNGEON._t);DUNGEON._t=null;if(typeof hideDgBar==='function')hideDgBar();document.querySelectorAll('.dg-ring').forEach(el=>el.style.display='none');}
function stopPrefetch(){if(prefetch){clearTimeout(prefetch.timer);prefetch.controller.abort();prefetch.lease?.release();prefetch=null;}prefetchKey='';}
function prefetchNext(){if(current||!mapReady()||S.mod!=='dungeon')return;const at=dgNode(DUNGEON.posA),n=(at?.next||[]).map(dgNode).find(n=>n&&!n.done&&!DUNGEON.locked[n.id]&&n.mode);if(!n)return;const list=RoomAssets.manifest(['mode:'+n.mode]).slice(0,2);if(!list.length)return;const key=route()+':'+n.id;if(key===prefetchKey)return;stopPrefetch();prefetchKey=key;const p=prefetch={controller:new AbortController(),timer:null,lease:null};p.timer=setTimeout(async()=>{for(const item of list){if(prefetch!==p||p.controller.signal.aborted)return;try{p.lease=await RoomAssets.prepare([item],{signal:p.controller.signal,priority:'low'});p.lease.release();p.lease=null;}catch(_){/* A future foreground attempt handles required-resource failures. */}}},300);}
function send(t,batch,extra){if(g.PEER&&PEER.conn&&PEER.conn.open)try{PEER.conn.send(Object.assign({t,v:1,batch},extra));}catch(_){}}
function same(a,b){return !!a&&!!b&&['attemptId','serial','roomId','routeId','nodeId','mode','kind','version'].every(k=>a[k]===b[k]);}
function validBatch(b){if(!b||!g.DUNGEON||DUNGEON.over||b.roomId!==DUNGEON.roomId||b.routeId!==route()||!['map','node'].includes(b.kind)||!Number.isSafeInteger(b.serial)||typeof b.attemptId!=='string')return false;if(b.kind==='map')return b.nodeId===null&&b.mode===null;const n=dgNode(b.nodeId);return !!n&&!n.done&&!DUNGEON.locked[b.nodeId]&&b.mode===(n.type==='boss'?'boss':n.mode);}
function active(s){return current===s&&!s.controller.signal.aborted&&s.conn===PEER.conn&&connected()&&validBatch(s.batch);}
function detach(s){clearTimeout(s.timeout);s.off.forEach(fn=>fn());s.off=[];s.observer?.disconnect();}
function cancel(notify,reason){const s=current,waitingMap=!s&&last.stage==='map';current=null;stopPrefetch();stopGather();if(s){detach(s);s.controller.abort();s.lease?.release();if(notify)send('rlCancel',s.batch,{reason:String(reason||'取消')});}hide();last={stage:'idle',completed:0,total:0,error:null};if(s?.kind==='map'||waitingMap){mapConn=null;mapRoute=null;mapInterrupted=reason==='连接变化';if(reason==='返回'){if(waitingMap&&g.PEER?.conn?.open)netSend({t:'bye'});renderDungeonMenu();return;}}if(g.DUNGEON&&S.mod==='dungeon'&&reason!=='离开')dgMsg(mapInterrupted?'地图准备已暂停，连接恢复后将重新准备地图。':'准备已取消，请重新选择节点出发。');}
function error(s,text){if(!active(s))return;s.error=text;paint(s);}
function progress(s,p){if(!active(s))return;s.completed=p.completed;s.total=p.total;paint(s);}
function scopes(b){return b.kind==='map'?['map','room:'+b.roomId]:['room:'+b.roomId,'mode:'+b.mode];}
function finish(s){if(!active(s)||!s.localReady||!s.remoteReady||s.error||role()!=='A')return;send('rlCommit',s.batch);commit(s);}
function commit(s){if(!active(s)||!s.localReady||s.error)return;current=null;detach(s);release(s.kind);if(s.kind==='map'){mapLease=s.lease;mapConn=s.conn;mapRoute=s.batch.routeId;}else nodeLease=s.lease;s.lease=null;hide();last={stage:'idle',attemptId:s.batch.attemptId,localReady:true,remoteReady:true,completed:s.total,total:s.total,error:null};
 if(s.kind==='map'){dgDrawMap();prefetchNext();return;}if(role()==='A'){if(s.batch.mode==='boss')bossPermit={conn:s.conn,route:s.batch.routeId,node:s.batch.nodeId};entering=true;try{s.enter(s.batch.nodeId);}finally{entering=false;}}
}
function monitor(s){function lost(){if(current===s)cancel(true,'连接变化');}for(const event of ['close','error']){s.conn.on(event,lost);s.off.push(()=>s.conn.off(event,lost));}s.observer=new MutationObserver(()=>{if(current===s&&!connected())lost();});s.observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['data-link-state']});s.timeout=setTimeout(()=>{if(!active(s))return;s.warning='准备用时较长，可继续等待、重新加载或返回。';paint(s);},45000);}
function begin(batch,enter,failure){if(current)cancel(false,'替换');bossPermit=null;if(batch.kind==='map')mapInterrupted=false;stopPrefetch();stopGather();const s=current={batch,kind:batch.kind,conn:PEER.conn,controller:new AbortController(),localReady:false,remoteReady:false,completed:0,total:0,error:failure||null,lease:null,enter,off:[]};paint(s);monitor(s);if(failure)return s;if(role()==='A')send('rlPrepare',batch);
 const list=RoomAssets.manifest(scopes(batch));s.total=list.length;paint(s);RoomAssets.prepare(list,{signal:s.controller.signal,onProgress:p=>progress(s,p)}).then(lease=>{if(!active(s)){lease.release();return;}s.lease=lease;s.localReady=true;s.completed=s.total;paint(s);send('rlReady',batch);if(role()==='A')finish(s);}).catch(e=>{if(!active(s)||e.name==='AbortError')return;error(s,'必要素材没有加载完成，请重试。');send('rlError',batch,{message:'同伴有素材加载失败，请一起重试。'});});return s;
}
function start(kind,nodeId,enter){if(!connected()||current||!DUNGEON||DUNGEON.over)return;const n=nodeId!=null?dgNode(nodeId):null;const batch={attemptId:(g.crypto?.randomUUID?crypto.randomUUID():Date.now()+'-'+(++serial)),serial:++serial,roomId:DUNGEON.roomId,routeId:route(),nodeId:nodeId??null,mode:n?(n.type==='boss'?'boss':n.mode):null,kind,version:version()};begin(batch,enter);}
function retryCurrent(){const s=current;if(!s)return;if(role()==='B'){send('rlRetry',s.batch);s.error=null;paint(s);return;}const {kind,batch,enter}=s;cancel(true,'重试');start(kind,batch.nodeId,enter);}
function consume(conn,d){if(!d||!String(d.t).startsWith('rl'))return false;if(conn!==PEER.conn||d.v!==1||!connected())return true;if(observedConn!==conn){observedConn=conn;highest=0;}
 const b=d.batch;if(d.t==='rlPrepare'&&role()==='B'){if(!validBatch(b)||b.serial<=highest)return true;highest=b.serial;if(b.version!==version()){begin(b,null,'两端游戏版本不同，请刷新后重新连接。');send('rlError',b,{message:'两端游戏版本不同，请刷新后重新连接。'});return true;}begin(b,null);return true;}
 const s=current;if(!s||!same(s.batch,b)||s.conn!==conn)return true;
 if(d.t==='rlReady'){s.remoteReady=true;paint(s);if(role()==='A')finish(s);}
 else if(d.t==='rlCommit'&&role()==='B'){s.remoteReady=true;commit(s);}
 else if(d.t==='rlCancel')cancel(false,d.reason==='返回'?'返回':'同伴取消');
 else if(d.t==='rlRetry'&&role()==='A')retryCurrent();
 else if(d.t==='rlError')error(s,d.message==='两端游戏版本不同，请刷新后重新连接。'?d.message:'同伴有素材加载失败，请一起重试。');
 return true;
}
function defaults(){const paper=!!g.PaperHouseLobby,actors=['actor-a.png','actor-b.png'].map(x=>({id:x,src:'assets/paper-house/'+x}));const foyer=paper?[{id:'lobby',src:'assets/paper-house/lobby.png'},...actors]:[];
 RoomAssets.register('startup:home',paper?foyer:[{id:'home',src:'pic.png'}]);RoomAssets.register('startup:dungeon',foyer);RoomAssets.register('map',g.PaperHouseMap?[{id:'rooms',src:'assets/paper-house/rooms.png'},...actors]:[]);
 (g.ROOM_CATALOG||[]).forEach(r=>RoomAssets.register('room:'+r.id,[{id:'cover:'+r.id,src:'assets/rooms/webp/'+r.id+'.webp',fallback:r.image}]));
}
function navigate(page,push=true){if(g.PEER?.conn?.open)netSend({t:'bye'});const url=new URL(location.href);url.searchParams.delete('role');if(page==='dungeon')url.searchParams.set('m','dungeon');else url.searchParams.delete('m');if(push&&url.href!==location.href)history.pushState({roomScreen:page},'',url);S.mod=page==='dungeon'?'dungeon':null;S.role=null;if(page==='dungeon')renderDungeonMenu();else renderMain();}
function install(){if(installed)return;installed=true;defaults();addEventListener('popstate',()=>{const mode=new URL(location.href).searchParams.get('m');if(!mode||mode==='dungeon')navigate(mode==='dungeon'?'dungeon':'home',false);else location.reload();});const oldEnter=dgEnterHost;dgEnterHost=function(id){if(entering)return oldEnter.apply(this,arguments);if(!mapReady()||current)return;const n=dgNode(id);if(!n||n.done||DUNGEON.locked[id])return;if(n.type==='rest')return oldEnter.apply(this,arguments);start('node',id,oldEnter);};
 const oldBoss=dgBossHost;dgBossHost=function(){if(entering||(bossPermit&&bossPermit.conn===PEER.conn&&bossPermit.route===route()&&bossPermit.node===DUNGEON.boss)){bossPermit=null;return oldBoss.apply(this,arguments);}if(!mapReady()||current)return;start('node',DUNGEON.boss,()=>{bossPermit=null;return oldBoss();});};
 for(const name of ['dgTapHost','dgTapGuest','hostMoveB','dgCheckRing']){const old=g[name];g[name]=function(){if(current||!mapReady())return;return old.apply(this,arguments);};}
 const oldShell=renderDungeonMapShell;renderDungeonMapShell=function(){const r=oldShell.apply(this,arguments);if(!connected()||DUNGEON.over)return r;if(!mapReady()&&!current){if(role()==='A')start('map',null,null);else paint({kind:'map',waiting:true});}else if(mapReady())prefetchNext();return r;};
 const oldClear=clearTimers;clearTimers=function(){stopPrefetch();if(current)cancel(true,'离开');return oldClear.apply(this,arguments);};
 const oldClose=closePeer;closePeer=function(){cancel(false,'离开');bossPermit=null;mapInterrupted=false;mapConn=null;mapRoute=null;observedConn=null;highest=0;release('map');release('node');return oldClose.apply(this,arguments);};
 const oldAbort=dungeonAbort;dungeonAbort=function(){bossPermit=null;if(current)cancel(true,'离开');return oldAbort.apply(this,arguments);};
 // Watchdog packets remain handled by the original accept method, including packets it consumes.
 const oldAccept=DungeonConnection.accept;DungeonConnection.accept=function(conn,d){const accepted=oldAccept.apply(this,arguments);if(current&&(!connected()||['dcPause','dgAbort','dgEnd','bye'].includes(d?.t)))cancel(false,'连接变化');return accepted;};
 const oldDraw=dgDrawMap;dgDrawMap=function(){const result=oldDraw.apply(this,arguments);if(mapInterrupted&&connected()&&!current&&!mapReady()){mapInterrupted=false;if(role()==='A')start('map',null,null);else paint({kind:'map',waiting:true});}return result;};
}
async function boot(){if(g.RoomSession){if(booted)return;booted=true;await g.__roomStylesReady;if((g.__roomLoadFailures||[]).length){document.getElementById('room-boot-detail').textContent='组件加载失败，请刷新重试。';return;}document.getElementById('room-boot')?.remove();hide();g.RoomSession.boot();g.__roomBootComplete=true;last={stage:'idle',error:null};return;}if(booted)return;booted=true;const s={kind:'startup',completed:0,total:0};await g.__roomStylesReady;paint(s);try{const failures=g.__roomLoadFailures||[];if(failures.length)throw new Error('基础界面未加载完成，请刷新重试。');if(!g.RoomAssets||!g.RoomProgression||!g.DungeonConnection||new Set(PLAYGROUNDS.map(p=>p.id)).size!==19||!['lockbox','silhouette','evidence','mirrors','pwslide','lightsearch'].every(id=>g.RoomGameAdapters?.[id]))throw new Error('玩法组件尚未准备完成，请重新加载。');install();
 // Mode validation must remain behind all ordered classic module registrations.
 if(S.mod!=='dungeon'&&!PLAYGROUNDS.some(p=>p.id===S.mod)){S.mod=null;S.role=null;}
 let names=S.mod==='dungeon'?['startup:dungeon','room:'+selectedRoom().id]:!S.mod?['startup:home']:['mode:'+S.mod];const list=RoomAssets.manifest(names);s.total=list.length;paint(s);bootLease=await RoomAssets.prepare(list,{onProgress:p=>{s.completed=p.completed;s.total=p.total;paint(s);}});hide();render();g.__roomBootComplete=true;last={stage:'idle',completed:list.length,total:list.length,error:null};const lease=bootLease;bootLease=null;queueMicrotask(()=>lease.release());
 }catch(e){s.error=e.message||'加载失败，请重新加载。';paint(s);}}
g.RoomLoading={boot,consume,navigate,cancel:()=>cancel(true,'返回'),status:()=>({...last}),mapReady,prefetchStatus:()=>({key:prefetchKey,active:!!prefetch&&!prefetch.controller.signal.aborted})};
})(window);
