(function(g){
'use strict';
let overlay=null,restore=null,inertNodes=[];
// Modal navigation must not send fresh movement commands to window-level game handlers.
g.addEventListener('keydown',e=>{if(overlay&&!['Tab','Escape','Enter',' '].includes(e.key)){e.stopImmediatePropagation();e.preventDefault();}},true);
function close(){if(!overlay)return;overlay.remove();overlay=null;for(const [el,value] of inertNodes)el.inert=value;inertNodes=[];if(restore?.isConnected)restore.focus({preventScroll:true});restore=null;}
function button(label,fn,kind=''){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=kind;b.onclick=fn;return b;}
function dialog(title,text,actions){close();restore=document.activeElement;const root=document.createElement('div');root.className='rs-overlay';root.id='room-shell-dialog';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','rs-dialog-title');const box=document.createElement('section'),h=document.createElement('h2'),p=document.createElement('p');h.id='rs-dialog-title';h.textContent=title;p.textContent=text;box.append(h,p);const group=document.createElement('div');group.className='rs-actions';for(const a of actions)group.append(button(a.label,()=>{close();a.run?.();},a.kind));box.append(group);root.append(box);for(const el of document.querySelectorAll('#app,#room-result')){inertNodes.push([el,el.inert]);el.inert=true;}overlay=root;document.body.append(root);root.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const all=[...root.querySelectorAll('button')];if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0].focus();}}};group.firstElementChild?.focus();return group;}
function confirmExit(){const run=g.RoomSession.current()?.runId;dialog('退出本局？','本局进度将丢弃。你和同伴一起返回密室选择，连接会保留。',[{label:'继续游戏'},{label:'退出本局',kind:'danger',run:()=>{if(run&&g.RoomSession.current()?.runId===run)g.RoomSession.exitRound();}}]);}
function confirmLeave(){dialog('离开房间？','离开后需要重新创建或输入房间码与同伴连接。',[{label:'留在房间'},{label:'离开房间',kind:'danger',run:()=>g.RoomSession.home()}]);}
function settings(){const group=dialog('声音与震动','设置立即生效，关闭后回到当前画面。',[]);for(const [key,label,set]of [['sound','声音','setSound'],['haptics','震动','setHaptics']]){const b=button('',()=>{g.GameFeedback?.[set](!g.GameFeedback.preferences()[key]);update();});function update(){const on=g.GameFeedback?.preferences()[key]!==false;b.textContent=label+'：'+(on?'开':'关');b.setAttribute('aria-pressed',String(on));}update();group.append(b);}const dismiss=button('×',close,'rs-settings-close');dismiss.setAttribute('aria-label','关闭设置');const box=group.parentElement;box.classList.add('rs-settings');box.prepend(dismiss);dismiss.focus();}
function menu(options={}){options.release?.();dialog('游戏菜单','菜单不会暂停本局；有计时的玩法仍会继续计时。',[{label:'继续游戏',kind:'primary'},{label:'查看分工',run:()=>dialog('我的分工',options.help||'与同伴交换各自看到的线索，再按本端操作提示配合。',[{label:'返回游戏',kind:'primary'}])},{label:'声音与震动',run:settings},{label:'退出本局',kind:'danger',run:confirmExit}]);}
g.RoomShell=Object.freeze({close,dialog,settings,menu,confirmExit,confirmLeave,isOpen:()=>!!overlay});
})(window);
